# Generated by Django 5.2.7 on 2025-11-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="discord_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Unique Discord user ID. Set upon linking via bot or site.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="discord_linked_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when Discord was linked.", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["discord_id"], name="users_custo_discord_94cf4e_idx"
            ),
        ),
    ]
