# Generated by Django 5.2.7 on 2025-11-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_discord_id_customuser_discord_linked_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customuser",
            name="users_custo_discord_94cf4e_idx",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="discord_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="discord_linked_at",
        ),
    ]
