# Generated by Django 5.2.7 on 2025-12-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_customuser_user_timezone"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customuser",
            name="users_custo_usernam_a8ad03_idx",
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="users_custo_email_c80f75_idx"),
        ),
    ]
