# Generated by Django 5.2.7 on 2025-12-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_users_custo_usernam_a8ad03_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
