# Generated by Django 5.2.7 on 2025-12-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_region",
            field=models.CharField(
                blank=True,
                choices=[("NA", "NA"), ("EU", "EU"), ("JP", "JP"), ("AS", "AS")],
                default=None,
                help_text="User's preferred default region filter for games.",
                max_length=2,
                null=True,
            ),
        ),
    ]
