# Generated by Django 5.2.7 on 2025-12-31 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0002_2_10"),
        ("users", "0008_alter_customuser_default_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="premium_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ad_free", "Ad Free"),
                    ("premium_monthly", "Premium Monthly"),
                    ("premium_yearly", "Premium Yearly"),
                    ("supporter", "Supporter"),
                ],
                help_text="User's subscription tier.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Customer ID for this user.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="djstripe.subscription",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
            },
        ),
    ]
