# Generated by Django 5.2.7 on 2026-01-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_premium_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="use_24hr_clock",
            field=models.BooleanField(
                default=False,
                help_text="Use 24-hour time format (23:00) instead of 12-hour AM/PM format (11:00 PM)",
            ),
        ),
    ]
