# Generated by Django 5.2.7 on 2026-02-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_delete_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User's email notification preferences",
            ),
        ),
    ]
