# Generated by Django 5.2.7 on 2026-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_customuser_email_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="paypal_cancel_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the PayPal subscription will expire after cancellation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="paypal_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="PayPal Subscription ID for active subscription.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_provider",
            field=models.CharField(
                blank=True,
                choices=[("stripe", "Stripe"), ("paypal", "PayPal")],
                help_text="Which payment provider manages the current subscription.",
                max_length=10,
                null=True,
            ),
        ),
    ]
