# Generated by Django 5.2.7 on 2026-02-18 19:10

from django.db import migrations


def backfill_stripe_provider(apps, schema_editor):
    """Set subscription_provider='stripe' for existing Stripe subscribers."""
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(
        stripe_customer_id__isnull=False,
        premium_tier__isnull=False,
    ).exclude(
        stripe_customer_id='',
    ).exclude(
        premium_tier='',
    ).update(subscription_provider='stripe')


def reverse_backfill(apps, schema_editor):
    """Clear subscription_provider for all users."""
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(subscription_provider='stripe').update(subscription_provider=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_add_paypal_subscription_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_stripe_provider, reverse_backfill),
    ]
