# Generated by Django 5.2.7 on 2026-02-19 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_backfill_stripe_subscription_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="When this subscription period began."
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this period ended. NULL means currently active.",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("paypal", "PayPal")],
                        help_text="Which payment provider for this period.",
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Admin notes (e.g., 'backfilled from launch').",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Period",
                "verbose_name_plural": "Subscription Periods",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "ended_at"], name="subperiod_user_active_idx"
                    )
                ],
            },
        ),
    ]
