# Generated by Django 5.2.7 on 2026-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_add_subscription_period"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscriptionperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("user",),
                name="one_open_period_per_user",
            ),
        ),
    ]
