# Generated by Django 5.2.7 on 2026-02-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_add_one_open_period_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveIndex(
            model_name="customuser",
            name="users_custo_email_c80f75_idx",
        ),
    ]
