# Generated by Django 5.2.7 on 2026-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="browse_defaults",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-page saved filter defaults. Keys: 'games', 'trophies', 'profiles'.",
            ),
        ),
    ]
