# Generated by Django 5.2.7 on 2026-08-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_add_browse_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="timezone_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user explicitly confirmed or changed their timezone. Null = never asked/answered.",
                null=True,
            ),
        ),
    ]
