# Generated by Django 5.2.7 on 2026-08-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_timezone_confirmed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="premium_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("premium_monthly", "Premium Monthly"),
                    ("premium_yearly", "Premium Yearly"),
                    ("supporter", "Supporter"),
                ],
                help_text="User's subscription tier.",
                max_length=50,
                null=True,
            ),
        ),
    ]
