# Generated by Django 5.2.7 on 2026-08-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_customuser_premium_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="premium_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("premium_monthly", "Premium Monthly"),
                    ("premium_yearly", "Premium Yearly"),
                    ("supporter", "Supporter"),
                    ("backer", "Backer"),
                    ("contributor", "Contributor"),
                    ("patron", "Patron"),
                    ("sponsor", "Sponsor"),
                    ("benefactor", "Benefactor"),
                    ("cornerstone", "Cornerstone"),
                ],
                help_text="User's subscription tier.",
                max_length=50,
                null=True,
            ),
        ),
    ]
