# Generated by Django 5.2.7 on 2026-08-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_supporter_ladder_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("admin", "Admin"), ("moderator", "Moderator")],
                default="",
                help_text="Service role. Admins keep Django-admin access (is_staff syncs to this); moderators get the mod mark and mod-level access only.",
                max_length=10,
            ),
        ),
    ]
