# Generated by Django 5.2.7 on 2026-08-21 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_supporter_ladder_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionperiod",
            name="provider",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("paypal", "PayPal"), ("gift", "Gift")],
                help_text="Which payment provider for this period.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PremiumGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "tier_slug",
                    models.CharField(
                        help_text="Ladder slug; display and records only.",
                        max_length=50,
                    ),
                ),
                ("months", models.PositiveSmallIntegerField(help_text="1 or 12.")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What was paid. 0 for comps.",
                        max_digits=8,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("issued", "Issued"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("void", "Void"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("comp", "Comp"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "purchaser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_purchased",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_redeemed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Premium Grant",
                "verbose_name_plural": "Premium Grants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["redeemed_by", "status", "expires_at"],
                        name="grant_active_lookup_idx",
                    )
                ],
            },
        ),
    ]
