# Generated by Django 5.2.7 on 2026-08-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_backfill_roles_and_marks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="default_region",
        ),
    ]
