# Generated by Django 5.2.7 on 2026-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_remove_default_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ui_flags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="One-shot UI education flags. Presence of a key means dismissed. Keys: 'career_explainer'.",
            ),
        ),
    ]
