# Generated by Django 5.2.7 on 2026-09-05 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_customuser_ui_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("quick_takes", "Writing quick takes"),
                            ("reports", "Filing reports and flags"),
                            ("all_ugc", "All user-submitted content"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="REQUIRED by the service, like every other audited action."
                    ),
                ),
                ("created_by_label", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL means indefinite. ONE field rather than a boolean plus a duration, because two fields describing one fact are two fields that can disagree -- and the disagreement would be silent, since nothing reads them together.",
                        null=True,
                    ),
                ),
                ("lifted_at", models.DateTimeField(blank=True, null=True)),
                ("lifted_by_label", models.CharField(blank=True, max_length=150)),
                ("lift_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restrictions_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lifted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restrictions_lifted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The account restricted. CASCADE: a deleted account has nothing left to restrict, and the AdminAction that applied it keeps the frozen name for the record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "lifted_at", "expires_at"],
                        name="restriction_live_idx",
                    ),
                    models.Index(
                        fields=["-created_at", "-id"], name="restriction_recent_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reason__regex", "\\S")),
                        name="restriction_reason_is_not_blank",
                    )
                ],
            },
        ),
    ]
