# Generated by Django 5.2.7 on 2026-09-05 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0331_moderation_proactive_reversal"),
        ("users", "0026_user_restriction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrestriction",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The PSN profile behind the account, and the half that actually survives.\n\nBoth, because neither alone is durable. The FIRST cut keyed on the user only, reasoning that a restriction is an account fact and that hanging it off the profile would make unlinking PSN an escape hatch. True, and it missed the bigger hatch: Settings has a self-service DELETE ACCOUNT, `Profile.user` is SET_NULL, and `link_profile_to_user` reattaches THE SAME profile row to a new account. So delete, re-register, re-verify the same PSN account, and a CASCADE took every restriction with it -- while the trophies, badges, ranking and handle all came back. The profile is what persists across that, so the profile is what a restriction has to remember.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restrictions",
                to="trophies.profile",
            ),
        ),
        migrations.AlterField(
            model_name="userrestriction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The account restricted. SET_NULL, not CASCADE -- see `profile` below.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restrictions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userrestriction",
            index=models.Index(
                fields=["profile", "lifted_at", "expires_at"],
                name="restriction_live_prof_idx",
            ),
        ),
    ]
