# Generated by Django 5.2.7 on 2026-02-20 19:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trophies", "0147_alter_milestone_criteria_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fundraiser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name shown on the fundraiser page.",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='URL identifier, e.g. "badge-artwork"',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Rich description shown on the fundraiser page."
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[("badge_artwork", "Badge Artwork")],
                        default="badge_artwork",
                        help_text="Determines reward mechanics. badge_artwork enables badge claiming.",
                        max_length=30,
                    ),
                ),
                (
                    "banner_active",
                    models.BooleanField(
                        default=False,
                        help_text="Show site-wide banner linking to this fundraiser (only while campaign is live).",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When the fundraiser opens to the public."
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="When the fundraiser closes (page becomes read-only)."
                    ),
                ),
                (
                    "minimum_donation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Minimum donation amount in USD.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00"))
                        ],
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("paypal", "PayPal")],
                        max_length=10,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        help_text="Stripe Checkout Session ID or PayPal Order ID.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "badge_picks_earned",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="floor(amount / 10), calculated at completion for badge_artwork campaigns.",
                    ),
                ),
                ("badge_picks_used", models.PositiveIntegerField(default=0)),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="If True, donor is hidden from the public donor wall.",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Optional public message from the donor.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="Denormalized for donor wall display.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="trophies.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fundraiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="fundraiser.fundraiser",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationBadgeClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_slug", models.CharField(db_index=True, max_length=100)),
                (
                    "series_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized display name at time of claim.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("claimed", "Claimed"),
                            ("in_progress", "Artwork In Progress"),
                            ("completed", "Artwork Complete"),
                        ],
                        default="claimed",
                        max_length=15,
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the artwork was uploaded for this badge series.",
                        null=True,
                    ),
                ),
                (
                    "badge",
                    models.OneToOneField(
                        help_text="Tier 1 badge of the series. OneToOne enforces one claim per badge.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artwork_claim",
                        to="trophies.badge",
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_claims",
                        to="fundraiser.donation",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_claims",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-claimed_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="fundraiser__status_8b441a_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["fundraiser", "status", "-completed_at"],
                name="fundraiser__fundrai_24b5ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["user", "-created_at"], name="fundraiser__user_id_f5acaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["provider_transaction_id"],
                name="fundraiser__provide_d25eb8_idx",
            ),
        ),
    ]
