# Generated by Django 5.2.7 on 2026-02-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraiser", "0001_initial"),
        ("trophies", "0147_alter_milestone_criteria_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationbadgeclaim",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="badge_claims",
                to="trophies.profile",
            ),
        ),
    ]
