# Generated by Django 5.2.7 on 2026-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraiser", "0004_fundraiser_banner_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="badge_picks_earned",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Incremental picks from cumulative donations: floor(cumulative_total / 10) minus prior picks earned.",
            ),
        ),
    ]
