# Generated by Django 5.2.7 on 2026-08-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraiser", "0006_claim_series_fk"),
        ("trophies", "0306_user_group_badge_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationbadgeclaim",
            name="series",
            field=models.OneToOneField(
                help_text="The claimed badge series. OneToOne enforces one claim per series.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artwork_claim",
                to="trophies.badgeseries",
            ),
        ),
    ]
