# Generated by Django 5.2.7 on 2026-02-08 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("game", "Game"),
                            ("checklist", "Checklist"),
                            ("badge", "Badge Series"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        db_index=True,
                        help_text="PK or slug for the object. Profile/Game/Checklist use integer PK as string; Badge uses series_slug.",
                        max_length=100,
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Stored for anonymous viewers only. Consider scrubbing after 90 days for GDPR compliance.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["page_type", "object_id"], name="pv_type_object_idx"
                    ),
                    models.Index(
                        fields=["page_type", "object_id", "viewed_at"],
                        name="pv_type_object_date_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("guide_visit", "Guide Visit"),
                            ("share_card_download", "Platinum Share Card Download"),
                            ("recap_share_generate", "Recap Share Card Generate"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Related object ID: guide slug, earned_trophy_id, or recap 'YYYY-MM' string.",
                        max_length=100,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "object_id"], name="se_type_object_idx"
                    )
                ],
            },
        ),
    ]
