# Generated by Django 5.2.7 on 2026-02-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guide_visit", "Guide Visit"),
                    ("share_card_download", "Platinum Share Card Download"),
                    ("recap_share_generate", "Recap Share Card Generate (Legacy)"),
                    ("recap_intro_view", "Recap Intro Slide View"),
                    ("recap_summary_view", "Recap Summary Slide View"),
                    ("recap_image_download", "Recap Image Download"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
