# Generated by Django 5.2.7 on 2026-02-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_siteevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guide_visit", "Guide Visit"),
                    ("share_card_download", "Platinum Share Card Download"),
                    ("recap_page_view", "Monthly Recap Page View"),
                    ("recap_share_generate", "Monthly Recap Share Card View"),
                    ("recap_image_download", "Recap Image Download"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
