# Generated by Django 5.2.7 on 2026-02-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_siteevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "index_page_view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total view count for the index/home page (deduplicated via PageView tracking).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AlterField(
            model_name="pageview",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("profile", "Profile"),
                    ("game", "Game"),
                    ("checklist", "Checklist"),
                    ("badge", "Badge Series"),
                    ("index", "Index Page"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
