# Generated by Django 5.2.7 on 2026-02-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_alter_pageview_page_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="User ID if authenticated during session creation",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address for anonymous users",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="Session end time (optional)", null=True
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of pages viewed in this session"
                    ),
                ),
                (
                    "page_sequence",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sequence of pages visited: [{'page_type': ..., 'object_id': ..., 'timestamp': ...}]",
                    ),
                ),
                (
                    "referrer",
                    models.URLField(
                        blank=True,
                        help_text="HTTP Referer header",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="User-Agent string",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Session",
                "verbose_name_plural": "Analytics Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="pageview",
            name="session_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Analytics session ID. Null for pre-migration records (before session-based tracking).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="session_tracking_enabled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when session-based tracking was enabled. Used for UI display '(since X date)' label.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session_id", "viewed_at"], name="pv_session_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["page_type", "object_id", "session_id"],
                name="pv_type_obj_session_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(
                fields=["user_id", "created_at"], name="as_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticssession",
            index=models.Index(fields=["last_activity"], name="as_last_activity_idx"),
        ),
    ]
