# Generated by Django 5.2.7 on 2026-02-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_analyticssession_pageview_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageview",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("profile", "Profile"),
                    ("game", "Game"),
                    ("checklist", "Checklist"),
                    ("badge", "Badge Series"),
                    ("index", "Index Page"),
                    ("profiles_list", "Profiles List"),
                    ("games_list", "Games List"),
                    ("trophies_list", "Trophies List"),
                    ("badges_list", "Badges List"),
                    ("guides_list", "Guides List"),
                    ("milestones_list", "Milestones List"),
                    ("badge_leaderboard", "Badge Leaderboard"),
                    ("overall_leaderboard", "Overall Badge Leaderboard"),
                    ("trophy_case", "Trophy Case"),
                    ("my_checklists", "My Checklists"),
                    ("my_shareables", "My Shareables"),
                    ("checklist_edit", "Checklist Edit"),
                    ("settings", "Settings"),
                    ("subscription", "Subscription Management"),
                    ("email_prefs", "Email Preferences"),
                    ("notifications", "Notifications"),
                    ("recap", "Monthly Recap"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
