# Generated by Django 5.2.7 on 2026-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_pageview_page_type_alter_siteevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageview",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("profile", "Profile"),
                    ("game", "Game"),
                    ("guide", "Guide"),
                    ("badge", "Badge Series"),
                    ("index", "Index Page"),
                    ("profiles_list", "Profiles List"),
                    ("games_list", "Games List"),
                    ("trophies_list", "Trophies List"),
                    ("badges_list", "Badges List"),
                    ("guides_list", "Guides List"),
                    ("milestones_list", "Milestones List"),
                    ("badge_leaderboard", "Badge Leaderboard"),
                    ("overall_leaderboard", "Overall Badge Leaderboard"),
                    ("trophy_case", "Trophy Case"),
                    ("my_guides", "My Guides"),
                    ("my_shareables", "My Shareables"),
                    ("guide_edit", "Guide Edit"),
                    ("settings", "Settings"),
                    ("subscription", "Subscription Management"),
                    ("email_prefs", "Email Preferences"),
                    ("notifications", "Notifications"),
                    ("recap", "Monthly Recap"),
                    ("game_list", "Game List"),
                    ("game_lists_browse", "Browse Game Lists"),
                    ("my_lists", "My Lists"),
                    ("game_list_edit", "Game List Edit"),
                    ("challenges_browse", "Challenge Hub"),
                    ("my_challenges", "My Challenges"),
                    ("az_challenge", "A-Z Challenge"),
                    ("az_challenge_setup", "A-Z Challenge Setup"),
                    ("az_challenge_edit", "A-Z Challenge Edit"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="siteevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guide_visit", "Guide Visit"),
                    ("share_card_download", "Platinum Share Card Download"),
                    ("recap_page_view", "Monthly Recap Page View"),
                    ("recap_share_generate", "Monthly Recap Share Card View"),
                    ("recap_image_download", "Recap Image Download"),
                    ("game_list_create", "Game List Created"),
                    ("game_list_share", "Game List Shared"),
                    ("challenge_create", "Challenge Created"),
                    ("challenge_complete", "Challenge Completed"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
