# Generated by Django 5.2.7 on 2026-02-19 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_siteevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("payment_failed", "Payment Failed Warning"),
                            ("payment_failed_final", "Payment Failed Final Warning"),
                            ("subscription_cancelled", "Subscription Cancelled"),
                            ("subscription_welcome", "Subscription Welcome"),
                            ("payment_succeeded", "Payment Succeeded"),
                            ("email_verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                            ("monthly_recap", "Monthly Recap"),
                            ("admin_announcement", "Admin Announcement"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("suppressed", "Suppressed (Preference)"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "triggered_by",
                    models.CharField(
                        default="system",
                        help_text="Origin: system, webhook, admin_manual, management_command",
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_emaill_user_id_2ba407_idx",
                    ),
                    models.Index(
                        fields=["email_type", "-created_at"],
                        name="core_emaill_email_t_166706_idx",
                    ),
                ],
            },
        ),
    ]
