# Generated by Django 5.2.7 on 2026-02-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_emaillog_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("payment_failed", "Payment Failed Warning"),
                    ("payment_failed_final", "Payment Failed Final Warning"),
                    ("subscription_cancelled", "Subscription Cancelled"),
                    ("subscription_welcome", "Subscription Welcome"),
                    ("payment_succeeded", "Payment Succeeded"),
                    ("payment_action_required", "Payment Action Required"),
                    ("email_verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("monthly_recap", "Monthly Recap"),
                    ("admin_announcement", "Admin Announcement"),
                    ("donation_receipt", "Donation Receipt"),
                    ("badge_claim_confirmation", "Badge Claim Confirmation"),
                    ("artwork_complete", "Badge Artwork Complete"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
