# Generated by Django 5.2.7 on 2026-03-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_fundraiser_email_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guide_visit", "Guide Visit"),
                    ("share_card_download", "Platinum Share Card Download"),
                    ("recap_page_view", "Monthly Recap Page View"),
                    ("recap_share_generate", "Monthly Recap Share Card View"),
                    ("recap_image_download", "Recap Image Download"),
                    ("game_list_create", "Game List Created"),
                    ("game_list_share", "Game List Shared"),
                    ("challenge_create", "Challenge Created"),
                    ("challenge_complete", "Challenge Completed"),
                    ("easter_egg", "Easter Egg"),
                    ("sync_search", "Sync Search"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
