# Generated by Django 5.2.7 on 2026-03-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_siteevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("payment_failed", "Payment Failed Warning"),
                    ("payment_failed_final", "Payment Failed Final Warning"),
                    ("subscription_cancelled", "Subscription Cancelled"),
                    ("subscription_welcome", "Subscription Welcome"),
                    ("payment_succeeded", "Payment Succeeded"),
                    ("payment_action_required", "Payment Action Required"),
                    ("email_verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("monthly_recap", "Monthly Recap"),
                    ("weekly_digest", "Weekly Digest"),
                    ("badge_earned", "Badge Earned"),
                    ("milestone_achieved", "Milestone Achieved"),
                    ("welcome", "Welcome"),
                    ("admin_announcement", "Admin Announcement"),
                    ("donation_receipt", "Donation Receipt"),
                    ("badge_claim_confirmation", "Badge Claim Confirmation"),
                    ("artwork_complete", "Badge Artwork Complete"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
