# Generated by Django 5.2.7 on 2026-03-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_email_system_enhancements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticssession",
            name="page_sequence",
        ),
    ]
