# Generated by Django 5.2.7 on 2026-04-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_siteevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guide_visit", "Guide Visit"),
                    ("share_card_download", "Platinum Share Card Download"),
                    ("recap_page_view", "Monthly Recap Page View"),
                    ("recap_share_generate", "Monthly Recap Share Card View"),
                    ("recap_image_download", "Recap Image Download"),
                    ("game_list_create", "Game List Created"),
                    ("game_list_share", "Game List Shared"),
                    ("challenge_create", "Challenge Created"),
                    ("challenge_complete", "Challenge Completed"),
                    ("easter_egg", "Easter Egg"),
                    ("sync_search", "Sync Search"),
                    ("welcome_tour_complete", "Welcome Tour Completed"),
                    ("welcome_tour_skip", "Welcome Tour Skipped"),
                    ("game_detail_tour_complete", "Game Detail Tour Completed"),
                    ("game_detail_tour_skip", "Game Detail Tour Skipped"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
