# Generated by Django 5.2.7 on 2026-04-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_siteevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticssession",
            name="is_bot",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if the User-Agent matched the bot regex (or was empty/very short).",
            ),
        ),
    ]
