# Generated by Django 5.2.7 on 2026-04-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_analyticssession_is_bot"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityTrophyDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The ET calendar day these stats cover.", unique=True
                    ),
                ),
                ("total_trophies", models.PositiveIntegerField(default=0)),
                ("total_platinums", models.PositiveIntegerField(default=0)),
                ("total_ultra_rares", models.PositiveIntegerField(default=0)),
                ("pp_score", models.PositiveIntegerField(default=0)),
                (
                    "eligible_profile_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Snapshot of how many Discord-linked profiles existed when this day was computed. Internal diagnostic.",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the Discord webhook post succeeded. Idempotency gate.",
                        null=True,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Community Trophy Day",
                "verbose_name_plural": "Community Trophy Days",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-pp_score"], name="ctd_pp_score_idx"),
                    models.Index(fields=["-total_platinums"], name="ctd_plat_idx"),
                    models.Index(fields=["-total_trophies"], name="ctd_trophies_idx"),
                    models.Index(fields=["-total_ultra_rares"], name="ctd_ur_idx"),
                ],
            },
        ),
    ]
