# Generated by Django 5.2.7 on 2026-08-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_communitytrophyday"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalyticsSession",
        ),
        migrations.DeleteModel(
            name="PageView",
        ),
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
