# Generated by Django 5.2.7 on 2026-09-05 17:42

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_emaillog_email_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        help_text="The actor's name at the time, so the entry still reads once the account is gone.",
                        max_length=150,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("restriction_applied", "Restriction applied"),
                            ("restriction_lifted", "Restriction lifted"),
                            (
                                "subscription_force_deactivated",
                                "Subscription force-deactivated",
                            ),
                            ("subscription_email_resent", "Subscription email resent"),
                            ("claim_status_changed", "Badge claim status changed"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="REQUIRED, and required by the service rather than by a form the next caller might not use -- a management command, a shell, or a Django-admin bulk action that renders no form at all."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject_label",
                    models.CharField(
                        blank=True,
                        help_text="The subject's name at the time. Same reason as `actor_label`.",
                        max_length=150,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user", "User"),
                            ("subscription", "Subscription"),
                            ("restriction", "Restriction"),
                            ("badge_claim", "Badge claim"),
                            ("fundraiser", "Fundraiser"),
                            ("system", "System"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of the thing acted on, as TEXT. Not an integer: a Stripe subscription id, a badge-series slug and a primary key all have to fit in this one column, and a log that can only reference integer PKs cannot describe half the actions here.",
                        max_length=255,
                    ),
                ),
                (
                    "target_label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable identification of what was acted on, captured at the time.",
                        max_length=255,
                    ),
                ),
                (
                    "changed",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="{field: [before, after]} for whatever the action actually WROTE -- read from the object, never assumed. An empty dict is a real outcome, not a bug. DjangoJSONEncoder so a datetime or Decimal cannot raise mid-transaction.",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="What the action was ABOUT but did not change. Kept beside the diff rather than inside it, so a diff view cannot render it as a field that was modified.",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        db_index=False,
                        help_text="The admin who acted. SET_NULL so deleting a staff account never erases what they did -- `actor_label` keeps the name.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this entry UNDOES an earlier one -- lifting a restriction, most of all. A reversal is its own entry rather than an edit to the original: an audit trail that can be rewritten is not one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by_action",
                        to="core.adminaction",
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        help_text='The person this was done TO, as distinct from the thing that was changed. This is what makes "everything ever done to this account" a single indexed query. Null for system actions with nobody on the other end.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "-id"], name="adminaction_recent_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at", "-id"],
                        name="adminaction_actor_idx",
                    ),
                    models.Index(
                        fields=["subject_user", "-created_at", "-id"],
                        name="adminaction_subject_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at", "-id"],
                        name="adminaction_action_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reverses__isnull", False)),
                        fields=("reverses",),
                        name="adminaction_one_reversal_per_action",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason__regex", "\\S")),
                        name="adminaction_reason_is_not_blank",
                    ),
                ],
            },
        ),
    ]
