# Generated by Django 5.2.7 on 2026-06-08 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "trophies",
            "0243_badge_developer_badge_franchise_badge_rarity_class_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtRevealEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name shown on the event page and banner.",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='URL identifier, e.g. "summer-2026".',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional intro shown on the event page."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Master switch. When off the event is hidden everywhere and the cron skips it.",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="Platinums earned from this moment onward count toward reveals."
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional hard close. Leave blank to run until all artwork is revealed.",
                        null=True,
                    ),
                ),
                (
                    "platinums_per_reveal",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Community platinums needed to unlock each successive artwork.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "banner_active",
                    models.BooleanField(
                        default=False,
                        help_text="Show the site-wide progress banner (only while the event is live).",
                    ),
                ),
                (
                    "banner_text",
                    models.CharField(
                        blank=True,
                        default="The community is revealing new badge artwork!",
                        help_text="Message shown in the banner before the CTA.",
                        max_length=200,
                    ),
                ),
                (
                    "banner_dismiss_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Days the banner stays dismissed after a user closes it. 0 means it reappears every session.",
                    ),
                ),
                (
                    "last_platinum_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Most recent community badge-platinum count (updated by the cron).",
                    ),
                ),
                ("last_counted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtRevealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Reveal position, 1-based. Lower numbers reveal first."
                    ),
                ),
                (
                    "artwork",
                    models.ImageField(
                        help_text="The to-be-revealed artwork. Hidden until released, then copied onto the badge.",
                        upload_to="art_reveal/",
                    ),
                ),
                (
                    "placeholder_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional teaser shown on the locked tile before release (defaults to a generic lock).",
                        max_length=120,
                    ),
                ),
                ("released", models.BooleanField(default=False)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "badge",
                    models.ForeignKey(
                        help_text="Tier-1 (base) badge of the series whose art is revealed. Tiers 2-4 inherit the art.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="art_reveal_items",
                        to="trophies.badge",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="art_reveal.artrevealevent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "order"), name="uniq_artreveal_event_order"
                    ),
                    models.UniqueConstraint(
                        fields=("event", "badge"), name="uniq_artreveal_event_badge"
                    ),
                ],
            },
        ),
    ]
