# Generated by Django 5.2.7 on 2026-06-08 15:34

import art_reveal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art_reveal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artrevealitem",
            name="artwork",
            field=models.ImageField(
                help_text="The to-be-revealed artwork. Hidden until released, then copied onto the badge.",
                upload_to=art_reveal.models._artwork_upload_path,
            ),
        ),
    ]
