# Generated by Django 5.2.7 on 2026-06-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art_reveal", "0002_alter_artrevealitem_artwork"),
        (
            "trophies",
            "0243_badge_developer_badge_franchise_badge_rarity_class_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="artrevealitem",
            name="badge",
            field=models.ForeignKey(
                help_text="The badge SERIES to reveal (pick its tier-1 base badge). The uploaded artwork is the series art and propagates to all four tiers on release.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="art_reveal_items",
                to="trophies.badge",
            ),
        ),
    ]
