# Generated by Django 5.2.7 on 2026-08-08 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trophies", "0280_company_representative_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable key (URL anchor, seed lookup).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One line: what this celebrates.",
                        max_length=255,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide-style icon key (template renders it).",
                        max_length=64,
                    ),
                ),
                ("metric", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional grouping bucket (unused at v1; flat list).",
                        max_length=64,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Uncheck to hide from the catalog. Earned history is preserved.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MilestoneTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        help_text="1-based rung order (authority for ordering + 'highest earned')."
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        help_text="Metric value required to earn this rung."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional flavour name (e.g. 'Legend'); blank = numeric display.",
                        max_length=64,
                    ),
                ),
                (
                    "discord_role_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord role granted when this rung is reached (optional).",
                        null=True,
                    ),
                ),
                (
                    "earned_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Denormalized global earn counter -> rarity %. F()-bumped on award, recomputed nightly.",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="milestones.milestone",
                    ),
                ),
            ],
            options={
                "ordering": ["milestone", "index"],
                "unique_together": {("milestone", "index")},
            },
        ),
        migrations.CreateModel(
            name="EarnedMilestoneTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_milestone_tiers",
                        to="trophies.profile",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="milestones.milestonetier",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["profile"], name="ms_earned_profile_idx")
                ],
                "unique_together": {("profile", "tier")},
            },
        ),
        migrations.CreateModel(
            name="UserMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_value",
                    models.PositiveIntegerField(
                        default=0, help_text="Last computed metric value."
                    ),
                ),
                (
                    "highest_tier_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Highest earned rung index (0 = none)."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="milestones.milestone",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_progress",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["profile"], name="ms_progress_profile_idx")
                ],
                "unique_together": {("profile", "milestone")},
            },
        ),
    ]
