# Generated by Django 5.2.7 on 2026-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milestones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="accent",
            field=models.CharField(
                blank=True,
                help_text="Optional CSS accent colour (hex or token) tinting this milestone's icon/rungs/progress. Blank = the default cyan.",
                max_length=32,
            ),
        ),
    ]
