# Generated by Django 5.2.7 on 2026-09-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trophies", "0336_contract_announcement_posted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("tier", "Tier list"),
                            ("grid", "Grid"),
                            ("poll", "Poll"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=300),
                ),
                ("grid_columns", models.PositiveSmallIntegerField(default=3)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Opt-IN. A prompt is private until its author publishes it.",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="No new responses. Existing ones stay readable and their authors may still edit.",
                    ),
                ),
                ("game_count", models.PositiveIntegerField(default=0)),
                ("response_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The hunter who set it. Prompts do not have co-authors.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=24)),
                (
                    "colour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("grey", "Grey"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buckets",
                        to="prompts.prompt",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="PromptGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_entries",
                        to="trophies.concept",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="prompts.prompt",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="PromptLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_likes",
                        to="trophies.profile",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="prompts.prompt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Answering is publishing. Unset it to keep an arrangement to yourself.",
                    ),
                ),
                ("placement_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_responses",
                        to="trophies.profile",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="prompts.prompt",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("single_slot", models.BooleanField()),
                ("position", models.PositiveIntegerField(default=0)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="prompts.promptbucket",
                    ),
                ),
                (
                    "prompt_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="prompts.promptgame",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="prompts.promptresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="PromptResponseLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_response_likes",
                        to="trophies.profile",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="prompts.promptresponse",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["owner", "-updated_at"],
                name="prm_owner_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                condition=models.Q(("is_deleted", False), ("is_public", True)),
                fields=["shape", "-response_count", "-created_at"],
                name="prm_public_shape_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                condition=models.Q(("is_deleted", False), ("is_public", True)),
                fields=["shape", "-like_count", "-created_at"],
                name="prm_public_liked_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                condition=models.Q(("is_deleted", False), ("is_public", True)),
                fields=["shape", "-created_at"],
                name="prm_public_new_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="prompt",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="prompt_title_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="prompt",
            constraint=models.CheckConstraint(
                condition=models.Q(("shape__in", ["tier", "grid", "poll"])),
                name="prompt_shape_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="prompt",
            constraint=models.CheckConstraint(
                condition=models.Q(("grid_columns__gte", 1), ("grid_columns__lte", 6)),
                name="prompt_grid_columns_sane",
            ),
        ),
        migrations.AddIndex(
            model_name="promptbucket",
            index=models.Index(
                fields=["prompt", "position"], name="prmbucket_position_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptbucket",
            constraint=models.CheckConstraint(
                condition=models.Q(("label", ""), _negated=True),
                name="promptbucket_label_not_blank",
            ),
        ),
        migrations.AddIndex(
            model_name="promptgame",
            index=models.Index(
                fields=["prompt", "position"], name="prmgame_position_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptgame",
            constraint=models.UniqueConstraint(
                fields=("prompt", "concept"), name="promptgame_unique_concept"
            ),
        ),
        migrations.AddIndex(
            model_name="promptlike",
            index=models.Index(
                fields=["profile", "-created_at"], name="prmlike_profile_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptlike",
            constraint=models.UniqueConstraint(
                fields=("prompt", "profile"), name="promptlike_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="promptresponse",
            index=models.Index(
                condition=models.Q(("is_public", True)),
                fields=["prompt", "-like_count"],
                name="prmresp_liked_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptresponse",
            index=models.Index(
                condition=models.Q(("is_public", True)),
                fields=["prompt", "-placement_count"],
                name="prmresp_filled_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptresponse",
            index=models.Index(
                condition=models.Q(("is_public", True)),
                fields=["prompt", "-created_at"],
                name="prmresp_new_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptresponse",
            index=models.Index(
                fields=["profile", "-updated_at"], name="prmresp_profile_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptresponse",
            constraint=models.UniqueConstraint(
                fields=("prompt", "profile"), name="promptresponse_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="promptplacement",
            index=models.Index(
                fields=["response", "bucket", "position"], name="prmplace_editor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promptplacement",
            index=models.Index(
                fields=["bucket", "prompt_game"], name="prmplace_tally_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptplacement",
            constraint=models.UniqueConstraint(
                fields=("response", "prompt_game"), name="promptplacement_unique_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("single_slot", True)),
                fields=("response", "bucket"),
                name="promptplacement_single_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="promptresponselike",
            index=models.Index(
                fields=["profile", "-created_at"], name="prmresplike_profile_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptresponselike",
            constraint=models.UniqueConstraint(
                fields=("response", "profile"), name="promptresponselike_unique"
            ),
        ),
    ]
