# Generated by Django 5.2.7 on 2026-09-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
        ("trophies", "0336_contract_announcement_posted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prompt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="promptresponse",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="prompt",
            name="prm_owner_idx",
        ),
        migrations.RemoveIndex(
            model_name="promptresponse",
            name="prmresp_profile_idx",
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["owner", "-created_at"],
                name="prm_owner_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptresponse",
            index=models.Index(
                fields=["profile", "-created_at"], name="prmresp_profile_idx"
            ),
        ),
    ]
