# Generated by Django 5.2.7 on 2026-09-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_alter_prompt_options_alter_promptresponse_options_and_more"),
        ("trophies", "0336_contract_announcement_posted"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="promptplacement",
            name="promptplacement_unique_game",
        ),
        migrations.AddField(
            model_name="prompt",
            name="allow_duplicates",
            field=models.BooleanField(
                default=True,
                help_text="Grids only: may one game be used in more than one slot?",
            ),
        ),
        migrations.AddField(
            model_name="promptplacement",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_placements",
                to="trophies.concept",
            ),
        ),
        migrations.AddField(
            model_name="promptplacement",
            name="no_duplicates",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="promptplacement",
            name="prompt_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="placements",
                to="prompts.promptgame",
            ),
        ),
        migrations.AddConstraint(
            model_name="promptplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("no_duplicates", True)),
                fields=("response", "prompt_game"),
                name="promptplacement_unique_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="promptplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("no_duplicates", True)),
                fields=("response", "concept"),
                name="promptplacement_unique_concept",
            ),
        ),
        migrations.AddConstraint(
            model_name="promptplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("concept__isnull", True), ("prompt_game__isnull", False)),
                    models.Q(("concept__isnull", False), ("prompt_game__isnull", True)),
                    _connector="OR",
                ),
                name="promptplacement_one_identity",
            ),
        ),
    ]
