# Generated by Django 5.2.7 on 2026-09-16 11:55

from django.db import migrations, models


def _repair_no_duplicates(apps, schema_editor):
    """`0003` backfilled `no_duplicates=True` onto every existing placement while backfilling
    `allow_duplicates=True` onto every existing prompt -- two independent defaults that contradict
    each other.

    The invariant is `no_duplicates == prompt.forbids_duplicates`: False exactly for a grid that
    allows duplicates. Every pre-existing placement on such a grid was therefore born violating it,
    and a wrong flag here is not a loud error -- the uniques are PARTIAL on it, so a row with the
    wrong value is simply invisible to the index it should have been in.

    Harmless on every database that exists today, because this app has never been deployed and the
    table is empty everywhere. That emptiness is doing real work, and it stops doing it the first time
    this lands on a staging box or a restored dump with rows in it. The repair is one statement;
    reasoning about the damage afterwards is not.
    """
    Placement = apps.get_model('prompts', 'PromptPlacement')
    Placement.objects.filter(
        response__prompt__shape='grid', response__prompt__allow_duplicates=True,
    ).update(no_duplicates=False)

    # AND THE PARENT, for the same reason and in the same direction. `0003` stamped
    # `allow_duplicates=True` onto every prompt regardless of shape, and `prompt_duplicates_grid_only`
    # (added below) requires False on every shape that has no such setting. `ADD CONSTRAINT ... CHECK`
    # validates existing rows, so a populated table would refuse the migration outright rather than
    # fail quietly -- which is the better failure, and still one worth not having.
    Prompt = apps.get_model('prompts', 'Prompt')
    Prompt.objects.exclude(shape='grid').update(allow_duplicates=False)


def _noop(apps, schema_editor):
    """Reversing is a no-op: the forward direction repairs a value rather than adding one."""


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0003_remove_promptplacement_promptplacement_unique_game_and_more"),
        ("trophies", "0336_contract_announcement_posted"),
    ]

    operations = [
        # FIRST, so the flags are right before the new partial uniques are built over them.
        migrations.RunPython(_repair_no_duplicates, _noop),
        migrations.RemoveConstraint(
            model_name="promptplacement",
            name="promptplacement_unique_game",
        ),
        migrations.RemoveConstraint(
            model_name="promptplacement",
            name="promptplacement_unique_concept",
        ),
        migrations.RemoveIndex(
            model_name="promptplacement",
            name="prmplace_tally_idx",
        ),
        migrations.AlterField(
            model_name="prompt",
            name="allow_duplicates",
            field=models.BooleanField(
                default=False,
                help_text="Grids only: may one game be used in more than one slot?",
            ),
        ),
        migrations.AlterField(
            model_name="promptplacement",
            name="no_duplicates",
            field=models.BooleanField(),
        ),
        migrations.AddIndex(
            model_name="promptplacement",
            index=models.Index(
                condition=models.Q(("prompt_game__isnull", False)),
                fields=["bucket", "prompt_game"],
                name="prmplace_tally_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptplacement",
            index=models.Index(
                condition=models.Q(("concept__isnull", False)),
                fields=["bucket", "concept"],
                name="prmplace_tally_free_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="prompt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("shape", "grid"), ("allow_duplicates", False), _connector="OR"
                ),
                name="prompt_duplicates_grid_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="promptplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("no_duplicates", True), ("prompt_game__isnull", False)
                ),
                fields=("response", "prompt_game"),
                name="promptplacement_unique_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="promptplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("concept__isnull", False), ("no_duplicates", True)),
                fields=("response", "concept"),
                name="promptplacement_unique_concept",
            ),
        ),
    ]
