# Generated by Django 5.2.7 on 2025-10-29 22:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "np_communication_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("title_id", models.CharField(blank=True, max_length=50, null=True)),
                ("np_service_name", models.CharField(blank=True, max_length=50)),
                ("trophy_set_version", models.CharField(blank=True, max_length=10)),
                ("title_name", models.CharField(max_length=255)),
                ("title_detail", models.TextField(blank=True, null=True)),
                ("title_image", models.URLField(blank=True, null=True)),
                ("title_icon_url", models.URLField(blank=True, null=True)),
                ("title_platform", models.JSONField(blank=True, default=list)),
                ("has_trophy_groups", models.BooleanField(default=False)),
                ("defined_trophies", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["np_communication_id", "title_name"], name="game_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "psn_username",
                    models.CharField(
                        help_text="PSN Online ID (case-sensitive as per PSN)",
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="PSN username must be 3-16 characters, using letters, numbers, hyphens or underscores.",
                                regex="^[a-zA-Z0-9_-]{3,16}$",
                            )
                        ],
                    ),
                ),
                (
                    "account_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("np_id", models.CharField(blank=True, max_length=50, null=True)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("is_plus", models.BooleanField(default=False)),
                ("about_me", models.TextField(blank=True)),
                ("languages_used", models.JSONField(blank=True, default=list)),
                ("trophy_level", models.IntegerField(default=0)),
                ("progress", models.IntegerField(default=0)),
                ("tier", models.IntegerField(default=0)),
                ("earned_trophy_summary", models.JSONField(blank=True, default=dict)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "last_synced",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sync_tier",
                    models.CharField(
                        choices=[("basic", "Basic"), ("preferred", "Preferred")],
                        default="basic",
                        max_length=10,
                    ),
                ),
                ("is_linked", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EarnedTrophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned", models.BooleanField(default=False)),
                ("trophy_hidden", models.BooleanField(default=False)),
                ("progress", models.IntegerField(blank=True, default=0, null=True)),
                ("progress_rate", models.FloatField(blank=True, default=0, null=True)),
                ("progressed_date_time", models.DateTimeField(blank=True, null=True)),
                ("earned_date_time", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_trophy_entries",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APIAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("token_id", models.CharField(max_length=64)),
                ("ip_used", models.CharField(blank=True, max_length=45)),
                ("endpoint", models.CharField(max_length=100)),
                ("status_code", models.IntegerField()),
                ("response_time", models.FloatField()),
                ("error_message", models.TextField(blank=True)),
                ("calls_remaining", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("play_count", models.IntegerField(default=0)),
                ("first_played_date_time", models.DateTimeField(blank=True, null=True)),
                ("last_played_date_time", models.DateTimeField(blank=True, null=True)),
                ("play_duration", models.DurationField(blank=True, null=True)),
                ("progress", models.IntegerField(default=0)),
                ("hidden_flag", models.BooleanField(default=False)),
                ("earned_trophies", models.JSONField(blank=True, default=dict)),
                ("last_updated_datetime", models.DateTimeField(blank=True, null=True)),
                ("last_sync", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_by",
                        to="trophies.game",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_games",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trophy_set_version", models.CharField(blank=True, max_length=10)),
                ("trophy_id", models.IntegerField()),
                ("trophy_type", models.CharField(max_length=20)),
                ("trophy_name", models.CharField(max_length=255)),
                ("trophy_detail", models.TextField(blank=True, null=True)),
                ("trophy_icon_url", models.URLField(blank=True, null=True)),
                ("trophy_group_id", models.CharField(default="default", max_length=10)),
                (
                    "progress_target_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reward_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reward_img_url", models.URLField(blank=True, null=True)),
                (
                    "trophy_rarity",
                    models.IntegerField(
                        blank=True,
                        help_text="Common=3, Rare=2, Very_Rare=1, Ultra_Rare=0",
                        null=True,
                    ),
                ),
                ("trophy_earn_rate", models.FloatField(default=0.0)),
                ("earn_rate", models.FloatField(default=0.0)),
                (
                    "earned_by",
                    models.ManyToManyField(
                        related_name="earned_trophies",
                        through="trophies.EarnedTrophy",
                        to="trophies.profile",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trophies",
                        to="trophies.game",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="earnedtrophy",
            name="trophy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earned_trophy_entries",
                to="trophies.trophy",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["psn_username"], name="psn_username_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["account_id"], name="account_id_idx"),
        ),
        migrations.AddIndex(
            model_name="apiauditlog",
            index=models.Index(
                fields=["timestamp", "status_code"],
                name="trophies_ap_timesta_318d48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profilegame",
            index=models.Index(
                fields=["last_updated_datetime"], name="profilegame_updated_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profilegame",
            unique_together={("profile", "game")},
        ),
        migrations.AddIndex(
            model_name="trophy",
            index=models.Index(
                fields=["trophy_name", "trophy_type"], name="trophy_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trophy",
            unique_together={("trophy_id", "game")},
        ),
        migrations.AddIndex(
            model_name="earnedtrophy",
            index=models.Index(
                fields=["last_updated"], name="earned_trophy_updated_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="earnedtrophy",
            unique_together={("profile", "trophy")},
        ),
    ]
