# Generated by Django 5.2.7 on 2025-10-17 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EarnedTrophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "psn_username",
                    models.CharField(
                        help_text="PSN Online ID (case-sensitive as per PSN)",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, null=True)),
                (
                    "last_synced",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sync_tier",
                    models.CharField(
                        choices=[("basic", "Basic"), ("preferred", "Preferred")],
                        default="basic",
                        max_length=10,
                    ),
                ),
                ("is_linked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Trophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trophy_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        max_length=20,
                    ),
                ),
                ("earn_rate", models.FloatField(default=0.0)),
                ("icon_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("psn_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=50)),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("total_trophies", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["psn_id", "title"], name="trophies_ga_psn_id_ac3312_idx"
                    )
                ],
            },
        ),
    ]
