# Generated by Django 5.2.7 on 2025-10-17 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trophies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="earnedtrophy",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trophies.profile"
            ),
        ),
        migrations.AddField(
            model_name="trophy",
            name="earned_by",
            field=models.ManyToManyField(
                related_name="earned_trophies",
                through="trophies.EarnedTrophy",
                to="trophies.profile",
            ),
        ),
        migrations.AddField(
            model_name="trophy",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trophies",
                to="trophies.game",
            ),
        ),
        migrations.AddField(
            model_name="earnedtrophy",
            name="trophy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trophies.trophy"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["psn_username"], name="trophies_pr_psn_use_51c142_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trophy",
            index=models.Index(
                fields=["name", "type"], name="trophies_tr_name_2e2564_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trophy",
            unique_together={("trophy_id", "game")},
        ),
        migrations.AddIndex(
            model_name="earnedtrophy",
            index=models.Index(
                fields=["last_updated"], name="trophies_ea_last_up_b77622_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="earnedtrophy",
            unique_together={("profile", "trophy")},
        ),
    ]
