# Generated by Django 5.2.7 on 2025-11-01 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0002_game_created_at_profile_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="Higher = shown first"),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("staff_pick", "Staff Pick"),
                            ("event", "Event"),
                            ("trending", "Trending"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trophies.game"
                    ),
                ),
            ],
            options={
                "ordering": ["-priority"],
            },
        ),
    ]
