# Generated by Django 5.2.7 on 2025-10-17 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="psn_username",
            field=models.CharField(
                help_text="PSN Online ID (case-sensitive as per PSN)",
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="PSN username must be 3-16 characters, using letters, numbers, hyphens or underscores.",
                        regex="^[a-zA-Z0-9_-]{3,16}$",
                    )
                ],
            ),
        ),
    ]
