# Generated by Django 5.2.7 on 2025-10-18 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0003_alter_profile_psn_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("play_count", models.IntegerField(default=0)),
                ("first_played_date_time", models.DateTimeField(blank=True, null=True)),
                ("last_played_date_time", models.DateTimeField(blank=True, null=True)),
                ("play_duration", models.DurationField(blank=True, null=True)),
                ("progress", models.IntegerField(default=0)),
                ("hidden_flag", models.BooleanField(default=False)),
                ("earned_trophies", models.JSONField(blank=True, default=dict)),
                ("last_updated_datetime", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="trophies_ga_psn_id_ac3312_idx",
        ),
        migrations.RemoveIndex(
            model_name="trophy",
            name="trophies_tr_name_2e2564_idx",
        ),
        migrations.RenameField(
            model_name="earnedtrophy",
            old_name="earned_date",
            new_name="earned_date_time",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="icon_url",
            new_name="title_icon_url",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="title",
            new_name="title_name",
        ),
        migrations.RenameField(
            model_name="trophy",
            old_name="description",
            new_name="trophy_detail",
        ),
        migrations.RenameField(
            model_name="trophy",
            old_name="icon_url",
            new_name="trophy_icon_url",
        ),
        migrations.RenameField(
            model_name="trophy",
            old_name="name",
            new_name="trophy_name",
        ),
        migrations.RenameField(
            model_name="trophy",
            old_name="type",
            new_name="trophy_type",
        ),
        migrations.RenameIndex(
            model_name="earnedtrophy",
            new_name="earned_trophy_updated_idx",
            old_name="trophies_ea_last_up_b77622_idx",
        ),
        migrations.RenameIndex(
            model_name="profile",
            new_name="psn_username_idx",
            old_name="trophies_pr_psn_use_51c142_idx",
        ),
        migrations.RemoveField(
            model_name="game",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="game",
            name="psn_id",
        ),
        migrations.RemoveField(
            model_name="game",
            name="total_trophies",
        ),
        migrations.AddField(
            model_name="earnedtrophy",
            name="earned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="earnedtrophy",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="earnedtrophy",
            name="progress_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="earnedtrophy",
            name="progressed_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="defined_trophies",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="game",
            name="has_trophy_groups",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="np_communication_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="game",
            name="np_service_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="game",
            name="np_title_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="title_detail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="game",
            name="title_platform",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="trophy_set_version",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="about_me",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="account_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="earned_trophy_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_plus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="languages_used",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="np_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="tier",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="trophy_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trophy",
            name="progress_target_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trophy",
            name="reward_img_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trophy",
            name="reward_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trophy",
            name="trophy_earn_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="trophy",
            name="trophy_group_id",
            field=models.CharField(default="default", max_length=10),
        ),
        migrations.AddField(
            model_name="trophy",
            name="trophy_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trophy",
            name="trophy_rarity",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="trophy",
            name="trophy_set_version",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="earnedtrophy",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earned_trophy_entries",
                to="trophies.profile",
            ),
        ),
        migrations.AlterField(
            model_name="earnedtrophy",
            name="trophy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earned_trophy_entries",
                to="trophies.trophy",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["np_communication_id", "title_name"], name="game_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["account_id"], name="account_id_idx"),
        ),
        migrations.AddIndex(
            model_name="trophy",
            index=models.Index(
                fields=["trophy_name", "trophy_type"], name="trophy_idx"
            ),
        ),
        migrations.AddField(
            model_name="usergame",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="played_by",
                to="trophies.game",
            ),
        ),
        migrations.AddField(
            model_name="usergame",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="played_games",
                to="trophies.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="usergame",
            index=models.Index(
                fields=["last_updated_datetime"], name="usergame_updated_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usergame",
            unique_together={("profile", "game")},
        ),
    ]
