# Generated by Django 5.2.7 on 2025-11-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0003_featuredgame"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profilegame",
            index=models.Index(fields=["progress"], name="profilegame_progress_idx"),
        ),
    ]
