# Generated by Django 5.2.7 on 2025-11-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0004_profilegame_profilegame_progress_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trophy",
            name="earn_rate",
        ),
        migrations.AddField(
            model_name="trophy",
            name="earned_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of profiles that have earned this trophy (PP-specific).",
            ),
        ),
        migrations.AddField(
            model_name="trophy",
            name="played_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of profiles that have played the game (PP-specific).",
            ),
        ),
        migrations.AddIndex(
            model_name="trophy",
            index=models.Index(
                fields=["earned_count", "played_count"], name="trophy_counters_idx"
            ),
        ),
    ]
