# Generated by Django 5.2.7 on 2025-10-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trophies",
            "0004_usergame_remove_game_trophies_ga_psn_id_ac3312_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="APIAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("token_id", models.CharField(max_length=64)),
                ("ip_used", models.CharField(blank=True, max_length=45)),
                ("endpoint", models.CharField(max_length=100)),
                ("status_code", models.IntegerField()),
                ("response_time", models.FloatField()),
                ("error_message", models.TextField(blank=True)),
                ("calls_remaining", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["timestamp", "status_code"],
                        name="trophies_ap_timesta_318d48_idx",
                    )
                ],
            },
        ),
    ]
