# Generated by Django 5.2.7 on 2025-11-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0005_remove_trophy_earn_rate_trophy_earned_count_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="trophy",
            name="trophy_counters_idx",
        ),
        migrations.RemoveField(
            model_name="trophy",
            name="played_count",
        ),
        migrations.AddField(
            model_name="game",
            name="played_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of profiles that have played the game (PP-specific).",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["played_count"], name="game_played_count_idx"),
        ),
        migrations.AddIndex(
            model_name="trophy",
            index=models.Index(fields=["earned_count"], name="trophy_earned_count_idx"),
        ),
    ]
