# Generated by Django 5.2.7 on 2025-10-22 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0005_apiauditlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="np_title_id",
            new_name="title_id",
        ),
        migrations.RemoveField(
            model_name="trophy",
            name="trophy_hidden",
        ),
        migrations.AddField(
            model_name="earnedtrophy",
            name="trophy_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="title_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProfileGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("play_count", models.IntegerField(default=0)),
                ("first_played_date_time", models.DateTimeField(blank=True, null=True)),
                ("last_played_date_time", models.DateTimeField(blank=True, null=True)),
                ("play_duration", models.DurationField(blank=True, null=True)),
                ("progress", models.IntegerField(default=0)),
                ("hidden_flag", models.BooleanField(default=False)),
                ("earned_trophies", models.JSONField(blank=True, default=dict)),
                ("last_updated_datetime", models.DateTimeField(blank=True, null=True)),
                ("last_sync", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_by",
                        to="trophies.game",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_games",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserGame",
        ),
        migrations.AddIndex(
            model_name="profilegame",
            index=models.Index(
                fields=["last_updated_datetime"], name="profilegame_updated_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profilegame",
            unique_together={("profile", "game")},
        ),
    ]
