# Generated by Django 5.2.7 on 2025-10-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0006_rename_np_title_id_game_title_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="title_detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
