# Generated by Django 5.2.7 on 2025-11-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0006_remove_trophy_trophy_counters_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trophy",
            name="earn_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name="trophy",
            index=models.Index(fields=["trophy_earn_rate"], name="trophy_psn_rate_idx"),
        ),
        migrations.AddIndex(
            model_name="trophy",
            index=models.Index(fields=["earn_rate"], name="trophy_pp_rate_idx"),
        ),
    ]
