# Generated by Django 5.2.7 on 2025-10-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0007_alter_game_title_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trophy",
            name="trophy_id",
            field=models.IntegerField(),
        ),
    ]
