# Generated by Django 5.2.7 on 2025-11-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0007_trophy_earn_rate_trophy_trophy_psn_rate_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher = preferred for display"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Feature from this date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Feature until this date", null=True
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin_pick", "Admin Pick"),
                            ("top_week", "Top of Week"),
                            ("event", "Event"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority"],
            },
        ),
    ]
