# Generated by Django 5.2.7 on 2025-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0008_alter_trophy_trophy_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trophy",
            name="trophy_rarity",
            field=models.IntegerField(
                blank=True, help_text="Common=3, Rare=2, Very_Rare=1, Ultra_Rare=0"
            ),
        ),
        migrations.AlterField(
            model_name="trophy",
            name="trophy_type",
            field=models.CharField(max_length=20),
        ),
    ]
