# Generated by Django 5.2.7 on 2025-11-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0008_featuredprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField(help_text="Start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date if multi-day", null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("accent", "Accent"),
                        ],
                        default="primary",
                        help_text="For badge/styling",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "time",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'All Day' or '12pm - 4pm EDT'",
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(help_text="For event page URL", unique=True)),
            ],
            options={
                "ordering": ["date"],
                "indexes": [models.Index(fields=["date"], name="event_date_idx")],
            },
        ),
    ]
