# Generated by Django 5.2.7 on 2025-10-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0009_alter_trophy_trophy_rarity_alter_trophy_trophy_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earnedtrophy",
            name="progress",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="earnedtrophy",
            name="progress_rate",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="trophy",
            name="trophy_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trophy",
            name="trophy_rarity",
            field=models.IntegerField(
                blank=True,
                help_text="Common=3, Rare=2, Very_Rare=1, Ultra_Rare=0",
                null=True,
            ),
        ),
    ]
