# Generated by Django 5.2.7 on 2025-11-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0009_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, help_text="For event page URL"),
        ),
    ]
