# Generated by Django 5.2.7 on 2025-11-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0010_alter_event_slug"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["title_name"], name="game_title_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["title_platform"], name="game_platform_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["created_at"], name="game_created_idx"),
        ),
    ]
