# Generated by Django 5.2.7 on 2025-11-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0011_game_game_title_idx_game_game_platform_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="title_id",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
