# Generated by Django 5.2.7 on 2025-11-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0012_alter_game_title_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="concept_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="game",
            name="region",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
