# Generated by Django 5.2.7 on 2025-11-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0013_game_concept_id_game_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="region",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
