# Generated by Django 5.2.7 on 2025-11-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0014_alter_game_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="concept_id",
        ),
        migrations.RemoveField(
            model_name="game",
            name="region",
        ),
        migrations.RemoveField(
            model_name="game",
            name="title_id",
        ),
    ]
