# Generated by Django 5.2.7 on 2025-11-05 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0015_remove_game_concept_id_remove_game_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concept_id", models.CharField(max_length=50, unique=True)),
                ("unified_title", models.CharField(blank=True, max_length=255)),
                ("publisher_name", models.CharField(blank=True, max_length=255)),
                ("genres", models.JSONField(blank=True, default=list)),
                ("subgenres", models.JSONField(blank=True, default=list)),
                ("descriptions", models.JSONField(blank=True, default=dict)),
                ("content_rating", models.JSONField(blank=True, default=dict)),
                ("media", models.JSONField(blank=True, default=dict)),
                ("regions", models.JSONField(blank=True, default=list)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["concept_id"], name="concept_id_idx"),
                    models.Index(fields=["unified_title"], name="concept_title_idx"),
                    models.Index(
                        fields=["publisher_name"], name="content_publisher_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="concept",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_obj",
                to="trophies.concept",
            ),
        ),
        migrations.CreateModel(
            name="TitleID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_id", models.CharField(max_length=50, unique=True)),
                ("platform", models.CharField(max_length=10)),
                ("region", models.CharField(blank=True, max_length=10)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "concept",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="title_ids",
                        to="trophies.concept",
                    ),
                ),
                (
                    "game",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title_id_obj",
                        to="trophies.game",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["title_id"], name="title_id_idx"),
                    models.Index(fields=["region"], name="title_region_idx"),
                    models.Index(fields=["release_date"], name="title_release_idx"),
                ],
            },
        ),
    ]
