# Generated by Django 5.2.7 on 2025-11-06 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0016_concept_game_concept_titleid"),
    ]

    operations = [
        migrations.AddField(
            model_name="titleid",
            name="sync_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="titleid",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="title_ids",
                to="trophies.concept",
            ),
        ),
        migrations.AlterField(
            model_name="titleid",
            name="game",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_id_obj",
                to="trophies.game",
            ),
        ),
    ]
