# Generated by Django 5.2.7 on 2025-11-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0017_titleid_sync_id_alter_titleid_concept_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="concept",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_obj",
                to="trophies.concept",
            ),
        ),
    ]
