# Generated by Django 5.2.7 on 2025-11-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0018_alter_game_concept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titleid",
            name="sync_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
