# Generated by Django 5.2.7 on 2025-11-06 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0019_alter_titleid_sync_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titleid",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="title_ids",
                to="trophies.game",
            ),
        ),
    ]
