# Generated by Django 5.2.7 on 2025-11-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0020_alter_titleid_game"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="titleid",
            name="title_release_idx",
        ),
        migrations.RemoveField(
            model_name="titleid",
            name="release_date",
        ),
    ]
