# Generated by Django 5.2.7 on 2025-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0021_remove_titleid_title_release_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="titleid",
            name="release_date",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
