# Generated by Django 5.2.7 on 2025-11-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0022_titleid_release_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="titleid",
            name="release_date",
        ),
    ]
