# Generated by Django 5.2.7 on 2025-11-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0023_remove_titleid_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="titleid",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
