# Generated by Django 5.2.7 on 2025-11-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0025_alter_game_concept"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="titleid",
            name="game",
        ),
        migrations.AddField(
            model_name="titleid",
            name="game",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="title_ids", to="trophies.game"
            ),
        ),
    ]
