# Generated by Django 5.2.7 on 2025-11-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0026_remove_titleid_game_titleid_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titleid",
            name="game",
            field=models.ManyToManyField(
                blank=True, related_name="title_ids", to="trophies.game"
            ),
        ),
    ]
