# Generated by Django 5.2.7 on 2025-11-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0027_alter_titleid_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concept",
            name="regions",
        ),
        migrations.AddField(
            model_name="game",
            name="region",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
