# Generated by Django 5.2.7 on 2025-11-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0028_remove_concept_regions_game_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_regional",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="region",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
