# Generated by Django 5.2.7 on 2025-11-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0029_game_is_regional_alter_game_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="titleid",
            name="concept",
        ),
        migrations.RemoveField(
            model_name="titleid",
            name="game",
        ),
        migrations.RemoveField(
            model_name="titleid",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="titleid",
            name="sync_id",
        ),
        migrations.AddField(
            model_name="concept",
            name="title_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="game",
            name="title_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
