# Generated by Django 5.2.7 on 2025-11-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0030_remove_titleid_concept_remove_titleid_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_shovelware",
            field=models.BooleanField(default=False),
        ),
    ]
