# Generated by Django 5.2.7 on 2025-11-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0031_game_is_shovelware"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="flag",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
