# Generated by Django 5.2.7 on 2025-11-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0032_profile_country_profile_country_code_profile_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrophyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trophy_group_id", models.CharField(max_length=10)),
                ("trophy_group_name", models.CharField(blank=True, max_length=255)),
                ("trophy_group_detail", models.TextField(blank=True, null=True)),
                ("trophy_group_icon_url", models.URLField(blank=True, null=True)),
                ("defined_trophies", models.JSONField(blank=True, default=dict)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trophy_groups",
                        to="trophies.game",
                    ),
                ),
            ],
            options={
                "ordering": ["trophy_group_id"],
                "indexes": [
                    models.Index(fields=["trophy_group_id"], name="trophy_group_id_idx")
                ],
                "unique_together": {("game", "trophy_group_id")},
            },
        ),
    ]
