# Generated by Django 5.2.7 on 2025-11-24 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0033_trophygroup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="discord_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Unique Discord user ID. Set on bot linking.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="discord_linked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when Discord was linked via bot.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["discord_id"], name="discord_id_idx"),
        ),
    ]
