# Generated by Django 5.2.7 on 2025-11-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0034_profile_discord_id_profile_discord_linked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_psn_username",
            field=models.CharField(
                blank=True,
                help_text="PSN username with original capitalization (populated from PSN API)",
                max_length=16,
                null=True,
            ),
        ),
    ]
