# Generated by Django 5.2.7 on 2025-11-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0035_profile_display_psn_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="True if PSN ownership verified via code."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_code",
            field=models.CharField(
                blank=True,
                help_text="Temporary code for PSN About Me verification.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiration timestamp for verification code.",
                null=True,
            ),
        ),
    ]
