# Generated by Django 5.2.7 on 2025-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0036_profile_is_verified_profile_verification_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="psn_history_public",
            field=models.BooleanField(
                default=True,
                help_text="Flag indicating if PSN gaming history is public. (Access error: 2240526)",
            ),
        ),
    ]
