# Generated by Django 5.2.7 on 2025-11-27 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0037_profile_psn_history_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_verified", "last_synced"], name="verified_synced_idx"
            ),
        ),
    ]
