# Generated by Django 5.2.7 on 2025-12-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0039_profile_user_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_timezone",
        ),
    ]
