# Generated by Django 5.2.7 on 2025-12-02 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0040_remove_profile_user_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTrophySelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for header display (1-10)."
                    ),
                ),
                (
                    "earned_trophy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="trophies.earnedtrophy",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trophy_selections",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
                "unique_together": {("profile", "earned_trophy")},
            },
        ),
    ]
