# Generated by Django 5.2.7 on 2025-12-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0041_usertrophyselection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertrophyselection",
            options={},
        ),
        migrations.RemoveField(
            model_name="usertrophyselection",
            name="display_order",
        ),
    ]
