# Generated by Django 5.2.7 on 2025-12-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0042_alter_usertrophyselection_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="guide_slug",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
