# Generated by Django 5.2.7 on 2025-12-08 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0043_concept_guide_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConceptRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        help_text="Platinum Difficulty rating (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "hours_to_platinum",
                    models.PositiveIntegerField(
                        help_text="Estimated hours to achieve platinum."
                    ),
                ),
                (
                    "fun_ranking",
                    models.IntegerField(
                        help_text="Fun ranking for the platinum (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        help_text="Overall game rating (1-5 stars)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ratings",
                        to="trophies.concept",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_ratings",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["concept"], name="user_rating_concept_idx"),
                    models.Index(
                        fields=["profile", "concept"], name="user_rating_unique_idx"
                    ),
                ],
                "unique_together": {("profile", "concept")},
            },
        ),
    ]
