# Generated by Django 5.2.7 on 2025-12-08 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0044_userconceptrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconceptrating",
            name="overall_rating",
            field=models.FloatField(
                help_text="Overall game rating (1-5 stars)",
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
