# Generated by Django 5.2.7 on 2025-12-09 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0045_alter_userconceptrating_overall_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "series_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Groups tiers of the same series",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon_url",
                    models.ImageField(blank=True, null=True, upload_to="badges/"),
                ),
                ("display_title", models.CharField(blank=True, max_length=100)),
                (
                    "tier",
                    models.IntegerField(
                        choices=[
                            (1, "Tier 1 (Platinum, Modern)"),
                            (2, "Tier 2 (100%, Modern)"),
                            (3, "Tier 3 (Platinum, All Platforms)"),
                            (4, "Tier 4 (100%, All Platforms)"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("series", "Series (Concept-based)"),
                            ("misc", "Miscellaneous"),
                        ],
                        default="series",
                        max_length=10,
                    ),
                ),
                (
                    "requires_all",
                    models.BooleanField(
                        default=True,
                        help_text="If True, user must complete all qualifying Concepts. If false, only the min_required.",
                    ),
                ),
                (
                    "min_required",
                    models.PositiveIntegerField(
                        default=0, help_text="For large series (e.g. 10 out of 30)"
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        blank=True, default=dict, help_text="For misc badges"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["tier", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_displayed",
                    models.BooleanField(
                        default=False, help_text="User's selected display badge."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBadgeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_concepts", models.PositiveIntegerField(default=0)),
                ("progress_value", models.PositiveIntegerField(default=0)),
                ("last_checked", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="is_obtainable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["is_obtainable", "title_platform"],
                name="game_obtainable_platform_idx",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="concepts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Required Concepts for series badges",
                related_name="badges",
                to="trophies.concept",
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earned_by",
                to="trophies.badge",
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges",
                to="trophies.profile",
            ),
        ),
        migrations.AddField(
            model_name="userbadgeprogress",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_for",
                to="trophies.badge",
            ),
        ),
        migrations.AddField(
            model_name="userbadgeprogress",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge_progress",
                to="trophies.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(
                fields=["series_slug", "tier"], name="badge_series_tier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(fields=["badge_type"], name="badge_type_idx"),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(
                fields=["profile", "is_displayed"], name="userbadge_display_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("profile", "badge")},
        ),
        migrations.AddIndex(
            model_name="userbadgeprogress",
            index=models.Index(
                fields=["profile", "badge"], name="userbadgeprogress_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbadgeprogress",
            unique_together={("profile", "badge")},
        ),
    ]
