# Generated by Django 5.2.7 on 2025-12-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trophies",
            "0046_badge_userbadge_userbadgeprogress_game_is_obtainable_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="badge",
            old_name="icon_url",
            new_name="icon",
        ),
        migrations.AddField(
            model_name="badge",
            name="base_badge",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to Tier 1 Badge for deriving variant icons (Tiers 2-4)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_badges",
                to="trophies.badge",
            ),
        ),
    ]
