# Generated by Django 5.2.7 on 2025-12-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0047_rename_icon_url_badge_icon_badge_base_badge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="base_badge",
        ),
    ]
