# Generated by Django 5.2.7 on 2025-12-09 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0048_remove_badge_base_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="base_badge",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference a base (Tier 1) badge to inherit its icon",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_badges",
                to="trophies.badge",
            ),
        ),
    ]
