# Generated by Django 5.2.7 on 2025-12-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0049_badge_base_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbadgeprogress",
            name="required_concepts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userbadgeprogress",
            name="required_value",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="psn_history_public",
            field=models.BooleanField(
                default=True,
                help_text="Flag indicating if PSN gaming history is public.",
            ),
        ),
    ]
