# Generated by Django 5.2.7 on 2025-12-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0050_userbadgeprogress_required_concepts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="discord_role_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Discord role ID to auto assign upon earning the badge (optional).",
                null=True,
            ),
        ),
    ]
