# Generated by Django 5.2.7 on 2025-12-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0051_badge_discord_role_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="display_series",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
