# Generated by Django 5.2.7 on 2025-12-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0052_badge_display_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="earned_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of users who have earned this badge tier"
            ),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(fields=["earned_count"], name="badge_earned_count_idx"),
        ),
    ]
