# Generated by Django 5.2.7 on 2025-12-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0053_badge_earned_count_badge_badge_earned_count_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="concept",
            index=models.Index(
                fields=["release_date"], name="concept_release_date_idx"
            ),
        ),
    ]
