# Generated by Django 5.2.7 on 2025-12-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0054_concept_release_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="trophies.concept",
            ),
        ),
    ]
