# Generated by Django 5.2.7 on 2025-12-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0055_alter_game_concept"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Start of feature period", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End of featured period", null=True
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1, help_text="Higher = preferred if multiple overlap"
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_entries",
                        to="trophies.concept",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"], name="featured_date_idx"
                    )
                ],
            },
        ),
    ]
