# Generated by Django 5.2.7 on 2025-12-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0056_featuredguide"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="concept_icon_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
