# Generated by Django 5.2.7 on 2025-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0057_concept_concept_icon_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="bg_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
