# Generated by Django 5.2.7 on 2025-12-13 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0058_concept_bg_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="sync_progress_target",
            field=models.IntegerField(
                default=0, help_text="Current sync progress target"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_progress_value",
            field=models.IntegerField(
                default=0, help_text="Current sync progress value"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("synced", "Synced"),
                    ("syncing", "Syncing"),
                    ("error", "Error"),
                ],
                default="idle",
                help_text="Current sync state of the profile",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["sync_status"], name="progile_sync_status_idx"),
        ),
    ]
