# Generated by Django 5.2.7 on 2025-12-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0059_profile_sync_progress_target_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("synced", "Synced"),
                    ("syncing", "Syncing"),
                    ("error", "Error"),
                ],
                default="synced",
                help_text="Current sync state of the profile",
                max_length=20,
            ),
        ),
    ]
