# Generated by Django 5.2.7 on 2025-12-17 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0060_alter_profile_sync_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profile",
            name="verified_synced_idx",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_discord_verified",
            field=models.BooleanField(
                default=False, help_text="True if Discord ownership verified via code."
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_discord_verified", "last_synced"],
                name="verified_synced_idx",
            ),
        ),
    ]
