# Generated by Django 5.2.7 on 2025-12-19 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0061_remove_profile_verified_synced_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_profile_health_check",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
