# Generated by Django 5.2.7 on 2025-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0062_profile_last_profile_health_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avg_progress",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_completes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_games",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_plats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_trophies",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
