# Generated by Django 5.2.7 on 2025-12-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0063_profile_avg_progress_profile_total_completes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="total_unearned",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
