# Generated by Django 5.2.7 on 2025-12-20 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0064_profile_total_unearned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="profile",
            new_name="profile_sync_status_idx",
            old_name="progile_sync_status_idx",
        ),
        migrations.AddField(
            model_name="profilegame",
            name="earned_trophies_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of earned trophies."
            ),
        ),
        migrations.AddField(
            model_name="profilegame",
            name="has_plat",
            field=models.BooleanField(
                default=False, help_text="Whether the plat has been earned."
            ),
        ),
        migrations.AddField(
            model_name="profilegame",
            name="most_recent_trophy_date",
            field=models.DateTimeField(
                blank=True, help_text="Date of most recent trophy earned.", null=True
            ),
        ),
        migrations.AddField(
            model_name="profilegame",
            name="unearned_trophies_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of unearned trophies."
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["total_trophies"], name="profile_total_trophies_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["total_unearned"], name="profile_total_unearned_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["total_plats"], name="profile_total_plats_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["total_games"], name="profile_total_games_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["total_completes"], name="profile_total_completes_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["avg_progress"], name="profile_avg_progress_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilegame",
            index=models.Index(
                fields=["most_recent_trophy_date"], name="pg_recent_trophy_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilegame",
            index=models.Index(
                fields=["earned_trophies_count"], name="pg_earned_count_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilegame",
            index=models.Index(
                fields=["unearned_trophies_count"], name="pg_unearned_count_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilegame",
            index=models.Index(fields=["has_plat"], name="pg_has_plat_idx"),
        ),
    ]
