# Generated by Django 5.2.7 on 2025-12-21 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trophies",
            "0065_rename_progile_sync_status_idx_profile_sync_status_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["last_synced"], name="profile_last_synced_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["created_at"], name="profile_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["country_code"], name="profile_country_code_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_linked", "sync_tier"], name="profile_linked_tier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_discord_verified", "discord_linked_at"],
                name="profile_discord_idx",
            ),
        ),
    ]
