# Generated by Django 5.2.7 on 2025-12-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0066_profile_profile_last_synced_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["is_shovelware"], name="game_shovelware_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["is_regional"], name="game_regional_idx"),
        ),
    ]
