# Generated by Django 5.2.7 on 2025-12-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0067_game_game_shovelware_idx_game_game_regional_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="earnedtrophy",
            index=models.Index(
                fields=["earned_date_time"], name="earned_trophy_earned_time_idx"
            ),
        ),
    ]
