# Generated by Django 5.2.7 on 2025-12-22 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0068_earnedtrophy_earned_trophy_earned_time_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rarest_plat",
            field=models.ForeignKey(
                blank=True,
                help_text="Rarest earned platinum by earn_rate.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rarest_for_profiles",
                to="trophies.earnedtrophy",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recent_plat",
            field=models.ForeignKey(
                blank=True,
                help_text="Most recent earned platinum.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recent_for_profiles",
                to="trophies.earnedtrophy",
            ),
        ),
    ]
