# Generated by Django 5.2.7 on 2025-12-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0069_profile_rarest_plat_profile_recent_plat"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="lock_title",
            field=models.BooleanField(
                default=False,
                help_text="Admin title override - won't be automatically updated.",
            ),
        ),
    ]
