# Generated by Django 5.2.7 on 2025-12-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0070_game_lock_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="icon",
        ),
        migrations.AddField(
            model_name="badge",
            name="badge_image",
            field=models.ImageField(
                blank=True,
                help_text="Main badge layer - defaults to static if blank.",
                null=True,
                upload_to="badges/main/",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="tier",
            field=models.IntegerField(
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("plat", "Platinum"),
                ],
                default="bronze",
            ),
        ),
    ]
