# Generated by Django 5.2.7 on 2025-12-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0071_remove_badge_icon_badge_badge_image_alter_badge_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="tier",
            field=models.CharField(
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("plat", "Platinum"),
                ],
                default="bronze",
                max_length=10,
            ),
        ),
    ]
