# Generated by Django 5.2.7 on 2025-12-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0072_alter_badge_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="tier",
            field=models.IntegerField(
                choices=[(1, "Bronze"), (2, "Silver"), (3, "Gold"), (4, "Platinum")],
                default=1,
            ),
        ),
    ]
