# Generated by Django 5.2.7 on 2025-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0073_alter_badge_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="user_title",
            field=models.CharField(
                blank=True,
                help_text="Title earned by user upon badge completion.",
                max_length=100,
            ),
        ),
    ]
