# Generated by Django 5.2.7 on 2025-12-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0074_badge_user_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="most_recent_concept",
            field=models.ForeignKey(
                blank=True,
                help_text="Concept with the latest release_date",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="most_recent_for_badges",
                to="trophies.concept",
            ),
        ),
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(
                fields=["most_recent_concept"], name="badge_recent_concept_idx"
            ),
        ),
    ]
