# Generated by Django 5.2.7 on 2025-12-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0075_badge_most_recent_concept_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="region_lock",
            field=models.BooleanField(
                default=False,
                help_text="Admin region override lock - won't be automatically updated.",
            ),
        ),
    ]
