# Generated by Django 5.2.7 on 2025-12-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0076_game_region_lock"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="force_title_icon",
            field=models.BooleanField(
                blank=True,
                help_text="Force displays to use the title icon instead of title image.",
                null=True,
            ),
        ),
    ]
