# Generated by Django 5.2.7 on 2025-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0077_game_force_title_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="force_title_icon",
            field=models.BooleanField(
                default=False,
                help_text="Force displays to use the title icon instead of title image.",
            ),
        ),
    ]
