# Generated by Django 5.2.7 on 2025-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0078_alter_game_force_title_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_profile_health_check",
            field=models.DateTimeField(null=True),
        ),
    ]
