# Generated by Django 5.2.7 on 2025-12-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0079_alter_profile_last_profile_health_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_delisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["is_delisted"], name="game_delisted_idx"),
        ),
    ]
