# Generated by Django 5.2.7 on 2025-12-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0080_game_is_delisted_game_game_delisted_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbadgeprogress",
            name="required_concepts",
        ),
        migrations.RemoveField(
            model_name="userbadgeprogress",
            name="required_value",
        ),
        migrations.AddField(
            model_name="badge",
            name="required_concepts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of required concepts for series badges",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="required_value",
            field=models.PositiveIntegerField(
                default=0, help_text="Denormalized required value for misc badges"
            ),
        ),
    ]
