# Generated by Django 5.2.7 on 2026-01-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0081_remove_userbadgeprogress_required_concepts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
