# Generated by Django 5.2.7 on 2026-01-01 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0082_profile_user_is_premium"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="selected_background",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected background concept for premium profiles.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_by_profiles",
                to="trophies.concept",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["user_is_premium", "selected_background"],
                name="trophies_pr_user_is_0fb999_idx",
            ),
        ),
    ]
