# Generated by Django 5.2.7 on 2026-01-02 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0083_profile_selected_background_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="selected_title_badge",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected badge for premium title display.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_title_for_profiles",
                to="trophies.badge",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["user_is_premium", "selected_title_badge"],
                name="trophies_pr_user_is_e6b676_idx",
            ),
        ),
    ]
