# Generated by Django 5.2.7 on 2026-01-02 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0084_profile_selected_title_badge_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profile",
            name="trophies_pr_user_is_e6b676_idx",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="selected_title_badge",
        ),
        migrations.AddField(
            model_name="profile",
            name="selected_title",
            field=models.CharField(
                blank=True,
                help_text="Selected user title text from earned badges.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["user_is_premium", "selected_title"],
                name="trophies_pr_user_is_e31e10_idx",
            ),
        ),
    ]
