# Generated by Django 5.2.7 on 2026-01-03 02:50

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0085_remove_profile_trophies_pr_user_is_e6b676_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series_slug",
                    models.SlugField(
                        help_text="Series slug this stage applies to.", max_length=100
                    ),
                ),
                (
                    "stage_number",
                    models.IntegerField(
                        help_text="Stage number (0 for optional/tangential concepts.)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Optional stage title", max_length=255
                    ),
                ),
                ("stage_icon", models.URLField(blank=True, null=True)),
                (
                    "required_tiers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "Bronze"),
                                (2, "Silver"),
                                (3, "Gold"),
                                (4, "Platinum"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "concepts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Concepts required for this stage.",
                        related_name="stages",
                        to="trophies.concept",
                    ),
                ),
            ],
            options={
                "ordering": ["stage_number"],
                "indexes": [
                    models.Index(
                        fields=["series_slug", "stage_number"],
                        name="stage_slug_number_idx",
                    )
                ],
                "unique_together": {("series_slug", "stage_number")},
            },
        ),
    ]
