# Generated by Django 5.2.7 on 2026-01-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0086_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="required_stages",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of required stages for series badges",
            ),
        ),
    ]
