# Generated by Django 5.2.7 on 2026-01-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0087_badge_required_stages"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="badge",
            index=models.Index(fields=["tier"], name="badge_tier_idx"),
        ),
    ]
