# Generated by Django 5.2.7 on 2026-01-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0088_badge_badge_tier_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublisherBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["name"], name="blacklist_name_idx")],
            },
        ),
    ]
