# Generated by Django 5.2.7 on 2026-01-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0089_publisherblacklist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="concepts",
        ),
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("series", "Series"),
                    ("collection", "Collection"),
                    ("misc", "Miscellaneous"),
                ],
                default="series",
                max_length=10,
            ),
        ),
    ]
