# Generated by Django 5.2.7 on 2026-01-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0090_remove_badge_concepts_alter_badge_badge_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(fields=["earned_at"], name="userbadge_earned_at_idx"),
        ),
    ]
