# Generated by Django 5.2.7 on 2026-01-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0091_userbadge_userbadge_earned_at_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="earnedtrophy",
            name="user_hidden",
            field=models.BooleanField(
                default=False, help_text="True if user has game hidden/deleted."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_hiddens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profilegame",
            name="user_hidden",
            field=models.BooleanField(
                default=False, help_text="True if user has game hidden/deleted."
            ),
        ),
    ]
