# Generated by Django 5.2.7 on 2026-01-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0092_earnedtrophy_user_hidden_profile_total_hiddens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hide_hiddens",
            field=models.BooleanField(
                default=False,
                help_text="If true, hide hidden/deleted games from list and totals.",
            ),
        ),
    ]
