# Generated by Django 5.2.7 on 2026-01-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0093_profile_hide_hiddens"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hide_zeros",
            field=models.BooleanField(
                default=False, help_text="If true, hide games with no trophies earned."
            ),
        ),
    ]
