# Generated by Django 5.2.7 on 2026-01-10 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0094_profile_hide_zeros"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconceptrating",
            name="grindiness",
            field=models.IntegerField(
                default=5,
                help_text="Platinum grindiness rating (1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
            preserve_default=False,
        ),
    ]
