# Generated by Django 5.2.7 on 2026-01-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0095_userconceptrating_grindiness"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The title text.", max_length=100, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Title",
                "verbose_name_plural": "Titles",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="title_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="UserTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("badge", "Badge"), ("milestone", "Milestone")],
                        help_text="Source of the title",
                        max_length=20,
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of the granting object", null=True
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_displayed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the user's selected display title",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_titles",
                        to="trophies.profile",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_titles",
                        to="trophies.title",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Title",
                "verbose_name_plural": "User Titles",
                "indexes": [
                    models.Index(
                        fields=["profile", "is_displayed"], name="usertitle_display_idx"
                    ),
                    models.Index(fields=["earned_at"], name="usertitle_earned_at_idx"),
                    models.Index(
                        fields=["source_type", "source_id"], name="usertitle_source_idx"
                    ),
                ],
                "unique_together": {("profile", "title")},
            },
        ),
    ]
