# Generated by Django 5.2.7 on 2026-01-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0096_title_usertitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="title",
            field=models.ForeignKey(
                blank=True,
                help_text="Title awarded to user upon earning.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="badge_title",
                to="trophies.title",
            ),
        ),
    ]
