# Generated by Django 5.2.7 on 2026-01-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0097_badge_title"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profile",
            name="trophies_pr_user_is_e31e10_idx",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="selected_title",
        ),
    ]
