# Generated by Django 5.2.7 on 2026-01-12 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0098_remove_profile_trophies_pr_user_is_e31e10_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description for display"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Visual icon",
                        null=True,
                        upload_to="milestones/",
                    ),
                ),
                (
                    "discord_role_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discord role ID to assign upon earning",
                        null=True,
                    ),
                ),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Award"),
                            ("plat_count", "Earned Plats"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "criteria_details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Flexible details"
                    ),
                ),
                (
                    "manual_award",
                    models.BooleanField(
                        default=False, help_text="If True, admins award manually."
                    ),
                ),
                (
                    "premium_only",
                    models.BooleanField(
                        default=False,
                        help_text="If True, can only be earned by current premium users",
                    ),
                ),
                (
                    "requires_all",
                    models.BooleanField(
                        default=True,
                        help_text="For multi-part criteria. False allowed min_required",
                    ),
                ),
                (
                    "min_required",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum items needed if not requires_all"
                    ),
                ),
                (
                    "required_value",
                    models.PositiveIntegerField(
                        default=0, help_text="Target for milestone"
                    ),
                ),
                (
                    "earned_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Counter for user earns"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestones",
                        to="trophies.title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone",
                "verbose_name_plural": "Milestones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_milestones",
                        to="trophies.milestone",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_milestones",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Milestone",
                "verbose_name_plural": "User Milestones",
            },
        ),
        migrations.CreateModel(
            name="UserMilestoneProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress_value",
                    models.PositiveIntegerField(
                        default=0, help_text="Current progress"
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last progress update"
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_progress",
                        to="trophies.milestone",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_milestone_progress",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Milestone Progress",
                "verbose_name_plural": "User Milestone Progress",
            },
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["criteria_type"], name="milestone_type_idx"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["earned_count"], name="milestone_earned_count_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermilestone",
            index=models.Index(
                fields=["earned_at"], name="usermilestone_earned_at_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermilestone",
            unique_together={("profile", "milestone")},
        ),
        migrations.AddIndex(
            model_name="usermilestoneprogress",
            index=models.Index(
                fields=["profile", "milestone"], name="usermilestoneprogress_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermilestoneprogress",
            index=models.Index(
                fields=["last_checked"], name="usermilestoneprog_checked_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermilestoneprogress",
            unique_together={("profile", "milestone")},
        ),
    ]
