# Generated by Django 5.2.7 on 2026-01-12 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0099_milestone_usermilestone_usermilestoneprogress_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="total_bronzes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_golds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_silvers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["total_bronzes"], name="profile_total_bronzes_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["total_silvers"], name="profile_total_silver_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["total_golds"], name="profile_total_gold_idx"),
        ),
    ]
