# Generated by Django 5.2.7 on 2026-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0100_profile_total_bronzes_profile_total_golds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="has_online_trophies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["has_online_trophies"], name="game_online_trophies_idx"
            ),
        ),
    ]
