# Generated by Django 5.2.7 on 2026-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0101_game_has_online_trophies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="has_online_trophies",
            field=models.BooleanField(default=False),
        ),
    ]
