# Generated by Django 5.2.7 on 2026-01-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0102_stage_has_online_trophies"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("type", "Guide Type"), ("language", "Language")],
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Guide Tag",
                "verbose_name_plural": "Guide Tags",
                "ordering": ["category", "display_order", "name"],
                "indexes": [
                    models.Index(fields=["category"], name="guidetag_category_idx"),
                    models.Index(fields=["slug"], name="guidetag_slug_idx"),
                ],
            },
        ),
    ]
