# Generated by Django 5.2.7 on 2026-01-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0103_game_comment_count_trophy_comment_count_comment_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="comment_content_votes_idx",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="comment_threaded_idx",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="game",
            name="comment_count",
        ),
        migrations.RemoveField(
            model_name="trophy",
            name="comment_count",
        ),
        migrations.AddField(
            model_name="comment",
            name="concept",
            field=models.ForeignKey(
                blank=True,
                help_text="The game concept this comment belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="trophies.concept",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="trophy_id",
            field=models.IntegerField(
                blank=True,
                help_text="Trophy position within concept (null = concept-level comment)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="concept",
            name="comment_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of all comments on this concept",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["concept", "trophy_id", "-upvote_count"],
                name="comment_concept_votes_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["concept", "trophy_id", "depth", "-upvote_count"],
                name="comment_threaded_idx",
            ),
        ),
    ]
