# Generated by Django 5.2.7 on 2026-01-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0103_guidetag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guidetag",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Guide Tag",
                "verbose_name_plural": "Guide Tags",
            },
        ),
        migrations.RemoveIndex(
            model_name="guidetag",
            name="guidetag_category_idx",
        ),
        migrations.RemoveField(
            model_name="guidetag",
            name="category",
        ),
    ]
