# Generated by Django 5.2.7 on 2026-01-17 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0104_remove_comment_comment_content_votes_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="concept",
            field=models.ForeignKey(
                help_text="The game concept this comment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="trophies.concept",
            ),
        ),
    ]
