# Generated by Django 5.2.7 on 2026-01-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0104_alter_guidetag_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorTrust",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trust_level",
                    models.CharField(
                        choices=[
                            ("new", "New Author"),
                            ("trusted", "Trusted Author"),
                            ("banned", "Banned"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("approved_guide_count", models.PositiveIntegerField(default=0)),
                ("total_stars_received", models.PositiveIntegerField(default=0)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("banned_at", models.DateTimeField(blank=True, null=True)),
                ("ban_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_trust",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author Trust",
                "verbose_name_plural": "Author Trust Records",
            },
        ),
    ]
