# Generated by Django 5.2.7 on 2026-01-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0105_alter_comment_concept"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="image",
        ),
    ]
