# Generated by Django 5.2.7 on 2026-01-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0105_authortrust"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("content", models.TextField()),
                ("draft_content", models.TextField(blank=True)),
                ("has_pending_edits", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                            ("unlisted", "Unlisted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("rating_sum", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_guides",
                        to="trophies.profile",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_guides",
                        to="trophies.concept",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_guides",
                        to="trophies.game",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_guides",
                        to="trophies.profile",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="guides", to="trophies.guidetag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Guide",
                "verbose_name_plural": "Community Guides",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="guide_slug_idx"),
                    models.Index(fields=["status"], name="guide_status_idx"),
                    models.Index(fields=["author"], name="guide_author_idx"),
                    models.Index(fields=["game"], name="guide_game_idx"),
                    models.Index(fields=["concept"], name="guide_concept_idx"),
                    models.Index(fields=["-average_rating"], name="guide_rating_idx"),
                    models.Index(fields=["-published_at"], name="guide_published_idx"),
                ],
            },
        ),
    ]
