# Generated by Django 5.2.7 on 2026-01-19 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0106_remove_comment_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("delete", "Comment Deleted"),
                            ("restore", "Comment Restored"),
                            ("dismiss_report", "Report Dismissed"),
                            ("approve_comment", "Comment Approved"),
                            ("warning_issued", "Warning Issued"),
                            ("bulk_delete", "Bulk Delete"),
                            ("report_reviewed", "Report Reviewed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("comment_id_snapshot", models.IntegerField()),
                (
                    "original_body",
                    models.TextField(
                        help_text="Original comment text preserved for context"
                    ),
                ),
                (
                    "trophy_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Trophy ID if comment was on trophy (null = concept-level)",
                        null=True,
                    ),
                ),
                ("reason", models.TextField(help_text="Moderator's reason for action")),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Private staff notes (not shown to user)"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of comment author at time of action",
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_logs",
                        to="trophies.comment",
                    ),
                ),
                (
                    "comment_author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_comments",
                        to="trophies.profile",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trophies.concept",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to="trophies.commentreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "moderator"],
                        name="trophies_mo_timesta_8dfa95_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="trophies_mo_action__2ee5de_idx",
                    ),
                    models.Index(
                        fields=["comment_author", "-timestamp"],
                        name="trophies_mo_comment_27dc67_idx",
                    ),
                ],
            },
        ),
    ]
