# Generated by Django 5.2.7 on 2026-01-16 14:33

import django.db.models.deletion
import trophies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0106_guide"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=trophies.models.guide_image_upload_path
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="trophies.guide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Image",
                "verbose_name_plural": "Guide Images",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
