# Generated by Django 5.2.7 on 2026-01-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0107_moderationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="guidelines_agreed",
            field=models.BooleanField(
                default=False,
                help_text="True if user has agreed to community guidelines for commenting.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="guidelines_agreed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when user agreed to community guidelines.",
                null=True,
            ),
        ),
    ]
