# Generated by Django 5.2.7 on 2026-01-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0107_guideimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guide",
            name="content",
        ),
        migrations.RemoveField(
            model_name="guide",
            name="draft_content",
        ),
        migrations.RemoveField(
            model_name="guide",
            name="has_pending_edits",
        ),
        migrations.AddField(
            model_name="guide",
            name="summary",
            field=models.CharField(
                default="hello",
                help_text="Brief text-only summary shown in listings and previews (max 500 chars)",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="GuideSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220)),
                (
                    "content",
                    models.TextField(
                        help_text="Markdown content for this section (max 8000 chars)"
                    ),
                ),
                ("draft_content", models.TextField(blank=True)),
                ("has_pending_edits", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="trophies.guide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Section",
                "verbose_name_plural": "Guide Sections",
                "ordering": ["guide", "section_order"],
                "unique_together": {("guide", "section_order"), ("guide", "slug")},
            },
        ),
    ]
