# Generated by Django 5.2.7 on 2026-01-21 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0108_profile_guidelines_agreed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("series", "Series"),
                    ("collection", "Collection"),
                    ("megamix", "Megamix"),
                    ("misc", "Miscellaneous"),
                ],
                default="series",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="BannedWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        help_text="Word or phrase to ban (case-insensitive)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this filter is currently active",
                    ),
                ),
                (
                    "use_word_boundaries",
                    models.BooleanField(
                        default=True,
                        help_text="Match whole words only (recommended to avoid false positives)",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about why this word was banned",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banned_words_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["word"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "word"],
                        name="trophies_ba_is_acti_b832ee_idx",
                    )
                ],
            },
        ),
    ]
