# Generated by Django 5.2.7 on 2026-01-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0108_remove_guide_content_remove_guide_draft_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="trophies.guide",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_ratings",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Rating",
                "verbose_name_plural": "Guide Ratings",
                "indexes": [
                    models.Index(fields=["guide"], name="guiderating_guide_idx"),
                    models.Index(fields=["profile"], name="guiderating_profile_idx"),
                ],
                "unique_together": {("guide", "profile")},
            },
        ),
    ]
