# Generated by Django 5.2.7 on 2026-01-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0109_alter_badge_badge_type_bannedword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="required_concepts",
        ),
    ]
