# Generated by Django 5.2.7 on 2026-01-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0109_guiderating"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="guide_type",
            field=models.CharField(
                choices=[("freeform", "Freeform"), ("roadmap", "Trophy Roadmap")],
                default="freeform",
                help_text="Type of guide structure",
                max_length=20,
            ),
        ),
    ]
