# Generated by Django 5.2.7 on 2026-01-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0110_remove_badge_required_concepts"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="earnedtrophy",
            index=models.Index(
                fields=["profile", "earned"], name="earnedtrophy_profileearned_idx"
            ),
        ),
    ]
