# Generated by Django 5.2.7 on 2026-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0111_earnedtrophy_earnedtrophy_profileearned_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="criteria_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Award"),
                    ("plat_count", "Earned Plats"),
                    ("psn_linked", "PSN Profile Linked"),
                    ("discord_linked", "Discord Connected"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
