# Generated by Django 5.2.7 on 2026-01-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0112_alter_milestone_criteria_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="user_title",
        ),
        migrations.AlterField(
            model_name="milestone",
            name="criteria_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Award"),
                    ("plat_count", "Earned Plats"),
                    ("psn_linked", "PSN Profile Linked"),
                    ("discord_linked", "Discord Connected"),
                    ("rating_count", "Games Rated"),
                    ("playtime_hours", "Total Playtime (Hours)"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
