# Generated by Django 5.2.7 on 2026-01-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0113_remove_badge_user_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="criteria_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Award"),
                    ("plat_count", "Earned Plats"),
                    ("psn_linked", "PSN Profile Linked"),
                    ("discord_linked", "Discord Connected"),
                    ("rating_count", "Games Rated"),
                    ("playtime_hours", "Total Playtime (Hours)"),
                    ("trophy_count", "Total Trophies Earned"),
                    ("comment_upvotes", "Comment Upvotes Received"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
