# Generated by Django 5.2.7 on 2026-01-23 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0114_alter_milestone_criteria_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Checklist title", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Checklist description/overview",
                        max_length=2000,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("upvote_count", models.PositiveIntegerField(default=0)),
                (
                    "progress_save_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of users who have saved progress on this checklist",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "concept",
                    models.ForeignKey(
                        help_text="The game concept this checklist belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="trophies.concept",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-upvote_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("misinformation", "Misinformation/Inaccurate"),
                            ("plagiarism", "Plagiarism"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Additional context for the report",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                            ("action_taken", "Action Taken"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="trophies.checklist",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_checklist_reports",
                        to="trophies.profile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_checklist_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Section subtitle/header", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional section description",
                        max_length=1000,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within checklist"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="trophies.checklist",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(help_text="Item description/task", max_length=500),
                ),
                (
                    "trophy_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional trophy_id if this item relates to a specific trophy",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within section"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trophies.checklistsection",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="trophies.checklist",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_votes",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserChecklistProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_items",
                    models.JSONField(
                        default=list, help_text="List of completed ChecklistItem IDs"
                    ),
                ),
                ("items_completed", models.PositiveIntegerField(default=0)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="trophies.checklist",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_progress",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(
                fields=["concept", "status", "-upvote_count"],
                name="checklist_concept_votes_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(
                fields=["profile", "-created_at"], name="checklist_profile_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(
                fields=["profile", "status"], name="checklist_author_drafts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklist",
            index=models.Index(
                fields=["is_deleted", "created_at"], name="checklist_moderation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistreport",
            index=models.Index(
                fields=["status", "-created_at"], name="checklist_report_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistreport",
            index=models.Index(
                fields=["checklist"], name="checklist_report_checklist_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checklistreport",
            unique_together={("checklist", "reporter")},
        ),
        migrations.AddIndex(
            model_name="checklistsection",
            index=models.Index(
                fields=["checklist", "order"], name="section_checklist_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(
                fields=["section", "order"], name="item_section_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistvote",
            index=models.Index(
                fields=["checklist", "profile"], name="checklistvote_unique_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checklistvote",
            index=models.Index(fields=["profile"], name="checklistvote_profile_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="checklistvote",
            unique_together={("checklist", "profile")},
        ),
        migrations.AddIndex(
            model_name="userchecklistprogress",
            index=models.Index(
                fields=["profile", "checklist"], name="userprogress_unique_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userchecklistprogress",
            index=models.Index(
                fields=["profile", "-last_activity"], name="userprogress_activity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userchecklistprogress",
            index=models.Index(
                fields=["checklist", "progress_percentage"],
                name="userprogress_completion_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userchecklistprogress",
            unique_together={("profile", "checklist")},
        ),
    ]
