# Generated by Django 5.2.7 on 2026-01-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0115_checklist_checklistreport_checklistsection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="item_type",
            field=models.CharField(
                choices=[("item", "Item"), ("sub_header", "Sub-Header")],
                default="item",
                help_text="Type of checklist entry",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(
                fields=["section", "item_type"], name="item_section_type_idx"
            ),
        ),
    ]
