# Generated by Django 5.2.7 on 2026-01-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0117_alter_milestone_criteria_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Main thumbnail image (recommended: 800x800px, max 5MB)",
                null=True,
                upload_to="checklists/thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image for item_type=image (premium only, max 2MB)",
                null=True,
                upload_to="checklists/items/",
            ),
        ),
        migrations.AddField(
            model_name="checklistsection",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Section thumbnail (recommended: 400x400px, max 2MB)",
                null=True,
                upload_to="checklists/sections/",
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("item", "Item"),
                    ("sub_header", "Sub-Header"),
                    ("image", "Image"),
                ],
                default="item",
                help_text="Type of checklist entry",
                max_length=20,
            ),
        ),
    ]
