# Generated by Django 5.2.7 on 2026-01-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0118_checklist_thumbnail_checklistitem_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("item", "Item"),
                    ("sub_header", "Sub-Header"),
                    ("image", "Image"),
                    ("text_area", "Text Area"),
                ],
                default="item",
                help_text="Type of checklist entry",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="text",
            field=models.CharField(help_text="Item description/task", max_length=2000),
        ),
    ]
