# Generated by Django 5.2.7 on 2026-01-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0119_alter_checklistitem_item_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklist",
            name="selected_game",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected game for trophy items (from this concept's games)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checklists_using_game",
                to="trophies.game",
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("item", "Item"),
                    ("sub_header", "Sub-Header"),
                    ("image", "Image"),
                    ("text_area", "Text Area"),
                    ("trophy", "Trophy"),
                ],
                default="item",
                help_text="Type of checklist entry",
                max_length=20,
            ),
        ),
    ]
