# Generated by Django 5.2.7 on 2026-01-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0120_checklist_selected_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="checklist_id",
            field=models.IntegerField(
                blank=True,
                help_text="Checklist ID within concept (null = concept-level comment)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["concept", "checklist_id", "-upvote_count"],
                name="comment_checklist_votes_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["concept", "checklist_id", "depth", "-upvote_count"],
                name="comment_checklist_threaded_idx",
            ),
        ),
    ]
