# Generated by Django 5.2.7 on 2026-02-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0121_comment_checklist_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="selected_theme",
            field=models.CharField(
                blank=True,
                help_text="Selected gradient theme key for premium site-wide background.",
                max_length=50,
                null=True,
            ),
        ),
    ]
