# Generated by Django 5.2.7 on 2026-02-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0122_profile_selected_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatType",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#FFD700",
                        help_text="Hex color for UI theming",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Stat Type",
                "verbose_name_plural": "Stat Types",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProfileGamification",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="gamification",
                        serialize=False,
                        to="trophies.profile",
                    ),
                ),
                (
                    "total_badge_xp",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "series_badge_xp",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-series XP breakdown: {"resident-evil": 1500, ...}',
                    ),
                ),
                ("total_badges_earned", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile Gamification Stats",
                "verbose_name_plural": "Profile Gamification Stats",
                "indexes": [
                    models.Index(
                        fields=["total_badge_xp"], name="gamification_badge_xp_idx"
                    ),
                    models.Index(
                        fields=["total_badges_earned"], name="gamification_badges_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StageStatValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bronze_value", models.PositiveIntegerField(default=0)),
                ("silver_value", models.PositiveIntegerField(default=0)),
                ("gold_value", models.PositiveIntegerField(default=0)),
                ("platinum_value", models.PositiveIntegerField(default=0)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_values",
                        to="trophies.stage",
                    ),
                ),
                (
                    "stat_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_values",
                        to="trophies.stattype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage Stat Value",
                "verbose_name_plural": "Stage Stat Values",
                "indexes": [
                    models.Index(fields=["stage", "stat_type"], name="stage_stat_idx")
                ],
                "unique_together": {("stage", "stat_type")},
            },
        ),
    ]
