# Generated by Django 5.2.7 on 2026-02-05 23:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0124_populate_gamification_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyRecap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("total_trophies_earned", models.PositiveIntegerField(default=0)),
                ("bronzes_earned", models.PositiveIntegerField(default=0)),
                ("silvers_earned", models.PositiveIntegerField(default=0)),
                ("golds_earned", models.PositiveIntegerField(default=0)),
                ("platinums_earned", models.PositiveIntegerField(default=0)),
                ("games_started", models.PositiveIntegerField(default=0)),
                ("games_completed", models.PositiveIntegerField(default=0)),
                (
                    "platinums_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of platinum dicts: [{game_name, game_image, earned_date, earn_rate}]",
                    ),
                ),
                (
                    "rarest_trophy_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Rarest trophy: {name, game, earn_rate, icon_url, trophy_type}",
                    ),
                ),
                (
                    "most_active_day",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Most active day: {date, day_name, trophy_count}",
                    ),
                ),
                ("badge_xp_earned", models.PositiveIntegerField(default=0)),
                ("badges_earned_count", models.PositiveIntegerField(default=0)),
                (
                    "badges_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of badges earned: [{name, tier, series_slug, image_url}]",
                    ),
                ),
                (
                    "comparison_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Comparison stats: {vs_prev_month_pct, personal_bests: []}",
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="True once the month ends and stats are locked",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_recaps",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Recap",
                "verbose_name_plural": "Monthly Recaps",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["profile", "year", "month"],
                        name="monthlyrecap_profile_ym_idx",
                    ),
                    models.Index(
                        fields=["year", "month", "is_finalized"],
                        name="monthlyrecap_ym_final_idx",
                    ),
                    models.Index(
                        fields=["profile", "is_finalized"],
                        name="monthlyrecap_profile_final_idx",
                    ),
                ],
                "unique_together": {("profile", "year", "month")},
            },
        ),
    ]
