# Generated by Django 5.2.7 on 2026-02-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0125_monthlyrecap"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyrecap",
            name="activity_calendar",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Activity calendar: {days: [{day, count, level}], max_count, total_active_days, first_day_weekday, days_in_month}",
            ),
        ),
    ]
