# Generated by Django 5.2.7 on 2026-02-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0128_add_remaining_denormalized_recap_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyrecap",
            name="email_sent",
            field=models.BooleanField(
                default=False,
                help_text="True if recap notification email has been sent to user",
            ),
        ),
        migrations.AddField(
            model_name="monthlyrecap",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when recap email was sent", null=True
            ),
        ),
    ]
