# Generated by Django 5.2.7 on 2026-02-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0129_monthlyrecap_email_sent_monthlyrecap_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyrecap",
            name="notification_sent",
            field=models.BooleanField(
                default=False,
                help_text="True if recap in-app notification has been sent to user",
            ),
        ),
        migrations.AddField(
            model_name="monthlyrecap",
            name="notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when recap notification was sent",
                null=True,
            ),
        ),
    ]
