# Generated by Django 5.2.7 on 2026-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0130_monthlyrecap_notification_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized total page view count (only tracked on tier=1 badge rows).",
            ),
        ),
        migrations.AddField(
            model_name="checklist",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Denormalized total page view count."
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Denormalized total page view count."
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Denormalized total page view count."
            ),
        ),
    ]
