# Generated by Django 5.2.7 on 2026-02-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0131_badge_view_count_checklist_view_count_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.AddField(
            model_name="concept",
            name="guide_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
