# Generated by Django 5.2.7 on 2026-02-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0132_delete_event_concept_guide_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("is_public", models.BooleanField(default=False)),
                ("game_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_lists",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GameListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_appearances",
                        to="trophies.game",
                    ),
                ),
                (
                    "game_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trophies.gamelist",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="GameListLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="trophies.gamelist",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_lists",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="gamelist",
            index=models.Index(
                fields=["profile", "is_deleted"], name="gl_profile_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamelist",
            index=models.Index(
                fields=["is_public", "is_deleted", "-like_count"],
                name="gl_public_likes_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gamelist",
            index=models.Index(
                fields=["is_public", "is_deleted", "-created_at"],
                name="gl_public_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gamelistitem",
            index=models.Index(
                fields=["game_list", "position"], name="gli_list_position_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamelistitem",
            unique_together={("game_list", "game")},
        ),
        migrations.AlterUniqueTogether(
            name="gamelistlike",
            unique_together={("game_list", "profile")},
        ),
    ]
