# Generated by Django 5.2.7 on 2026-02-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0133_game_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelist",
            name="selected_theme",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Selected gradient theme key for list background (premium only).",
                max_length=50,
            ),
        ),
    ]
