# Generated by Django 5.2.7 on 2026-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0134_gamelist_selected_theme"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="earnedtrophy",
            index=models.Index(
                condition=models.Q(("earned", True)),
                fields=["profile", "earned", "earned_date_time"],
                name="earnedtrophy_timeline_idx",
            ),
        ),
    ]
