# Generated by Django 5.2.7 on 2026-02-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0136_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="cover_letter",
            field=models.CharField(blank=True, default="", max_length=1),
        ),
    ]
