# Generated by Django 5.2.7 on 2026-02-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0137_challenge_cover_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="concept_lock",
            field=models.BooleanField(
                default=False,
                help_text="Admin concept override lock - won't be automatically updated.",
            ),
        ),
    ]
