# Generated by Django 5.2.7 on 2026-02-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0138_add_game_concept_lock"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="concept_stale",
            field=models.BooleanField(
                default=False, help_text="Flag for concept re-lookup on next sync."
            ),
        ),
    ]
