# Generated by Django 5.2.7 on 2026-02-17 00:21

from django.db import migrations, models


def truncate_long_names(apps, schema_editor):
    Challenge = apps.get_model('trophies', 'Challenge')
    for c in Challenge.objects.filter(name__regex=r'.{76,}'):
        c.name = c.name[:75]
        c.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0140_add_game_family"),
    ]

    operations = [
        migrations.RunPython(truncate_long_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="challenge",
            name="name",
            field=models.CharField(max_length=75),
        ),
    ]
