# Generated by Django 5.2.7 on 2026-02-17 22:36

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0141_reduce_challenge_name_length"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="game",
            name="game_platform_idx",
        ),
        migrations.AlterField(
            model_name="concept",
            name="comment_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of concept-level comments (excludes trophy and checklist comments)",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title_platform"], name="game_platform_gin_idx"
            ),
        ),
    ]
