# Generated by Django 5.2.7 on 2026-02-18 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0142_replace_platform_btree_with_gin_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("az", "A-Z Platinum Challenge"),
                    ("calendar", "Platinum Calendar"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CalendarChallengeDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("day", models.PositiveSmallIntegerField()),
                ("is_filled", models.BooleanField(default=False)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("platinum_earned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_days",
                        to="trophies.challenge",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_day_slots",
                        to="trophies.game",
                    ),
                ),
            ],
            options={
                "ordering": ["month", "day"],
                "indexes": [
                    models.Index(
                        fields=["challenge", "is_filled"],
                        name="calday_challenge_filled_idx",
                    )
                ],
                "unique_together": {("challenge", "month", "day")},
            },
        ),
    ]
