# Generated by Django 5.2.7 on 2026-02-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0143_calendar_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarchallengeday",
            name="plat_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
