# Generated by Django 5.2.7 on 2026-02-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0150_shovelware_detection_improvements"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="cover_genre",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="challenge",
            name="subgenre_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("az", "A-Z Platinum Challenge"),
                    ("calendar", "Platinum Calendar"),
                    ("genre", "Genre Challenge"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="GenreChallengeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(db_index=True, max_length=50)),
                (
                    "genre_display",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genre_slots",
                        to="trophies.challenge",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="genre_challenge_slots",
                        to="trophies.concept",
                    ),
                ),
            ],
            options={
                "ordering": ["genre"],
                "indexes": [
                    models.Index(
                        fields=["challenge", "is_completed"],
                        name="genreslot_chal_completed_idx",
                    )
                ],
                "unique_together": {("challenge", "genre")},
            },
        ),
    ]
