# Generated by Django 5.2.7 on 2026-02-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0151_genre_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="bonus_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="GenreBonusSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_slots",
                        to="trophies.challenge",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="genre_bonus_slots",
                        to="trophies.concept",
                    ),
                ),
            ],
            options={
                "ordering": ["assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["challenge", "is_completed"],
                        name="bonusslot_chal_completed_idx",
                    )
                ],
                "unique_together": {("challenge", "concept")},
            },
        ),
    ]
