# Generated by Django 5.2.7 on 2026-02-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0154_alter_milestone_criteria_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisherblacklist",
            name="is_blacklisted",
            field=models.BooleanField(
                default=False,
                help_text="True when any concept is flagged. All publisher games get flagged.",
            ),
        ),
    ]
