# Generated by Django 5.2.7 on 2026-02-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0155_immediate_publisher_blacklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardConfig",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="dashboard_config",
                        serialize=False,
                        to="trophies.profile",
                    ),
                ),
                ("module_order", models.JSONField(blank=True, default=list)),
                ("hidden_modules", models.JSONField(blank=True, default=list)),
                ("module_settings", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard Config",
                "verbose_name_plural": "Dashboard Configs",
            },
        ),
    ]
