# Generated by Django 5.2.7 on 2026-02-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0157_challenge_platted_subgenre_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="criteria_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Award"),
                    ("plat_count", "Earned Plats"),
                    ("psn_linked", "PSN Profile Linked"),
                    ("discord_linked", "Discord Connected"),
                    ("rating_count", "Games Rated"),
                    ("playtime_hours", "Total Playtime (Hours)"),
                    ("trophy_count", "Total Trophies Earned"),
                    ("comment_upvotes", "Comment Upvotes Received"),
                    ("checklist_upvotes", "Checklist Upvotes Received"),
                    ("badge_count", "Badge Tiers Earned"),
                    ("unique_badge_count", "Unique Badges Earned"),
                    ("completion_count", "Games 100% Completed"),
                    ("stage_count", "Badge Stages Completed"),
                    ("az_progress", "A-Z Challenge Letters"),
                    ("genre_progress", "Genre Challenge Genres"),
                    ("subgenre_progress", "Subgenre Collection"),
                    ("calendar_month_jan", "Calendar: January Complete"),
                    ("calendar_month_feb", "Calendar: February Complete"),
                    ("calendar_month_mar", "Calendar: March Complete"),
                    ("calendar_month_apr", "Calendar: April Complete"),
                    ("calendar_month_may", "Calendar: May Complete"),
                    ("calendar_month_jun", "Calendar: June Complete"),
                    ("calendar_month_jul", "Calendar: July Complete"),
                    ("calendar_month_aug", "Calendar: August Complete"),
                    ("calendar_month_sep", "Calendar: September Complete"),
                    ("calendar_month_oct", "Calendar: October Complete"),
                    ("calendar_month_nov", "Calendar: November Complete"),
                    ("calendar_month_dec", "Calendar: December Complete"),
                    ("calendar_months_total", "Calendar Months Completed"),
                    ("calendar_complete", "Calendar Challenge Complete"),
                    ("is_premium", "Premium Subscriber"),
                    ("subscription_months", "Subscription Months"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
    ]
