# Generated by Django 5.2.7 on 2026-02-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0158_alter_milestone_criteria_type_unique_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilegamification",
            name="unique_badges_earned",
            field=models.PositiveIntegerField(
                default=0, help_text="Count of distinct badge series earned"
            ),
        ),
    ]
