# Generated by Django 5.2.7 on 2026-02-26 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0159_add_unique_badges_earned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptTrophyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trophy_group_id",
                    models.CharField(
                        help_text="Matches TrophyGroup.trophy_group_id ('default', '001', etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Canonical display name for this group (e.g., 'Base Game', 'DLC Pack 1')",
                        max_length=255,
                    ),
                ),
                ("icon_url", models.URLField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "trophy_group_id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Review text (50-8000 characters, markdown supported)",
                        max_length=8000,
                    ),
                ),
                (
                    "recommended",
                    models.BooleanField(
                        help_text="True = thumbs up (recommended), False = thumbs down (not recommended)"
                    ),
                ),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("funny_count", models.PositiveIntegerField(default=0)),
                ("reply_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-helpful_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("delete", "Review Deleted"),
                            ("restore", "Review Restored"),
                            ("dismiss_report", "Report Dismissed"),
                            ("report_reviewed", "Report Reviewed"),
                        ],
                        db_index=True,
                        default="delete",
                        max_length=20,
                    ),
                ),
                ("review_id_snapshot", models.IntegerField()),
                (
                    "original_body",
                    models.TextField(
                        help_text="Original review text preserved for context"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Moderator's reason for action"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of review author at time of action",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("inappropriate", "Inappropriate Content"),
                            ("spoiler", "Unmarked Spoiler"),
                            ("misinformation", "Misinformation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Additional context for the report",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                            ("action_taken", "Action Taken"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("helpful", "Helpful"), ("funny", "Funny")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="concept",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="concept",
            index=models.Index(fields=["slug"], name="concept_slug_idx"),
        ),
        migrations.AddField(
            model_name="concepttrophygroup",
            name="concept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concept_trophy_groups",
                to="trophies.concept",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userconceptrating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userconceptrating",
            name="concept_trophy_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = base game rating (backward compatible). Set = DLC-specific rating.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_ratings",
                to="trophies.concepttrophygroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userconceptrating",
            unique_together={("profile", "concept", "concept_trophy_group")},
        ),
        migrations.AddField(
            model_name="review",
            name="concept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="trophies.concept",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="concept_trophy_group",
            field=models.ForeignKey(
                help_text="Which trophy group this review is for (base game or specific DLC)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="trophies.concepttrophygroup",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="trophies.profile",
            ),
        ),
        migrations.AddField(
            model_name="reviewmoderationlog",
            name="concept",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trophies.concept",
            ),
        ),
        migrations.AddField(
            model_name="reviewmoderationlog",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_moderation_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewmoderationlog",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderation_logs",
                to="trophies.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewmoderationlog",
            name="review_author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_reviews",
                to="trophies.profile",
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_replies",
                to="trophies.profile",
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="trophies.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_review_reports",
                to="trophies.profile",
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="trophies.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_review_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewmoderationlog",
            name="related_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_logs",
                to="trophies.reviewreport",
            ),
        ),
        migrations.AddField(
            model_name="reviewvote",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_votes",
                to="trophies.profile",
            ),
        ),
        migrations.AddField(
            model_name="reviewvote",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="trophies.review",
            ),
        ),
        migrations.AddIndex(
            model_name="concepttrophygroup",
            index=models.Index(
                fields=["concept", "trophy_group_id"], name="ctg_concept_group_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="concepttrophygroup",
            unique_together={("concept", "trophy_group_id")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["concept", "concept_trophy_group", "-created_at"],
                name="review_concept_group_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["concept", "concept_trophy_group", "-helpful_count"],
                name="review_helpful_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["profile", "-created_at"], name="review_profile_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["is_deleted", "created_at"], name="review_moderation_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("profile", "concept", "concept_trophy_group")},
        ),
        migrations.AddIndex(
            model_name="reviewreply",
            index=models.Index(
                fields=["review", "created_at"], name="reviewreply_review_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(
                fields=["status", "-created_at"], name="reviewreport_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(fields=["review"], name="reviewreport_review_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reviewreport",
            unique_together={("review", "reporter")},
        ),
        migrations.AddIndex(
            model_name="reviewmoderationlog",
            index=models.Index(
                fields=["-timestamp", "moderator"], name="reviewmodlog_timestamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewmoderationlog",
            index=models.Index(
                fields=["action_type", "-timestamp"], name="reviewmodlog_action_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewmoderationlog",
            index=models.Index(
                fields=["review_author", "-timestamp"], name="reviewmodlog_author_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewvote",
            index=models.Index(
                fields=["review", "profile"], name="reviewvote_lookup_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewvote",
            unique_together={("review", "profile", "vote_type")},
        ),
    ]
