# Generated by Django 5.2.7 on 2026-02-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0160_concepttrophygroup_review_reviewmoderationlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("series", "Series"),
                    ("collection", "Collection"),
                    ("megamix", "Megamix"),
                    ("developer", "Developer"),
                    ("misc", "Miscellaneous"),
                ],
                default="series",
                max_length=10,
            ),
        ),
    ]
