# Generated by Django 5.2.7 on 2026-03-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0162_review_word_count_and_milestone_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewmoderationlog",
            name="internal_notes",
            field=models.TextField(
                blank=True, help_text="Private staff notes (not shown to user)"
            ),
        ),
    ]
