# Generated by Django 5.2.7 on 2026-03-14 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0164_remove_comment_count_and_comment_upvotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile who submitted this badge concept.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_badges",
                to="trophies.profile",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("series", "Series"),
                    ("collection", "Collection"),
                    ("megamix", "Megamix"),
                    ("developer", "Developer"),
                    ("user", "User"),
                    ("misc", "Miscellaneous"),
                ],
                default="series",
                max_length=10,
            ),
        ),
    ]
