# Generated by Django 5.2.7 on 2026-03-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0165_add_user_badge_type_and_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardconfig",
            name="tab_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tab layout: {active_tab, tab_order, custom_tabs, module_tab_overrides}",
            ),
        ),
    ]
