# Generated by Django 5.2.7 on 2026-03-18 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0166_add_dashboard_tab_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileCardSettings",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="card_settings",
                        serialize=False,
                        to="trophies.profile",
                    ),
                ),
                (
                    "public_sig_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the public forum signature URL is active.",
                    ),
                ),
                (
                    "public_sig_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Unique token for the public forum signature URL.",
                        unique=True,
                    ),
                ),
                (
                    "card_theme",
                    models.CharField(
                        default="default",
                        help_text="Theme key for the profile card background.",
                        max_length=50,
                    ),
                ),
                (
                    "sig_last_rendered",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the forum sig PNG/SVG was last rendered.",
                        null=True,
                    ),
                ),
                (
                    "sig_render_hash",
                    models.CharField(
                        blank=True,
                        help_text="MD5 of the data used for last render (to skip unchanged).",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Card Settings",
                "verbose_name_plural": "Profile Card Settings",
            },
        ),
    ]
