# Generated by Django 5.2.7 on 2026-03-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0168_rename_community_tab_to_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyrecap",
            name="has_been_viewed",
            field=models.BooleanField(
                default=False,
                help_text="True once the user has viewed this recap on the slides page",
            ),
        ),
    ]
