# Generated by Django 5.2.7 on 2026-03-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0169_add_monthly_recap_has_been_viewed"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageCompletionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Effective completion date (max of game completion vs badge creation).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_completion_events",
                        to="trophies.badge",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which concept satisfied this stage completion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_completion_events",
                        to="trophies.concept",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_completions",
                        to="trophies.profile",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_events",
                        to="trophies.stage",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["profile", "completed_at"],
                        name="stagecomp_profile_date_idx",
                    ),
                    models.Index(
                        fields=["profile", "badge"], name="stagecomp_profile_badge_idx"
                    ),
                ],
                "unique_together": {("profile", "badge", "stage")},
            },
        ),
    ]
