# Generated by Django 5.2.7 on 2026-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0170_add_stage_completion_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("series", "Series"),
                    ("collection", "Collection"),
                    ("megamix", "Megamix"),
                    ("developer", "Developer"),
                    ("user", "User"),
                    ("genre", "Genre"),
                    ("misc", "Miscellaneous"),
                ],
                default="series",
                max_length=10,
            ),
        ),
    ]
