# Generated by Django 5.2.7 on 2026-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0171_alter_badge_badge_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banner_position",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Banner vertical position (0=top, 50=center, 100=bottom).",
            ),
        ),
    ]
