# Generated by Django 5.2.7 on 2026-03-25 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0172_profile_banner_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileBadgeShowcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Position in the showcase carousel (1-3)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcased_by",
                        to="trophies.badge",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_showcase",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "display_order"],
                        name="showcase_profile_order_idx",
                    )
                ],
                "unique_together": {("profile", "badge")},
            },
        ),
    ]
