# Generated by Django 5.2.7 on 2026-03-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0173_profilebadgeshowcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilebadgeshowcase",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Position in the showcase (1-5), auto-assigned on creation",
            ),
        ),
    ]
