# Generated by Django 5.2.7 on 2026-03-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0174_fix_showcase_display_order_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap",
                        to="trophies.concept",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_roadmaps",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadmapStepTrophy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trophy_id", models.IntegerField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_trophies",
                        to="trophies.roadmapstep",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("general_tips", models.TextField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                (
                    "concept_trophy_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_tabs",
                        to="trophies.concepttrophygroup",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="trophies.roadmap",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "concept_trophy_group__sort_order",
                    "concept_trophy_group__trophy_group_id",
                ],
            },
        ),
        migrations.AddField(
            model_name="roadmapstep",
            name="tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="trophies.roadmaptab",
            ),
        ),
        migrations.CreateModel(
            name="TrophyGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trophy_id", models.IntegerField()),
                ("body", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trophy_guides",
                        to="trophies.roadmaptab",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(fields=["status"], name="roadmap_status_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roadmapsteptrophy",
            unique_together={("step", "trophy_id")},
        ),
        migrations.AlterUniqueTogether(
            name="roadmaptab",
            unique_together={("roadmap", "concept_trophy_group")},
        ),
        migrations.AlterUniqueTogether(
            name="trophyguide",
            unique_together={("tab", "trophy_id")},
        ),
    ]
