# Generated by Django 5.2.7 on 2026-03-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0175_roadmap_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapstep",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
