# Generated by Django 5.2.7 on 2026-03-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0171_alter_badge_badge_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="igdb_genres",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="concept",
            name="igdb_themes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igdb_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "country",
                    models.IntegerField(
                        blank=True, help_text="ISO 3166-1 numeric code", null=True
                    ),
                ),
                (
                    "logo_image_id",
                    models.CharField(
                        blank=True, help_text="IGDB image hash", max_length=100
                    ),
                ),
                (
                    "company_size",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1"),
                            (2, "2-10"),
                            (3, "11-50"),
                            (4, "51-200"),
                            (5, "201-500"),
                            (6, "501-1000"),
                            (7, "1001-5000"),
                            (8, "5001-10000"),
                            (9, "10001+"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Founding date", null=True),
                ),
                ("change_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Points to new company after merger/rename",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_identities",
                        to="trophies.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsidiaries",
                        to="trophies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConceptCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_developer", models.BooleanField(default=False)),
                ("is_publisher", models.BooleanField(default=False)),
                ("is_porting", models.BooleanField(default=False)),
                ("is_supporting", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_concepts",
                        to="trophies.company",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_companies",
                        to="trophies.concept",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "concept companies",
            },
        ),
        migrations.CreateModel(
            name="IGDBMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igdb_id", models.IntegerField(db_index=True, unique=True)),
                ("igdb_name", models.CharField(max_length=500)),
                ("igdb_slug", models.CharField(blank=True, max_length=300)),
                ("match_confidence", models.FloatField(help_text="0.0 to 1.0")),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("external_id", "External ID"),
                            ("exact_name", "Exact Name"),
                            ("fuzzy_name", "Fuzzy Name"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("auto_accepted", "Auto-Accepted"),
                            ("pending_review", "Pending Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "game_category",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Main Game"),
                            (1, "DLC/Addon"),
                            (2, "Expansion"),
                            (3, "Bundle"),
                            (4, "Standalone Expansion"),
                            (5, "Mod"),
                            (6, "Episode"),
                            (7, "Season"),
                            (8, "Remake"),
                            (9, "Remaster"),
                            (10, "Expanded Game"),
                            (11, "Port"),
                            (12, "Fork"),
                            (13, "Pack"),
                            (14, "Update"),
                        ],
                        null=True,
                    ),
                ),
                ("igdb_summary", models.TextField(blank=True)),
                ("igdb_storyline", models.TextField(blank=True)),
                (
                    "time_to_beat_hastily",
                    models.IntegerField(
                        blank=True, help_text="Speedrun time in seconds", null=True
                    ),
                ),
                (
                    "time_to_beat_normally",
                    models.IntegerField(
                        blank=True,
                        help_text="Average playthrough in seconds",
                        null=True,
                    ),
                ),
                (
                    "time_to_beat_completely",
                    models.IntegerField(
                        blank=True,
                        help_text="100%% completion time in seconds (platinum estimate)",
                        null=True,
                    ),
                ),
                (
                    "igdb_first_release_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("game_engine_name", models.CharField(blank=True, max_length=100)),
                ("igdb_cover_image_id", models.CharField(blank=True, max_length=100)),
                (
                    "franchise_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Franchise/collection names for GameFamily suggestions",
                    ),
                ),
                (
                    "similar_game_igdb_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IGDB IDs of similar games for future recommendations",
                    ),
                ),
                (
                    "external_urls",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="External links: {steam: url, wikipedia: url, ...}",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="igdb_match",
                        to="trophies.concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "IGDB match",
                "verbose_name_plural": "IGDB matches",
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="company_name_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["igdb_id"], name="company_igdb_id_idx"),
        ),
        migrations.AddIndex(
            model_name="conceptcompany",
            index=models.Index(fields=["concept"], name="conceptcompany_concept_idx"),
        ),
        migrations.AddIndex(
            model_name="conceptcompany",
            index=models.Index(fields=["company"], name="conceptcompany_company_idx"),
        ),
        migrations.AddIndex(
            model_name="conceptcompany",
            index=models.Index(fields=["is_developer"], name="conceptcompany_dev_idx"),
        ),
        migrations.AddIndex(
            model_name="conceptcompany",
            index=models.Index(fields=["is_publisher"], name="conceptcompany_pub_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="conceptcompany",
            unique_together={("concept", "company")},
        ),
        migrations.AddIndex(
            model_name="igdbmatch",
            index=models.Index(fields=["igdb_id"], name="igdbmatch_igdb_id_idx"),
        ),
        migrations.AddIndex(
            model_name="igdbmatch",
            index=models.Index(fields=["status"], name="igdbmatch_status_idx"),
        ),
        migrations.AddIndex(
            model_name="igdbmatch",
            index=models.Index(
                fields=["match_confidence"], name="igdbmatch_confidence_idx"
            ),
        ),
    ]
