# Generated by Django 5.2.7 on 2026-03-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0177_igdb_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igdbmatch",
            name="igdb_id",
            field=models.IntegerField(db_index=True),
        ),
    ]
