# Generated by Django 5.2.7 on 2026-04-02 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0178_igdb_match_drop_unique_igdb_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("delisted", "Game has been delisted"),
                            ("not_delisted", "Game is NOT delisted"),
                            ("unobtainable", "Trophies are unobtainable"),
                            ("obtainable", "Trophies ARE obtainable"),
                            ("is_shovelware", "Game is shovelware"),
                            ("not_shovelware", "Game is NOT shovelware"),
                            ("missing_vr", "Game supports VR but is not tagged"),
                            (
                                "has_online_trophies",
                                "Game has online-required trophies",
                            ),
                            (
                                "no_online_trophies",
                                "Game does NOT have online trophies",
                            ),
                            ("has_buggy_trophies", "Game has buggy/broken trophies"),
                            (
                                "buggy_trophies_resolved",
                                "Buggy trophies have been fixed",
                            ),
                            ("region_incorrect", "Regional info is incorrect"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Optional context for the flag.",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="has_buggy_trophies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["has_buggy_trophies"], name="game_buggy_trophies_idx"
            ),
        ),
        migrations.AddField(
            model_name="gameflag",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="trophies.game",
            ),
        ),
        migrations.AddField(
            model_name="gameflag",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_game_flags",
                to="trophies.profile",
            ),
        ),
        migrations.AddField(
            model_name="gameflag",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_game_flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="gameflag",
            index=models.Index(
                fields=["status", "-created_at"], name="gameflag_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gameflag",
            index=models.Index(fields=["game"], name="gameflag_game_idx"),
        ),
        migrations.AddIndex(
            model_name="gameflag",
            index=models.Index(fields=["reporter"], name="gameflag_reporter_idx"),
        ),
        migrations.AddIndex(
            model_name="gameflag",
            index=models.Index(fields=["flag_type"], name="gameflag_type_idx"),
        ),
    ]
