# Generated by Django 5.2.7 on 2026-04-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0179_game_has_buggy_trophies_gameflag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igdbmatch",
            name="igdb_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="igdbmatch",
            name="igdb_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="igdbmatch",
            name="match_confidence",
            field=models.FloatField(blank=True, help_text="0.0 to 1.0", null=True),
        ),
        migrations.AlterField(
            model_name="igdbmatch",
            name="match_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("external_id", "External ID"),
                    ("exact_name", "Exact Name"),
                    ("fuzzy_name", "Fuzzy Name"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="igdbmatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("auto_accepted", "Auto-Accepted"),
                    ("pending_review", "Pending Review"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("no_match", "No Match Found"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
