# Generated by Django 5.2.7 on 2026-04-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0181_igdbmatch_no_match_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igdb_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "game engine",
                "verbose_name_plural": "game engines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igdb_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igdb_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConceptEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_engines",
                        to="trophies.concept",
                    ),
                ),
                (
                    "engine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engine_concepts",
                        to="trophies.gameengine",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["concept"], name="conceptengine_concept_idx"),
                    models.Index(fields=["engine"], name="conceptengine_engine_idx"),
                ],
                "unique_together": {("concept", "engine")},
            },
        ),
        migrations.CreateModel(
            name="ConceptGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_genres",
                        to="trophies.concept",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genre_concepts",
                        to="trophies.genre",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["concept"], name="conceptgenre_concept_idx"),
                    models.Index(fields=["genre"], name="conceptgenre_genre_idx"),
                ],
                "unique_together": {("concept", "genre")},
            },
        ),
        migrations.CreateModel(
            name="ConceptTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_themes",
                        to="trophies.concept",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_concepts",
                        to="trophies.theme",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["concept"], name="concepttheme_concept_idx"),
                    models.Index(fields=["theme"], name="concepttheme_theme_idx"),
                ],
                "unique_together": {("concept", "theme")},
            },
        ),
    ]
