# Generated by Django 5.2.7 on 2026-04-08 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("trophies", "0183_populate_genres_themes_engines"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=32)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Historical truth of when the event happened. NEVER use timezone.now() at insert time for trophy events.",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-event-type structured payload (rare-trophy earn rate, badge tier, coalesced sub-event lists, etc.).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="The actor who caused the event. Nullable for system events (Day Zero, etc.).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="trophies.profile",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(fields=["-occurred_at"], name="event_occurred_idx"),
                    models.Index(
                        fields=["profile", "-occurred_at"], name="event_profile_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-occurred_at"], name="event_type_idx"
                    ),
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="event_target_idx",
                    ),
                ],
            },
        ),
    ]
