# Generated by Django 5.2.7 on 2026-04-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0188_drop_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tour_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when user completed or skipped the Welcome Tour.",
                null=True,
            ),
        ),
    ]
