# Generated by Django 5.2.7 on 2026-04-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0189_add_tour_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="game_detail_tour_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when user completed or skipped the Game Detail Tour.",
                null=True,
            ),
        ),
    ]
