# Generated by Django 5.2.7 on 2026-04-14 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0191_add_badge_detail_tour_completed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoutAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "refresh_frequency_hours",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Hours between refresh syncs for this scout.",
                    ),
                ),
                (
                    "games_discovered",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of new games first seen via this scout.",
                    ),
                ),
                ("staff_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="trophygroup",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this trophy group was first added to the database.",
            ),
        ),
        migrations.AddIndex(
            model_name="trophygroup",
            index=models.Index(fields=["-created_at"], name="trophy_group_created_idx"),
        ),
        migrations.AddField(
            model_name="scoutaccount",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_scouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scoutaccount",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scout_account",
                to="trophies.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="scoutaccount",
            index=models.Index(
                fields=["status", "created_at"], name="scout_status_idx"
            ),
        ),
    ]
