# Generated by Django 5.2.7 on 2026-04-15 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0192_scout_account_and_trophy_group_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmaptab",
            name="difficulty",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Author-assessed difficulty (1-10). Distinct from community ratings.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="roadmaptab",
            name="estimated_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Author-estimated hours to complete this trophy group.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roadmaptab",
            name="min_playthroughs",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Minimum playthroughs required for all trophies."
            ),
        ),
        migrations.AddField(
            model_name="roadmaptab",
            name="missable_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of missable trophies in this group."
            ),
        ),
        migrations.AddField(
            model_name="roadmaptab",
            name="online_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether online play is required for trophies in this group.",
            ),
        ),
        migrations.AlterField(
            model_name="gameflag",
            name="flag_type",
            field=models.CharField(
                choices=[
                    ("delisted", "Game has been delisted"),
                    ("not_delisted", "Game is NOT delisted"),
                    ("unobtainable", "Trophies are unobtainable"),
                    ("obtainable", "Trophies ARE obtainable"),
                    ("is_shovelware", "Game is shovelware"),
                    ("not_shovelware", "Game is NOT shovelware"),
                    ("missing_vr", "Game supports VR but is not tagged"),
                    ("has_online_trophies", "Game has online-required trophies"),
                    ("no_online_trophies", "Game does NOT have online trophies"),
                    ("has_buggy_trophies", "Game has buggy/broken trophies"),
                    ("buggy_trophies_resolved", "Buggy trophies have been fixed"),
                    ("region_incorrect", "Regional info is incorrect"),
                    ("other", "Other (please describe)"),
                ],
                max_length=30,
            ),
        ),
    ]
