# Generated by Django 5.2.7 on 2026-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0193_roadmaptab_guide_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="trophyguide",
            name="is_missable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trophyguide",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trophyguide",
            name="is_unobtainable",
            field=models.BooleanField(default=False),
        ),
    ]
