# Generated by Django 5.2.7 on 2026-04-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0194_trophy_guide_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Franchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igdb_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("franchise", "Franchise"),
                            ("collection", "Collection"),
                        ],
                        default="franchise",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConceptFranchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_franchises",
                        to="trophies.concept",
                    ),
                ),
                (
                    "franchise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="franchise_concepts",
                        to="trophies.franchise",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["concept"], name="conceptfranchise_concept_idx"
                    ),
                    models.Index(
                        fields=["franchise"], name="conceptfranchise_franchise_idx"
                    ),
                ],
                "unique_together": {("concept", "franchise")},
            },
        ),
    ]
