# Generated by Django 5.2.7 on 2026-04-16 08:55

from django.db import migrations, models
from django.db.models import Count


def backfill_single_franchise_main(apps, schema_editor):
    """For concepts with exactly ONE ConceptFranchise link, mark it as is_main.

    Most games have a single franchise, and for those the lone link is
    obviously the "main" one. This avoids a regression where the browse page
    and detail Games tab go empty until full re-enrichment runs. Concepts
    with multiple franchise links are left with is_main=False on every link
    until ``enrich_from_igdb --refresh`` populates the IGDB-determined main.
    """
    ConceptFranchise = apps.get_model("trophies", "ConceptFranchise")

    # Find concept_ids that have exactly one ConceptFranchise row.
    single_franchise_concept_ids = (
        ConceptFranchise.objects
        .values('concept_id')
        .annotate(n=Count('id'))
        .filter(n=1)
        .values_list('concept_id', flat=True)
    )

    ConceptFranchise.objects.filter(
        concept_id__in=single_franchise_concept_ids
    ).update(is_main=True)


def reverse_backfill(apps, schema_editor):
    """No-op reverse: the schema will be removed by the AddField reverse anyway."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0195_franchise_and_concept_franchise"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptfranchise",
            name="is_main",
            field=models.BooleanField(
                default=False,
                help_text="True when this is the concept's primary franchise (IGDB's singular `franchise` field). At most one is_main=True per concept.",
            ),
        ),
        migrations.AddIndex(
            model_name="conceptfranchise",
            index=models.Index(fields=["is_main"], name="conceptfranchise_main_idx"),
        ),
        migrations.RunPython(backfill_single_franchise_main, reverse_backfill),
    ]
