# Generated by Django 5.2.7 on 2026-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0196_add_is_main_to_concept_franchise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="franchise",
            name="igdb_id",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="franchise",
            constraint=models.UniqueConstraint(
                fields=("igdb_id", "source_type"),
                name="franchise_igdb_id_source_type_unique",
            ),
        ),
    ]
