# Generated by Django 5.2.7 on 2026-04-17 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0198_normalize_tag_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameengine",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="IGDB engine description, surfaced in the engine detail header.",
            ),
        ),
        migrations.AddField(
            model_name="gameengine",
            name="logo_image_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IGDB image hash for the engine logo. Used by logo_url().",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="EngineCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_engines",
                        to="trophies.company",
                    ),
                ),
                (
                    "engine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engine_companies",
                        to="trophies.gameengine",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameengine",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="engines",
                through="trophies.EngineCompany",
                to="trophies.company",
            ),
        ),
        migrations.AddIndex(
            model_name="enginecompany",
            index=models.Index(fields=["engine"], name="enginecompany_engine_idx"),
        ),
        migrations.AddIndex(
            model_name="enginecompany",
            index=models.Index(fields=["company"], name="enginecompany_company_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="enginecompany",
            unique_together={("engine", "company")},
        ),
    ]
