# Generated by Django 5.2.7 on 2026-04-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0200_enrich_engines_and_prune_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileShowcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "showcase_type",
                    models.CharField(
                        choices=[
                            ("platinum_case", "Platinum Trophy Case"),
                            ("favorite_games", "Favorite Games"),
                            ("badge_showcase", "Badge Showcase"),
                            ("rarest_trophies", "Rarest Trophies"),
                            ("recent_platinums", "Recent Platinums"),
                            ("review_showcase", "Review Showcase"),
                            ("challenge_showcase", "Challenge Showcase"),
                            ("title_showcase", "Title Showcase"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False when a premium-only showcase is preserved during downgrade.",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User-selected item IDs for this showcase (schema varies per type).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcases",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "is_active", "sort_order"],
                        name="profileshowcase_active_idx",
                    )
                ],
                "unique_together": {("profile", "showcase_type")},
            },
        ),
    ]
