# Generated by Django 5.2.7 on 2026-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0204_drop_developer_blacklist_flagged_concepts"),
    ]

    operations = [
        migrations.AddField(
            model_name="igdbmatch",
            name="is_likely_compilation",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
