# Generated by Django 5.2.7 on 2026-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0205_add_igdbmatch_is_likely_compilation"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamefamily",
            name="igdb_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="IGDB game id this family maps to. Nullable to support admin-created families for edge cases IGDB does not cover; Unique when set.",
                null=True,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="GameFamilyProposal",
        ),
    ]
