# Generated by Django 5.2.7 on 2026-04-20 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0206_phase_2_6_game_families"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RematchSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_igdb_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("old_igdb_name", models.CharField(blank=True, max_length=500)),
                ("old_confidence", models.FloatField(blank=True, null=True)),
                ("old_match_method", models.CharField(blank=True, max_length=20)),
                ("proposed_igdb_id", models.IntegerField(db_index=True)),
                ("proposed_igdb_name", models.CharField(blank=True, max_length=500)),
                ("proposed_confidence", models.FloatField()),
                ("proposed_match_method", models.CharField(blank=True, max_length=20)),
                (
                    "proposed_raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of the IGDB payload so the suggestion can be applied without re-querying.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rematch_suggestions",
                        to="trophies.concept",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_rematch_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rematch suggestion",
                "verbose_name_plural": "rematch suggestions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="rematch_status_created_idx",
                    ),
                    models.Index(
                        fields=["concept", "status"], name="rematch_concept_status_idx"
                    ),
                ],
            },
        ),
    ]
