# Generated by Django 5.2.7 on 2026-04-21 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0207_phase_3_rematch_suggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptSplitEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_original_title", models.CharField(blank=True, max_length=500)),
                ("parent_original_igdb_id", models.IntegerField(blank=True, null=True)),
                (
                    "parent_original_igdb_name",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "kept_game_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Game.id retained on the parent concept after the split.",
                        null=True,
                    ),
                ),
                ("is_reversed", models.BooleanField(db_index=True, default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child_concepts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Newly created concepts, one per non-kept Game.",
                        related_name="splits_as_child",
                        to="trophies.concept",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_concept_splits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="The concept that was split. Kept attached to one Game and renamed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="splits_as_parent",
                        to="trophies.concept",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_concept_splits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "concept split event",
                "verbose_name_plural": "concept split events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_reversed", "-created_at"],
                        name="split_reversed_created_idx",
                    )
                ],
            },
        ),
    ]
