# Generated by Django 5.2.7 on 2026-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0208_phase_5_concept_split_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="igdbmatch",
            name="compilation_review_dismissed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
