# Generated by Django 5.2.7 on 2026-04-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0209_compilation_review_dismissed"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="title_lock",
            field=models.BooleanField(
                default=False,
                help_text="When True, PSN sync (`update_concept_english_fields`) will not overwrite `unified_title`. Set by admins who've manually merged a concept's title to the IGDB canonical (via `review_title_merges` or the admin), so subsequent regional sync passes don't regress the curated title back to the raw PSN titleName.",
            ),
        ),
        migrations.AddField(
            model_name="concept",
            name="title_reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set by `review_title_merges` when an admin approves, leaves, or merges this concept's title. Distinct from title_lock: this flag only means 'already reviewed, don't re-surface', while title_lock means 'PSN sync can't touch this'. Cleared automatically by Game.add_concept when a new game joins the concept, so a fresh sibling title gets a re-review.",
                null=True,
            ),
        ),
    ]
