# Generated by Django 5.2.7 on 2026-04-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0215_roadmap_note_tab_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapstep",
            name="gallery_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="trophyguide",
            name="gallery_images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
