# Generated by Django 5.2.7 on 2026-04-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0217_roadmap_per_ctg"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["country"], name="company_country_idx"),
        ),
        migrations.AddIndex(
            model_name="conceptcompany",
            index=models.Index(
                fields=["company", "is_developer"], name="cc_company_dev_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conceptcompany",
            index=models.Index(
                fields=["company", "is_publisher"], name="cc_company_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conceptcompany",
            index=models.Index(
                fields=["company", "is_porting"], name="cc_company_port_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conceptcompany",
            index=models.Index(
                fields=["company", "is_supporting"], name="cc_company_support_idx"
            ),
        ),
    ]
