# Generated by Django 5.2.7 on 2026-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0218_browse_perf_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="trophyguide",
            name="phase",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Recommended phase of the playthrough (story / grindy / endgame / etc).",
                max_length=20,
            ),
        ),
    ]
