# Generated by Django 5.2.7 on 2026-05-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0219_trophyguide_phase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roadmap",
            name="missable_count",
        ),
        migrations.RemoveField(
            model_name="roadmap",
            name="online_required",
        ),
    ]
