# Generated by Django 5.2.7 on 2026-05-02 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0220_remove_roadmap_derived_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collectibles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "intro_text",
                    models.TextField(
                        blank=True,
                        help_text="Markdown rendered at the top of the page (general advice, totals, prereqs).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectibles",
                        to="trophies.concept",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_collectibles",
                        to="trophies.profile",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_edited_collectibles",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collectibles Guide",
                "verbose_name_plural": "Collectibles Guides",
            },
        ),
        migrations.CreateModel(
            name="CollectibleArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text='In-game progression order. Used for the "in-game order" sort and per-area headers.',
                    ),
                ),
                (
                    "collectibles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="trophies.collectibles",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CollectiblesEditLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("branch_payload", models.JSONField(default=dict)),
                ("payload_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "collectibles",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_lock",
                        to="trophies.collectibles",
                    ),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="held_collectibles_locks",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collectibles Edit Lock",
                "verbose_name_plural": "Collectibles Edit Locks",
            },
        ),
        migrations.CreateModel(
            name="CollectiblesRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("edited", "Edited"),
                            ("published", "Published"),
                            ("unpublished", "Unpublished"),
                            ("restored", "Restored"),
                            ("force_unlocked", "Force unlocked"),
                            ("auto_taken_over", "Auto-taken over (stale lock)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Full Collectibles state after this action (types, areas, items)."
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text='Auto-generated short description (e.g., "edited 12 items in Feathers").',
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profile that triggered this revision. NULL preserves history if profile is later deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_collectibles_revisions",
                        to="trophies.profile",
                    ),
                ),
                (
                    "collectibles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="trophies.collectibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collectibles Revision",
                "verbose_name_plural": "Collectibles Revisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectibleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("info", "Blue (info)"),
                            ("success", "Green (success)"),
                            ("warning", "Amber (warning)"),
                            ("error", "Red (error)"),
                            ("accent", "Orange (accent)"),
                            ("secondary", "Purple (secondary)"),
                            ("primary", "Primary"),
                            ("neutral", "Neutral"),
                        ],
                        default="accent",
                        help_text="Tab + accent color. Picked from a curated palette so types stay visually distinct across the page.",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional Heroicon name for the tab.",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "collectibles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="trophies.collectibles",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Collectible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Short — what the item is."),
                ),
                (
                    "location",
                    models.TextField(blank=True, help_text="Markdown. How to find it."),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of {url, alt, caption}. Capped at 8 items server-side.",
                    ),
                ),
                ("is_missable", models.BooleanField(default=False)),
                ("is_dlc", models.BooleanField(default=False)),
                ("is_postgame", models.BooleanField(default=False)),
                (
                    "prerequisites",
                    models.TextField(
                        blank=True,
                        help_text='Free text. Examples: "Requires hookshot", "After completing Chapter 2".',
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Single timestamped video link."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="In-area sort."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_collectible_items",
                        to="trophies.profile",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_edited_collectible_items",
                        to="trophies.profile",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="trophies.collectiblearea",
                    ),
                ),
                (
                    "collectibles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trophies.collectibles",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trophies.collectibletype",
                    ),
                ),
            ],
            options={
                "ordering": ["area__order", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserCollectibleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("found_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collectible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="trophies.collectible",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectible_progress",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="collectibles",
            index=models.Index(fields=["status"], name="collectibles_status_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="collectiblearea",
            unique_together={("collectibles", "slug")},
        ),
        migrations.AddIndex(
            model_name="collectibleseditlock",
            index=models.Index(
                fields=["expires_at"], name="collectibles_lock_expires_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectiblesrevision",
            index=models.Index(
                fields=["collectibles", "-created_at"], name="coll_rev_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectiblesrevision",
            index=models.Index(
                fields=["author", "-created_at"], name="coll_rev_author_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectibletype",
            unique_together={("collectibles", "slug")},
        ),
        migrations.AddIndex(
            model_name="collectible",
            index=models.Index(
                fields=["collectibles", "type"], name="collectible_page_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectible",
            index=models.Index(
                fields=["collectibles", "area"], name="collectible_page_area_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercollectibleprogress",
            index=models.Index(
                fields=["profile", "collectible"], name="ucp_profile_item_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercollectibleprogress",
            unique_together={("profile", "collectible")},
        ),
    ]
