# Generated by Django 5.2.7 on 2026-05-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0221_igdbmatch_ps_release_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="youtube_channel_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="youtube_channel_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="roadmapstep",
            name="youtube_channel_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="roadmapstep",
            name="youtube_channel_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="trophyguide",
            name="youtube_channel_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="trophyguide",
            name="youtube_channel_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="trophyguide",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
