# Generated by Django 5.2.7 on 2026-05-04 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0222_youtube_attribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapCollectibleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("accent", "Accent"),
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Optional emoji prefix.", max_length=4
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("total_count", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profile that originally created this type. Set ownership is derived from the oldest type by created_by.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_collectible_types",
                        to="trophies.profile",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_edited_collectible_types",
                        to="trophies.profile",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectible_types",
                        to="trophies.roadmap",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("roadmap", "slug")},
            },
        ),
    ]
