# Generated by Django 5.2.7 on 2026-05-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0223_roadmap_collectible_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapCollectibleArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_collectible_areas",
                        to="trophies.profile",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_edited_collectible_areas",
                        to="trophies.profile",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectible_areas",
                        to="trophies.roadmap",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("roadmap", "slug")},
            },
        ),
        migrations.CreateModel(
            name="RoadmapCollectibleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("youtube_channel_name", models.CharField(blank=True, max_length=200)),
                ("youtube_channel_url", models.URLField(blank=True)),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                ("is_missable", models.BooleanField(default=False)),
                ("is_dlc", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="trophies.roadmapcollectiblearea",
                    ),
                ),
                (
                    "collectible_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trophies.roadmapcollectibletype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_collectible_items",
                        to="trophies.profile",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_edited_collectible_items",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserCollectibleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("found_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="trophies.roadmapcollectibleitem",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectible_progress",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="roadmapcollectibleitem",
            index=models.Index(
                fields=["collectible_type", "order"], name="ci_type_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercollectibleprogress",
            index=models.Index(
                fields=["profile", "item"], name="ci_progress_lookup_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercollectibleprogress",
            unique_together={("profile", "item")},
        ),
    ]
