# Generated by Django 5.2.7 on 2026-05-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0224_roadmap_collectible_areas_items_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="introduction",
            field=models.TextField(
                blank=True,
                help_text="Author intro / scope blurb shown at the very top of the roadmap detail page. Reads ahead of General Tips: what this guide covers vs. what to know while playing.",
            ),
        ),
    ]
