# Generated by Django 5.2.7 on 2026-05-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0225_roadmap_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapcollectibletype",
            name="name_plural",
            field=models.CharField(
                blank=True,
                help_text='Plural / category form ("Journals", "Journal Entries"). Falls back to the singular name when blank.',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="roadmapcollectibletype",
            name="name",
            field=models.CharField(
                help_text='Singular form, used per-item ("Journal", "Riddler Trophy").',
                max_length=100,
            ),
        ),
    ]
