# Generated by Django 5.2.7 on 2026-05-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0226_collectible_type_name_plural"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="last_profile_health_check",
        ),
    ]
