# Generated by Django 5.2.7 on 2026-05-21 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0228_roadmapareamarker"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label, e.g. 'PS3 Episodic'", max_length=120
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order within the Stage."
                    ),
                ),
                (
                    "concepts",
                    models.ManyToManyField(
                        help_text="Concepts grouped under this bundle.",
                        related_name="bundles",
                        to="trophies.concept",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_bundles",
                        to="trophies.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["stage"], name="conceptbundle_stage_idx")
                ],
            },
        ),
    ]
