# Generated by Django 5.2.7 on 2026-05-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0229_conceptbundle"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapCollectibleSubarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subareas",
                        to="trophies.roadmapcollectiblearea",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_collectible_subareas",
                        to="trophies.profile",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_edited_collectible_subareas",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("area", "slug")},
            },
        ),
        migrations.AddField(
            model_name="roadmapareamarker",
            name="subarea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="markers",
                to="trophies.roadmapcollectiblesubarea",
            ),
        ),
        migrations.AddField(
            model_name="roadmapcollectibleitem",
            name="subarea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="trophies.roadmapcollectiblesubarea",
            ),
        ),
    ]
