# Generated by Django 5.2.7 on 2026-05-25 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trophies",
            "0230_roadmapcollectiblesubarea_roadmapareamarker_subarea_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="anchor_migration_completed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set when this Concept has been processed by the anchor_concepts migration (its identity has been resolved against a canonical IGDB id). Null means the Concept still needs migration. New Concepts created during a migration batch are stamped immediately because they are at canonical identity by construction.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="igdbmatch",
            name="igdb_artwork_image_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="IGDB artwork image_ids. Render via artwork_urls(size).",
            ),
        ),
        migrations.AddField(
            model_name="igdbmatch",
            name="igdb_screenshot_image_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="IGDB screenshot image_ids. Render via screenshot_urls(size).",
            ),
        ),
        migrations.AddField(
            model_name="igdbmatch",
            name="igdb_video_youtube_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="IGDB video YouTube ids. Embed via video_embed_urls().",
            ),
        ),
        migrations.CreateModel(
            name="ConceptJoinReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_canonical_igdb_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Canonical IGDB id the matcher resolved for this Game.",
                    ),
                ),
                (
                    "flag_reasons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of strings from FLAG_REASON_CHOICES indicating why this Game needs review. Multiple reasons can fire at once.",
                    ),
                ),
                (
                    "trophy_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Short hash of the Game trophy metrics at proposal time.",
                        max_length=64,
                    ),
                ),
                (
                    "identity_check_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Identity cross-check results: title similarity score, platform overlap, release-date proximity, etc. Populated for staff context.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("deferred", "Deferred"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.OneToOneField(
                        help_text="The Game whose concept placement needs review.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_review",
                        to="trophies.game",
                    ),
                ),
                (
                    "proposed_concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="Existing Concept this Game would join. Null when the proposal is to create a new Concept, or when a collision was detected and the existing concept_id is unrelated.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="trophies.concept",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "concept join review",
                "verbose_name_plural": "concept join reviews",
                "indexes": [
                    models.Index(fields=["status"], name="cjreview_status_idx"),
                    models.Index(
                        fields=["proposed_canonical_igdb_id"], name="cjreview_igdb_idx"
                    ),
                    models.Index(fields=["created_at"], name="cjreview_created_idx"),
                ],
            },
        ),
    ]
