# Generated by Django 5.2.7 on 2026-05-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0231_anchor_concepts_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="anchor_migration_last_attempt_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set every time the anchor_concepts migration touches this Concept (whether it succeeds, defers due to NO_MATCH, splits, collides, or hits any other terminal state). Combined with anchor_migration_completed_at, lets the admin distinguish 'never attempted' from 'attempted but not anchored' — the latter are the concepts staff actually need to look at.",
                null=True,
            ),
        ),
    ]
