# Generated by Django 5.2.7 on 2026-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0233_concept_join_review_raw_igdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamefamily",
            name="origin_cover_image_id",
            field=models.CharField(
                blank=True,
                help_text="IGDB cover image id for the origin entry. Used to render the origin cover on family/lineage UI.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="gamefamily",
            name="origin_first_release_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='First release date of the origin (topmost canonical) IGDB entry. Used for the "Origin Release" sort on franchise / company detail pages.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gamefamily",
            name="origin_name",
            field=models.CharField(
                blank=True,
                help_text="IGDB name of the origin entry. Distinct from canonical_name, which may be admin-edited.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="gamefamily",
            name="origin_summary",
            field=models.TextField(
                blank=True,
                help_text="IGDB summary of the origin entry. Optional context for family detail / lineage display.",
            ),
        ),
    ]
