# Generated by Django 5.2.7 on 2026-05-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0234_game_family_origin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="hidden_authors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Profiles to hide from the public author/contributor display for this roadmap.",
                related_name="hidden_from_roadmaps",
                to="trophies.profile",
            ),
        ),
    ]
