# Generated by Django 5.2.7 on 2026-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0235_roadmap_hidden_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igdbmatch",
            name="match_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("external_id", "External ID"),
                    ("exact_name", "Exact Name"),
                    ("fuzzy_name", "Fuzzy Name"),
                    ("manual", "Manual"),
                    ("name_no_platform", "Name match (platform ignored)"),
                ],
                max_length=20,
            ),
        ),
    ]
