# Generated by Django 5.2.7 on 2026-05-28 16:44

from django.db import migrations, models


def delete_review_showcases(apps, schema_editor):
    """Delete ProfileShowcase rows for the retired review_showcase type."""
    ProfileShowcase = apps.get_model("trophies", "ProfileShowcase")
    ProfileShowcase.objects.filter(showcase_type="review_showcase").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0236_igdbmatch_name_no_platform_method"),
    ]

    operations = [
        migrations.RunPython(
            delete_review_showcases, migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="profileshowcase",
            name="showcase_type",
            field=models.CharField(
                choices=[
                    ("platinum_case", "Platinum Trophy Case"),
                    ("favorite_games", "Favorite Games"),
                    ("badge_showcase", "Badge Showcase"),
                    ("rarest_trophies", "Rarest Trophies"),
                    ("recent_platinums", "Recent Platinums"),
                    ("challenge_showcase", "Challenge Showcase"),
                    ("title_showcase", "Title Showcase"),
                ],
                max_length=30,
            ),
        ),
    ]
