# Generated by Django 5.2.7 on 2026-05-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0237_remove_review_showcase_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banner_image_url",
            field=models.URLField(
                blank=True,
                help_text="Exact banner image the user picked from the selected concept's landscape images (IGDB artwork/screenshot/cover). When set, takes precedence over selected_background.bg_url.",
                max_length=500,
                null=True,
            ),
        ),
    ]
