# Generated by Django 5.2.7 on 2026-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0239_alter_igdbmatch_match_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="trial_writers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Trial-role profiles granted writer powers on this roadmap. Has no effect on non-trial profiles.",
                related_name="trial_assigned_roadmaps",
                to="trophies.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="roadmap_role",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("trial", "Trial"),
                    ("writer", "Writer"),
                    ("editor", "Editor"),
                    ("publisher", "Publisher"),
                ],
                default="none",
                help_text="Roadmap authoring role. Independent of is_staff. trial: no global authoring power; publishers assign trials to specific roadmaps via Roadmap.trial_writers and the assignee acts as a writer on that roadmap only. writer: edit own sections on unpublished guides. editor: edit any field on unpublished guides. publisher: editor power plus toggle visibility and force-break locks.",
                max_length=20,
            ),
        ),
    ]
