# Generated by Django 5.2.7 on 2026-06-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0242_drop_orphan_legacy_guide_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated developer/company (developer badges). Drives the Frame's subject name + enables developer reporting.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="developed_badges",
                to="trophies.company",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="franchise",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated IGDB franchise (series/collection badges). Drives the Frame's subject name + enables franchise reporting.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="badges",
                to="trophies.franchise",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="rarity_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("common", "Common"),
                    ("uncommon", "Uncommon"),
                    ("rare", "Rare"),
                    ("mythic", "Mythic"),
                ],
                default="",
                help_text="Denormalized rarity bucket (drives the Frame's rarity icon). Refreshed by the rarity command.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="rarity_pct",
            field=models.FloatField(
                blank=True,
                help_text="Denormalized: % of linked profiles who have earned this badge. Refreshed by the rarity command (not hand-edited).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="rarity_rank",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Denormalized: rank among live badges by rarity (1 = rarest). Refreshed by the rarity command.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="set_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Edition / print-run number engraved on the Frame. Admin-assigned per tier (4 consecutive numbers per series).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="earn_rank",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Permanent all-time earn order (the Nth profile to earn this badge tier). Stamped at award; never changes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="status",
            field=models.CharField(
                choices=[("earned", "Earned"), ("maintenance", "Maintenance")],
                default="earned",
                help_text="Earned badges are NEVER deleted. If a series grows and the user lapses, the badge enters 'maintenance' (repair) instead of being revoked, so earn_rank stays permanent.",
                max_length=12,
            ),
        ),
    ]
