# Generated by Django 5.2.7 on 2026-06-12 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trophies",
            "0243_badge_developer_badge_franchise_badge_rarity_class_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated IGDB collection (source_type='collection'). Frame attribution + reporting. Franchise takes display precedence when both are set.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_badges",
                to="trophies.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="franchise",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated IGDB franchise (source_type='franchise'). Drives the Frame's subject name + enables franchise reporting.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="badges",
                to="trophies.franchise",
            ),
        ),
    ]
