# Generated by Django 5.2.7 on 2026-06-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0244_badge_collection_alter_badge_franchise"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="franchises_locked",
            field=models.BooleanField(
                default=False,
                help_text="When True, IGDB refresh/enrichment will NOT wipe or rebuild this concept's Franchise/Collection links (ConceptFranchise rows), so manually-curated links and is_main flags survive every sync. Set by admins who've hand-tuned a concept's franchise/collection membership (e.g. excluding a spin-off's parent collection).",
            ),
        ),
    ]
