# Generated by Django 5.2.7 on 2026-06-13 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0245_concept_franchises_locked"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "is_live",
                    models.BooleanField(
                        default=False,
                        help_text="Visible/active to users. Curate while False.",
                    ),
                ),
                (
                    "xp_total_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override the global base XP total for this Contract (special cases only).",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Staff curation notes."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("combat", "Combat"),
                            ("exploration", "Exploration"),
                            ("mind", "Mind"),
                            ("heart", "Heart"),
                            ("finesse", "Finesse"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hex color for UI theming (set in the visual pass).",
                        max_length=20,
                    ),
                ),
                (
                    "is_fallback",
                    models.BooleanField(
                        default=False,
                        help_text="True only for Freelancer (the no-specialization catch-all).",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["discipline", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContractBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label, e.g. 'Collection list covers this game'.",
                        max_length=120,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "concepts",
                    models.ManyToManyField(
                        related_name="contract_bundles", to="trophies.concept"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="trophies.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ContractMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_membership",
                        to="trophies.concept",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="trophies.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["contract"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="jobs",
            field=models.ManyToManyField(
                blank=True,
                help_text="The job profile -- job XP splits evenly across these jobs.",
                related_name="contracts",
                to="trophies.job",
            ),
        ),
    ]
