# Generated by Django 5.2.7 on 2026-06-14 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0247_seed_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarnedContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_platinum", models.BooleanField(default=False)),
                (
                    "platinum_reached_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When Platinum was completed (became claimable).",
                        null=True,
                    ),
                ),
                (
                    "full_reached_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When 100% was completed (became claimable).",
                        null=True,
                    ),
                ),
                (
                    "platinum_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user accepted the Platinum XP.",
                        null=True,
                    ),
                ),
                (
                    "full_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user accepted the 100% XP.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="trophies.contract",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_contracts",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractXPGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("platinum", "Platinum"), ("full", "100%")],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="XP granted to this job, as paid."
                    ),
                ),
                (
                    "base_t",
                    models.PositiveIntegerField(
                        help_text="The Contract total T in effect when granted."
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Active XP multiplier at grant time (e.g. double-XP events).",
                        max_digits=4,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_grants",
                        to="trophies.job",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_xp_grants",
                        to="trophies.profile",
                    ),
                ),
                (
                    "earned_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="trophies.earnedcontract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileJobXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_xp",
                        to="trophies.job",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_xp",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="earnedcontract",
            index=models.Index(fields=["profile"], name="earnedcontract_profile_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="earnedcontract",
            unique_together={("profile", "contract")},
        ),
        migrations.AddIndex(
            model_name="contractxpgrant",
            index=models.Index(
                fields=["profile", "job"], name="xpgrant_profile_job_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractxpgrant",
            unique_together={("earned_contract", "job", "tier")},
        ),
        migrations.AddIndex(
            model_name="profilejobxp",
            index=models.Index(fields=["profile"], name="profilejobxp_profile_idx"),
        ),
        migrations.AddIndex(
            model_name="profilejobxp",
            index=models.Index(
                fields=["job", "total_xp"], name="profilejobxp_job_xp_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profilejobxp",
            unique_together={("profile", "job")},
        ),
    ]
