# Generated by Django 5.2.7 on 2026-06-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0248_earnedcontract_contractxpgrant_profilejobxp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("series", "Series"),
                    ("franchise", "Franchise"),
                    ("collection", "Collection"),
                    ("megamix", "Megamix"),
                    ("developer", "Developer"),
                    ("user", "User"),
                    ("event", "Event"),
                ],
                default="series",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="set_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Edition / print-run number engraved on the Frame. Admin-assigned per tier (4 consecutive numbers per series), numbered independently within each badge type (every type starts its own sequence at 1).",
                null=True,
            ),
        ),
    ]
