# Generated by Django 5.2.7 on 2026-06-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0249_alter_badge_badge_type_alter_badge_set_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptfranchise",
            name="is_spinoff",
            field=models.BooleanField(
                default=False,
                help_text="True when IGDB types this game's membership in the collection (Series) as a 'Spin-off' rather than a normal 'Member'. Collection links only; always False for franchise links. Spin-offs are suppressed from the Series' game list and from collection badge stage coverage.",
            ),
        ),
        migrations.AddIndex(
            model_name="conceptfranchise",
            index=models.Index(
                fields=["franchise", "is_spinoff"], name="conceptfranchise_spinoff_idx"
            ),
        ),
    ]
