# Generated by Django 5.2.7 on 2026-06-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0250_conceptfranchise_is_spinoff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="discord_role_id",
        ),
    ]
