# Generated by Django 5.2.7 on 2026-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0251_remove_badge_discord_role_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conceptfranchise",
            name="conceptfranchise_main_idx",
        ),
        migrations.RemoveField(
            model_name="conceptfranchise",
            name="is_main",
        ),
        migrations.AddField(
            model_name="conceptfranchise",
            name="is_excluded",
            field=models.BooleanField(
                default=False,
                help_text="Admin override. When True, every consumer (browse list, franchise detail page, game detail page, franchise-tier badge coverage) filters this link out as if IGDB had never listed it. Survives IGDB refresh only on locked concepts (concept.franchises_locked=True).",
            ),
        ),
        migrations.AddIndex(
            model_name="conceptfranchise",
            index=models.Index(
                condition=models.Q(("is_excluded", True)),
                fields=["is_excluded"],
                name="conceptfranchise_excl_idx",
            ),
        ),
    ]
