# Generated by Django 5.2.7 on 2026-06-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0252_remove_conceptfranchise_conceptfranchise_main_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="franchises_locked",
            field=models.BooleanField(
                default=False,
                help_text="When True, IGDB refresh/enrichment will NOT wipe or rebuild this concept's Franchise/Collection links (ConceptFranchise rows), so manually-curated links and is_excluded / is_spinoff admin overrides survive every sync. Set by admins who've hand-tuned a concept's franchise/collection membership.",
            ),
        ),
    ]
