# Generated by Django 5.2.7 on 2026-06-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0253_alter_concept_franchises_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="If False the milestone is RETIRED: hidden from the milestones page and no longer awarded. Existing earned records persist. Retire via the retire_milestones command, which also removes the titles it granted.",
            ),
        ),
    ]
