# Generated by Django 5.2.7 on 2026-06-29 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0254_milestone_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractxpgrant",
            name="source",
            field=models.CharField(
                choices=[
                    ("contract", "Contract"),
                    ("quest", "Quest"),
                    ("event", "Event"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="contract",
                help_text="Where this XP came from.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contractxpgrant",
            name="source_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Id of the granting object (quest id, etc.) when not a contract.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contractxpgrant",
            name="base_t",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The Contract total T in effect when granted (contract source only).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contractxpgrant",
            name="earned_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="trophies.earnedcontract",
            ),
        ),
        migrations.AlterField(
            model_name="contractxpgrant",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[("platinum", "Platinum"), ("full", "100%")],
                max_length=10,
                null=True,
            ),
        ),
    ]
