# Generated by Django 5.2.7 on 2026-07-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0255_contractxpgrant_source_contractxpgrant_source_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="avg_completion",
            field=models.FloatField(
                default=0.0,
                help_text="Denormalized average of profiles' completion progress (0-100).",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="full_completion_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of profiles at 100% completion (progress=100).",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="plats_earned_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of profiles that have earned this game's platinum.",
            ),
        ),
    ]
