# Generated by Django 5.2.7 on 2026-07-05 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0256_job_icons"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressionMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("job_tier", "Job tier"),
                            ("pursuer_rank", "Pursuer rank"),
                        ],
                        max_length=16,
                    ),
                ),
                ("key", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=48)),
                ("level_at", models.PositiveIntegerField()),
                ("from_first_claim", models.BooleanField(default=False)),
                ("reached_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="trophies.job",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["profile", "reached_at"],
                        name="milestone_profile_time_idx",
                    ),
                    models.Index(
                        fields=["profile", "kind"], name="milestone_profile_kind_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "kind", "key", "job"),
                        name="uniq_milestone_job",
                    )
                ],
            },
        ),
    ]
