# Generated by Django 5.2.7 on 2026-07-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0257_progressionmilestone"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="progressionmilestone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job__isnull", True)),
                fields=("profile", "kind", "key"),
                name="uniq_milestone_rank",
            ),
        ),
    ]
