# Generated by Django 5.2.7 on 2026-07-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0257_universal_search_trgm_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="contract_satisfier_only",
            field=models.BooleanField(
                default=False,
                help_text="This concept's trophy list spans MULTIPLE games that each have their own Contract (e.g. a remaster collection like Uncharted: Legacy of Thieves). It must be a bundle SATISFIER, never a home MEMBER: the membership admin refuses to home it, and the Stage -> Contract converter attaches it as a ContractBundle instead. Set by hand -- appearing in multiple Stages alone doesn't imply this (a single game can be in many badges). See list_multi_stage_concepts.",
            ),
        ),
    ]
