# Generated by Django 5.2.7 on 2026-07-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0258_progressionmilestone_uniq_milestone_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="badge_detail_tour_completed_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="game_detail_tour_completed_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="tour_completed_at",
        ),
    ]
