# Generated by Django 5.2.7 on 2026-07-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0258_concept_contract_satisfier_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concept",
            name="contract_satisfier_only",
        ),
        migrations.AddField(
            model_name="contract",
            name="igdb_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="The raw IGDB game id this Contract represents; its member concepts are all ANCHORED Concepts sharing this id. Leave null for an admin/episodic Contract whose concepts come from its bundles instead.",
                null=True,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="ContractMembership",
        ),
    ]
