# Generated by Django 5.2.7 on 2026-07-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0256_game_avg_completion_game_full_completion_count_and_more"),
        ("trophies", "0259_remove_profile_badge_detail_tour_completed_at_and_more"),
    ]

    operations = []
