# Generated by Django 5.2.7 on 2026-07-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0257_universal_search_trgm_indexes"),
        ("trophies", "0260_merge_20260718_0900"),
    ]

    operations = []
