# Generated by Django 5.2.7 on 2026-07-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0258_concept_contract_satisfier_only"),
        ("trophies", "0261_merge_20260718_1341"),
    ]

    operations = []
