# Generated by Django 5.2.7 on 2026-07-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0259_contracts_igdb_keyed"),
        ("trophies", "0262_merge_20260718_1931"),
    ]

    operations = []
