# Generated by Django 5.2.7 on 2026-07-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0262_profilegame_pg_playtime_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconceptrating",
            name="blurb",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional short public quick take (<=140 chars).",
                max_length=140,
            ),
        ),
        migrations.AddField(
            model_name="userconceptrating",
            name="blurb_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Staff soft-hide of an inappropriate blurb; the rating itself is unaffected.",
            ),
        ),
        migrations.AddIndex(
            model_name="userconceptrating",
            index=models.Index(
                condition=models.Q(
                    models.Q(("blurb", ""), _negated=True), ("blurb_hidden", False)
                ),
                fields=["concept", "concept_trophy_group", "-updated_at"],
                name="rating_blurb_idx",
            ),
        ),
    ]
