# Generated by Django 5.2.7 on 2026-07-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0262_profilegame_pg_playtime_idx"),
        ("trophies", "0264_merge_20260723_0813"),
    ]

    operations = []
