# Generated by Django 5.2.7 on 2026-07-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0265_merge_20260724_2106"),
        ("trophies", "0265_rating_blurb_idx"),
    ]

    operations = []
