# Generated by Django 5.2.7 on 2026-08-01 11:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0266_merge_0265_merge_20260724_2106_0265_rating_blurb_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable key, e.g. 'legacy-hd', 'ultra-hd'.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Legacy HD'.", max_length=60
                    ),
                ),
                (
                    "platforms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        default=list,
                        help_text="PSN title_platform values in this group, e.g. ['PS3','PSVITA']. A Game joins the group when its title_platform list intersects this.",
                        size=None,
                    ),
                ),
                (
                    "exclude_delisted",
                    models.BooleanField(
                        default=False,
                        help_text="If True, delisted games do NOT gate this group's badges (they still SATISFY if earned). Legacy HD=False (delisting is a no-op, immunizing it against the store closure); Ultra HD=True.",
                    ),
                ),
                (
                    "medallion_shape",
                    models.CharField(
                        blank=True,
                        help_text="Visual key for the group's medallion shape (shared across all series).",
                        max_length=40,
                    ),
                ),
                (
                    "backing_key",
                    models.CharField(
                        blank=True,
                        help_text="Visual key for the group's medallion backing (shared across all series).",
                        max_length=40,
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Default backdrop shared by every badge in this group (bg1 for Legacy, bg2 for Ultra, ...).",
                        null=True,
                        upload_to="badges/group_bg/",
                    ),
                ),
                (
                    "holo_background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional upgraded backdrop shown when a badge in this group is holo.",
                        null=True,
                        upload_to="badges/group_bg/",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BadgeSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series_slug",
                    models.SlugField(
                        help_text="Stable series identity; shared by this series' group badges.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("series", "Series"),
                            ("franchise", "Franchise"),
                            ("collection", "Collection"),
                            ("developer", "Developer"),
                            ("user", "User"),
                            ("event", "Event"),
                            ("megamix", "Megamix"),
                        ],
                        default="series",
                        help_text="Attribution/flavor (drives subject name, set-numbering group, display label). All types share one earn engine.",
                        max_length=12,
                    ),
                ),
                (
                    "completion_policy",
                    models.CharField(
                        choices=[
                            ("all", "All gating stages"),
                            ("min_count", "N of M gating stages (megamix)"),
                        ],
                        default="all",
                        help_text="How a group badge is earned: 'all' gating stages, or 'min_count' (megamix).",
                        max_length=12,
                    ),
                ),
                (
                    "min_required",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="For completion_policy='min_count' (megamix): stages needed. Interpretation under the per-group split is resolved by the evaluator.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_series", models.CharField(blank=True, max_length=100)),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        help_text="Default subject artwork for the series (sits on the group background).",
                        null=True,
                        upload_to="badges/series/",
                    ),
                ),
                (
                    "holo_badge_image",
                    models.ImageField(
                        blank=True,
                        help_text="Default upgraded subject artwork shown when a badge is holo.",
                        null=True,
                        upload_to="badges/series/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_badge_series",
                        to="trophies.franchise",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="developed_badge_series",
                        to="trophies.company",
                    ),
                ),
                (
                    "franchise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="badge_series",
                        to="trophies.franchise",
                    ),
                ),
                (
                    "funded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Donor credited for the default artwork.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="funded_badge_series",
                        to="trophies.profile",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Credited submitter for 'user' badges; also the source of the badge art (their avatar) when no image is set.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_badge_series",
                        to="trophies.profile",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        help_text="One title per series; granted when the profile earns ANY of the series' group badges.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="badge_series",
                        to="trophies.title",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_live",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden until released. Dormant grouping badges stay False until the cutover flip.",
                    ),
                ),
                (
                    "set_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Edition/print-run number engraved on the medallion. Assigned by the new numbering scheme (see rebuild doc).",
                        null=True,
                    ),
                ),
                (
                    "earned_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Active earners (status='earned'). Rarity uses the same count.",
                    ),
                ),
                (
                    "required_stages",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of gating stages for THIS group (recomputed from the group's platform routing).",
                    ),
                ),
                ("rarity_pct", models.FloatField(blank=True, null=True)),
                ("rarity_rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rarity_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("mythic", "Mythic"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "badge_image_override",
                    models.ImageField(
                        blank=True,
                        help_text="Per-group subject artwork; null inherits BadgeSeries.badge_image.",
                        null=True,
                        upload_to="badges/group/",
                    ),
                ),
                (
                    "holo_badge_image_override",
                    models.ImageField(
                        blank=True,
                        help_text="Per-group holo artwork; null inherits BadgeSeries.holo_badge_image.",
                        null=True,
                        upload_to="badges/group/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "funded_by_override",
                    models.ForeignKey(
                        blank=True,
                        help_text="Per-group art funder; null inherits BadgeSeries.funded_by. Travels with badge_image_override.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="funded_group_badges",
                        to="trophies.profile",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_badges",
                        to="trophies.badgeseries",
                    ),
                ),
                (
                    "platform_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_badges",
                        to="trophies.platformgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["series", "platform_group"],
            },
        ),
        migrations.CreateModel(
            name="UserGroupBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("earned", "Earned"), ("maintenance", "Maintenance")],
                        default="earned",
                        help_text="Earned badges are NEVER deleted. If the series grows and the profile lapses, the badge enters 'maintenance' (repair) instead of being revoked, so earn_rank stays permanent.",
                        max_length=12,
                    ),
                ),
                (
                    "earn_rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Permanent completion-ordered rank (the Nth profile to COMPLETE this group badge). Seeded from historical completion dates at cutover; stamped once, never recomputed.",
                        null=True,
                    ),
                ),
                (
                    "is_holo",
                    models.BooleanField(
                        default=False,
                        help_text="LIVE mastery flag: currently 100% on every gating stage. Flips both ways; cosmetic; no XP.",
                    ),
                ),
                (
                    "is_displayed",
                    models.BooleanField(
                        default=False, help_text="Profile's selected display badge."
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group_badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="trophies.groupbadge",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_badges",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="badgeseries",
            index=models.Index(fields=["series_slug"], name="badgeseries_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="badgeseries",
            index=models.Index(fields=["badge_type"], name="badgeseries_type_idx"),
        ),
        migrations.AddIndex(
            model_name="groupbadge",
            index=models.Index(
                fields=["series", "platform_group"], name="groupbadge_series_group_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupbadge",
            index=models.Index(fields=["is_live"], name="groupbadge_is_live_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="groupbadge",
            unique_together={("series", "platform_group")},
        ),
        migrations.AddIndex(
            model_name="usergroupbadge",
            index=models.Index(
                fields=["profile", "is_displayed"], name="ugb_display_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergroupbadge",
            index=models.Index(
                fields=["group_badge", "status"], name="ugb_badge_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergroupbadge",
            index=models.Index(fields=["earned_at"], name="ugb_earned_at_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usergroupbadge",
            unique_together={("profile", "group_badge")},
        ),
    ]
