# Generated by Django 5.2.7 on 2026-08-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0268_seed_platform_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertitle",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("badge", "Badge"),
                    ("milestone", "Milestone"),
                    ("badge_series", "Badge Series"),
                ],
                help_text="Source of the title",
                max_length=20,
            ),
        ),
    ]
