# Generated by Django 5.2.7 on 2026-08-01 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0269_alter_usertitle_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergroupbadge",
            name="earned_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the base list was completed (the engine's completion date), NOT the sync time. Settable so the backfill can seed historical dates; defaults to now for a fresh earn.",
            ),
        ),
    ]
