# Generated by Django 5.2.7 on 2026-08-01 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0270_alter_usergroupbadge_earned_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileBadgeStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_xp", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "series_xp",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-series XP: {"god-of-war": 1500, ...}',
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_standing",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
    ]
