# Generated by Django 5.2.7 on 2026-08-02 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0271_profilebadgestanding"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="usergroupbadge",
            name="ugb_badge_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="usergroupbadge",
            name="ugb_earned_at_idx",
        ),
        migrations.RemoveField(
            model_name="usergroupbadge",
            name="earn_rank",
        ),
        migrations.RemoveField(
            model_name="usergroupbadge",
            name="status",
        ),
        migrations.AlterField(
            model_name="usergroupbadge",
            name="earned_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="CURRENT-iteration completion date (the engine's earned_date) -- the leaderboard sort key, resynced on re-evaluation if the badge changes. NOT the sync time.",
            ),
        ),
        migrations.AddIndex(
            model_name="usergroupbadge",
            index=models.Index(
                fields=["group_badge", "earned_at"], name="ugb_badge_earned_idx"
            ),
        ),
    ]
