# Generated by Django 5.2.7 on 2026-08-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0272_remove_usergroupbadge_ugb_badge_status_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilebadgestanding",
            name="series_xp",
        ),
        migrations.CreateModel(
            name="SeriesBadgeStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_slug", models.SlugField(max_length=100)),
                ("xp", models.PositiveIntegerField(default=0)),
                (
                    "progress_bp",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Furthest-along fraction, basis points (0-10000).",
                    ),
                ),
                ("stages_cleared", models.PositiveIntegerField(default=0)),
                ("stages_total", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_badge_standings",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["series_slug", "-xp"], name="sbs_series_xp_idx"
                    ),
                    models.Index(
                        fields=["series_slug", "-progress_bp"],
                        name="sbs_series_prog_idx",
                    ),
                ],
                "unique_together": {("profile", "series_slug")},
            },
        ),
    ]
