# Generated by Django 5.2.7 on 2026-08-10 00:06
"""Denormalize the last two live aggregates off the game-detail header.

Both are AddField with a constant default, so Postgres records the default in the
catalogue instead of rewriting the table -- safe to apply to a large `game` table
without a maintenance window.

DEPLOY: both columns land at 0 and are only populated by the nightly
`recalc_earn_rates` cron, so the header's "Total Earns" and "Monthly Players" read
0 until that runs. Run `python manage.py recalc_earn_rates` immediately after
migrating rather than waiting for the cron. See docs/design/rebuild/prod-deploy-checklist.md.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0273_remove_profilebadgestanding_series_xp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="monthly_players_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of profiles that played this game in the last 30 days.",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="total_earns_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of earned trophies across all of this game's trophies.",
            ),
        ),
    ]
