# Generated by Django 5.2.7 on 2026-08-10 00:39
"""Retire the Rarest Trophies showcase type.

It was the only DERIVED showcase. Every other type renders a bounded, user-selected
set (at most 20 ids out of config, or a small owned table), while this one ranked the
profile's ENTIRE earned set by a joined column (trophy__trophy_earn_rate) with no index
able to serve the sort -- a full join plus top-N sort over 250K rows on a heavy account,
running on every profile render including anonymous ones. It was the single most
expensive thing a logged-out visitor could trigger, and a contributing factor in the
2026-08-09 outage.

Removed rather than gated behind auth: the cost is intrinsic to "rank everything I own",
so it would have stayed a liability for signed-in views of large profiles either way.

Mirrors 0237_remove_review_showcase_type: delete the orphaned rows FIRST, then narrow
the choices. Deleting a row frees the slot it occupied, so affected users can pick a
replacement showcase; the resulting gap in `sort_order` is harmless (ordering is
relative, and add_showcase appends at Max+1).

Irreversible in the data direction by design -- the reverse is a noop rather than a
resurrection, since the config held only a display toggle and the item set was always
recomputed from trophies rather than stored.
"""
from django.db import migrations, models


def delete_rarest_trophies_showcases(apps, schema_editor):
    """Delete ProfileShowcase rows for the retired rarest_trophies type."""
    ProfileShowcase = apps.get_model("trophies", "ProfileShowcase")
    ProfileShowcase.objects.filter(showcase_type="rarest_trophies").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0274_game_community_stats_denorm"),
    ]

    operations = [
        migrations.RunPython(
            delete_rarest_trophies_showcases, migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="profileshowcase",
            name="showcase_type",
            field=models.CharField(
                choices=[
                    ("platinum_case", "Platinum Trophy Case"),
                    ("favorite_games", "Favorite Games"),
                    ("badge_showcase", "Badge Showcase"),
                    ("recent_platinums", "Recent Platinums"),
                    ("challenge_showcase", "Challenge Showcase"),
                    ("title_showcase", "Title Showcase"),
                ],
                max_length=30,
            ),
        ),
    ]
