# Generated by Django 5.2.7 on 2026-08-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0275_platform_group_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="seriesbadgestanding",
            name="group_progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-edition read-model {platform_group_key: [stages_cleared, gating_count]} for editions with partial progress -- lets the Collection show each edition's own progress without a live eval.",
            ),
        ),
    ]
