# Generated by Django 5.2.7 on 2026-08-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0275_remove_rarest_trophies_showcase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="view_count",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="view_count",
        ),
        migrations.RemoveField(
            model_name="game",
            name="view_count",
        ),
        migrations.RemoveField(
            model_name="gamelist",
            name="view_count",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="view_count",
        ),
    ]
