# Generated by Django 5.2.7 on 2026-08-29 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trophies",
            "0276_remove_badge_view_count_remove_checklist_view_count_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PSNConceptData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "psn_concept_id",
                    models.CharField(
                        db_index=True,
                        help_text="PSN's own concept id, unprefixed. Concept.concept_id may be an IGDB anchor or a PP_* stub, so this is the only reliable record of the PSN identity. NOT unique on its own -- one row per (id, region).",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("publisher_name", models.CharField(blank=True, max_length=255)),
                ("genres", models.JSONField(blank=True, default=list)),
                ("subgenres", models.JSONField(blank=True, default=list)),
                ("descriptions", models.JSONField(blank=True, default=dict)),
                ("content_rating", models.JSONField(blank=True, default=dict)),
                ("media", models.JSONField(blank=True, default=dict)),
                ("country", models.CharField(blank=True, max_length=8)),
                ("language", models.CharField(blank=True, max_length=8)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="The concept that most recently resolved this PSN storefront entry. May move: one PSN concept id can span several Concepts once IGDB anchoring splits editions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="psn_data",
                        to="trophies.concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "PSN concept data",
                "verbose_name_plural": "PSN concept data",
            },
        ),
        migrations.CreateModel(
            name="PSNRawPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text='The full get_details response, exactly as PSN returned it. We consume ~8 keys of it; keeping the rest is what makes "what does PSN actually send us?" answerable.'
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "psn_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw",
                        to="trophies.psnconceptdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "PSN raw payload",
                "verbose_name_plural": "PSN raw payloads",
            },
        ),
        migrations.AddConstraint(
            model_name="psnconceptdata",
            constraint=models.UniqueConstraint(
                fields=("psn_concept_id", "country"),
                name="psn_concept_data_unique_per_region",
            ),
        ),
    ]
