# Generated by Django 5.2.7 on 2026-08-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0276_seriesbadgestanding_group_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="representative_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="trophies.game",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="representative_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="trophies.game",
            ),
        ),
    ]
