# Generated by Django 5.2.7 on 2026-08-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0277_genre_representative_game_theme_representative_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="related_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="theme",
            name="related_tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
