# Generated by Django 5.2.7 on 2026-08-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0277_psn_concept_data_capture"),
    ]

    operations = [
        migrations.CreateModel(
            name="PSNTitleObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("np_communication_id", models.CharField(max_length=50)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("trophy_titles", "Trophy titles walk"),
                            ("title_stats", "Title stats endpoint"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title_name_raw", models.CharField(blank=True, max_length=255)),
                ("title_detail", models.TextField(blank=True)),
                ("title_icon_url", models.CharField(blank=True, max_length=500)),
                ("np_service_name", models.CharField(blank=True, max_length=50)),
                ("trophy_set_version", models.CharField(blank=True, max_length=16)),
                ("title_platform", models.JSONField(blank=True, default=list)),
                ("has_trophy_groups", models.BooleanField(blank=True, null=True)),
                ("defined_trophies", models.JSONField(blank=True, default=dict)),
                ("np_title_id", models.CharField(blank=True, max_length=32)),
                ("stats_category", models.CharField(blank=True, max_length=32)),
                ("content_hash", models.CharField(max_length=64)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pointer, not ownership: the observation outlives the Game row.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="psn_observations",
                        to="trophies.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "PSN title observation",
                "verbose_name_plural": "PSN title observations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("np_communication_id", "content_hash"),
                        name="psn_title_obs_unique_content",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            # fillfactor 85: Django creates tables at the Postgres default of 100 (packed pages),
            # which forces the first UPDATE on each page off-page (non-HOT), writing into every
            # index. This table's last_seen_at bump is its one recurring UPDATE; headroom keeps
            # those updates HOT. Safe on an empty table; reverse is a no-op (fillfactor only
            # affects future writes).
            sql="ALTER TABLE trophies_psntitleobservation SET (fillfactor = 85);",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]