# Generated by Django 5.2.7 on 2026-09-01 02:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0278_psn_title_observations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igdb_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=500)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("A", "A (auto)"),
                            ("B", "B (review)"),
                            ("C", "C (snooze)"),
                        ],
                        max_length=1,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=16)),
                ("players", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("review", "Review"),
                            ("snoozed", "Snoozed"),
                            ("dismissed", "Dismissed"),
                            ("done", "Done"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="The auto-staged Contract, when status is staged.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="trophies.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["-players"],
                "indexes": [
                    models.Index(
                        fields=["status", "-players"], name="contract_cand_queue_idx"
                    )
                ],
            },
        ),
    ]
