# Generated by Django 5.2.7 on 2026-08-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0284_merge_anon_render_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="monthly_earners_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denormalized count of profiles that earned a trophy in this game in the last 30 days.",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["-monthly_earners_count"], name="game_monthly_earners_idx"
            ),
        ),
    ]
