# Generated by Django 5.2.7 on 2026-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0285_game_monthly_earners_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbadge",
            name="rarity_floor_pct",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="rarity_floor_pct",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
