# Generated by Django 5.2.7 on 2026-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0285_game_monthly_earners_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seriesbadgestanding",
            name="group_progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-edition read-model {platform_group_key: [stages_cleared, gating_count]} for every EARNABLE edition (gating_count > 0), started or not -- so an untouched edition still carries its denominator. Lets the Collection show each edition's own progress without a live eval.",
            ),
        ),
    ]
