# Generated by Django 5.2.7 on 2026-08-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0286_alter_seriesbadgestanding_group_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyrecap",
            name="badge_xp_earned",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Badge XP earned in this month, bucketed from the engine's stage/badge completion dates (badge_xp.monthly_xp). Snapshotted at generation; there is no XP ledger.",
            ),
        ),
    ]
