# Generated by Django 5.2.7 on 2026-08-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0286_alter_seriesbadgestanding_group_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyrecap",
            name="badge_xp_earned",
        ),
    ]
