# Generated by Django 5.2.7 on 2026-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0287_alter_monthlyrecap_badge_xp_earned"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyrecap",
            name="community_comparison_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="This month's headline game vs the community's denormed stats (get_community_comparison_for_month).",
            ),
        ),
        migrations.AddField(
            model_name="monthlyrecap",
            name="month_in_history_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="This same month across the hunter's other years, plus a first-platinum anniversary when one falls here (get_month_in_history).",
            ),
        ),
        migrations.AddField(
            model_name="monthlyrecap",
            name="taste_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Top genre + franchise for the month (get_taste_for_month).",
            ),
        ),
    ]
