# Generated by Django 5.2.7 on 2026-08-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "trophies",
            "0276_remove_badge_view_count_remove_checklist_view_count_and_more",
        ),
        ("trophies", "0289_reset_recap_viewed_for_ceremony"),
    ]

    operations = []
