# Generated by Django 5.2.7 on 2026-08-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0290_merge_20260812_1843"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profile",
            name="trophies_pr_user_is_0fb999_idx",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="banner_image_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="banner_position",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="selected_background",
        ),
    ]
