# Generated by Django 5.2.7 on 2026-08-14 07:31

from django.db import migrations, models


def delete_challenge_showcases(apps, schema_editor):
    """Drop rows of the retired type.

    The AlterField below only narrows the CHOICES, which Django does not enforce at the database
    level -- without this, every existing row keeps a showcase_type the registry cannot resolve, and
    `get_descriptor` raises for it. Mirrors how `review_showcase` (0237) and `rarest_trophies` (0275)
    were retired.
    """
    apps.get_model("trophies", "ProfileShowcase").objects.filter(
        showcase_type="challenge_showcase"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0291_drop_profile_banner_fields"),
    ]

    operations = [
        # Data first: the rows must go while the type is still a legal value.
        migrations.RunPython(delete_challenge_showcases, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profileshowcase",
            name="showcase_type",
            field=models.CharField(
                choices=[
                    ("platinum_case", "Platinum Trophy Case"),
                    ("favorite_games", "Favorite Games"),
                    ("badge_showcase", "Badge Showcase"),
                    ("recent_platinums", "Recent Platinums"),
                    ("title_showcase", "Title Showcase"),
                ],
                max_length=30,
            ),
        ),
    ]
