# Generated by Django 5.2.7 on 2026-08-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0292_drop_challenge_showcase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="selected_theme",
        ),
    ]
