# Generated by Django 5.2.7 on 2026-08-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0293_drop_profile_selected_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconceptrating",
            name="recommendation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("worth_it", "Do it"),
                    ("good_game_bad_plat", "Great game, rough platinum"),
                    ("bad_game_good_plat", "Only for the trophy"),
                    ("skip", "Skip it"),
                ],
                default="",
                help_text="Would you send someone else after this platinum? Blank = predates the field (re-asked by the wizard).",
                max_length=20,
            ),
        ),
    ]
