# Generated by Django 5.2.7 on 2026-08-15 08:36

from django.db import migrations, models


def retire_the_fourth_option(apps, schema_editor):
    """`bad_game_good_plat` -> `worth_it`.

    The fourth option was live only between 0294 and this migration, so in practice this touches nothing
    outside a dev database -- but `choices` is not enforced at the database level, so a row left holding a
    retired value would survive and then render its raw slug through `get_recommendation_display`.

    `worth_it` is the honest destination, not a downgrade: "only for the trophy" was always a
    recommendation OF THE PLATINUM, which is what this field rates. The "bad game" half of it is carried
    by the star score, which is why three options turned out to be enough.
    """
    apps.get_model('trophies', 'UserConceptRating').objects.filter(
        recommendation='bad_game_good_plat'
    ).update(recommendation='worth_it')


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0294_userconceptrating_recommendation"),
    ]

    operations = [
        # Data first: narrowing `choices` does not touch the column, so a row holding the retired value
        # would otherwise sit there valid-to-Postgres and invalid to the app.
        migrations.RunPython(retire_the_fourth_option, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userconceptrating",
            name="recommendation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("worth_it", "Do it"),
                    ("good_game_bad_plat", "Great game, rough platinum"),
                    ("skip", "Skip it"),
                ],
                default="",
                help_text="Would you send someone else after this platinum? Blank = predates the field (re-asked by the wizard).",
                max_length=20,
            ),
        ),
    ]
