# Generated by Django 5.2.7 on 2026-08-16 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0296_alter_userconceptrating_recommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileCareerStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_xp", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "pursuer_level",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="profilebadgestanding",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="profilebadgestanding",
            name="trophies_bronze",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profilebadgestanding",
            name="trophies_gold",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profilebadgestanding",
            name="trophies_platinum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profilebadgestanding",
            name="trophies_silver",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profilebadgestanding",
            name="trophies_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profilejobxp",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="seriesbadgestanding",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=2),
        ),
        migrations.AddIndex(
            model_name="profilebadgestanding",
            index=models.Index(
                fields=["-trophies_platinum", "-trophies_total"],
                name="pbs_progress_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profilebadgestanding",
            index=models.Index(
                fields=["country_code", "-total_xp"], name="pbs_country_xp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilebadgestanding",
            index=models.Index(
                fields=["country_code", "-trophies_platinum", "-trophies_total"],
                name="pbs_country_prog_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profilejobxp",
            index=models.Index(
                fields=["job", "country_code", "-total_xp"], name="pjx_job_cc_xp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seriesbadgestanding",
            index=models.Index(
                fields=["series_slug", "country_code", "-xp"],
                name="sbs_series_cc_xp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="seriesbadgestanding",
            index=models.Index(
                fields=["series_slug", "country_code", "-progress_bp"],
                name="sbs_series_cc_prog_idx",
            ),
        ),
        migrations.AddField(
            model_name="profilecareerstanding",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_standing",
                to="trophies.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="profilecareerstanding",
            index=models.Index(
                fields=["country_code", "-total_xp"], name="pcs_country_xp_idx"
            ),
        ),
    ]
