# Generated by Django 5.2.7 on 2026-08-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0297_leaderboard_standings"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profilebadgestanding",
            name="pbs_country_troph_idx",
        ),
        migrations.RemoveIndex(
            model_name="seriesbadgestanding",
            name="sbs_series_prog_idx",
        ),
        migrations.RemoveIndex(
            model_name="seriesbadgestanding",
            name="sbs_series_cc_prog_idx",
        ),
        migrations.AddField(
            model_name="seriesbadgestanding",
            name="advanced_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profilebadgestanding",
            name="trophies_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="profilebadgestanding",
            index=models.Index(
                fields=["-trophies_platinum", "-trophies_total"],
                name="pbs_progress_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profilebadgestanding",
            index=models.Index(
                fields=["country_code", "-trophies_platinum", "-trophies_total"],
                name="pbs_country_prog_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="seriesbadgestanding",
            index=models.Index(
                fields=["series_slug", "-progress_bp", "advanced_at"],
                name="sbs_series_board_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="seriesbadgestanding",
            index=models.Index(
                fields=["series_slug", "country_code", "-progress_bp", "advanced_at"],
                name="sbs_series_cc_board_idx",
            ),
        ),
    ]
