# Generated by Django 5.2.7 on 2026-08-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0298_leaderboard_board_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilebadgestanding",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="profilecareerstanding",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="profilejobxp",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="seriesbadgestanding",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=5),
        ),
    ]
