# Generated by Django 5.2.7 on 2026-08-17 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0299_widen_standing_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="seriesbadgestanding",
            name="group_xp",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-edition XP {platform_group_key: xp} for this series. Re-summed across the profile's series rows into ProfileEditionStanding, so scoped recomputes stay correct.",
            ),
        ),
        migrations.CreateModel(
            name="ProfileEditionStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_group_key", models.SlugField(max_length=40)),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("trophies_total", models.PositiveIntegerField(default=0)),
                ("trophies_platinum", models.PositiveIntegerField(default=0)),
                ("trophies_gold", models.PositiveIntegerField(default=0)),
                ("trophies_silver", models.PositiveIntegerField(default=0)),
                ("trophies_bronze", models.PositiveIntegerField(default=0)),
                (
                    "country_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=5
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edition_standings",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["platform_group_key", "-total_xp"], name="pes_ed_xp_idx"
                    ),
                    models.Index(
                        fields=[
                            "platform_group_key",
                            "-trophies_platinum",
                            "-trophies_total",
                        ],
                        name="pes_ed_troph_idx",
                    ),
                    models.Index(
                        fields=["platform_group_key", "country_code", "-total_xp"],
                        name="pes_ed_cc_xp_idx",
                    ),
                    models.Index(
                        fields=[
                            "platform_group_key",
                            "country_code",
                            "-trophies_platinum",
                            "-trophies_total",
                        ],
                        name="pes_ed_cc_troph_idx",
                    ),
                ],
                "unique_together": {("profile", "platform_group_key")},
            },
        ),
    ]
