# Generated by Django 5.2.7 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0300_edition_standings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilebadgestanding",
            name="badges_held",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profileeditionstanding",
            name="badges_held",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
