# Generated by Django 5.2.7 on 2026-08-17 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0301_badges_held"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="profilebadgestanding",
            name="pbs_progress_idx",
        ),
        migrations.RemoveIndex(
            model_name="profilebadgestanding",
            name="pbs_country_prog_idx",
        ),
        migrations.RemoveIndex(
            model_name="profileeditionstanding",
            name="pes_ed_troph_idx",
        ),
        migrations.RemoveIndex(
            model_name="profileeditionstanding",
            name="pes_ed_cc_troph_idx",
        ),
        migrations.RemoveField(
            model_name="profilebadgestanding",
            name="trophies_bronze",
        ),
        migrations.RemoveField(
            model_name="profilebadgestanding",
            name="trophies_gold",
        ),
        migrations.RemoveField(
            model_name="profilebadgestanding",
            name="trophies_platinum",
        ),
        migrations.RemoveField(
            model_name="profilebadgestanding",
            name="trophies_silver",
        ),
        migrations.RemoveField(
            model_name="profilebadgestanding",
            name="trophies_total",
        ),
        migrations.RemoveField(
            model_name="profileeditionstanding",
            name="trophies_bronze",
        ),
        migrations.RemoveField(
            model_name="profileeditionstanding",
            name="trophies_gold",
        ),
        migrations.RemoveField(
            model_name="profileeditionstanding",
            name="trophies_platinum",
        ),
        migrations.RemoveField(
            model_name="profileeditionstanding",
            name="trophies_silver",
        ),
        migrations.RemoveField(
            model_name="profileeditionstanding",
            name="trophies_total",
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["-total_plats", "-total_trophies", "id"],
                name="profile_board_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["country_code", "-total_plats", "-total_trophies", "id"],
                name="profile_board_cc_idx",
            ),
        ),
    ]
