# Generated by Django 5.2.7 on 2026-08-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0302_trophies_board_on_profile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="profileshowcase",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="profileshowcase",
            name="profile",
        ),
        migrations.DeleteModel(
            name="ProfileBadgeShowcase",
        ),
        migrations.DeleteModel(
            name="ProfileShowcase",
        ),
    ]
