# Generated by Django 5.2.7 on 2026-08-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0303_drop_profile_showcases"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardConfig",
        ),
    ]
