# Generated by Django 5.2.7 on 2026-08-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0314_supporter_wall_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_mark",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
