# Generated by Django 5.2.7 on 2026-08-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0315_role_and_display_mark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="set_number",
        ),
        migrations.RemoveField(
            model_name="groupbadge",
            name="set_number",
        ),
        migrations.AlterField(
            model_name="badgeseries",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("series", "Series"),
                    ("franchise", "Franchise"),
                    ("collection", "Collection"),
                    ("developer", "Developer"),
                    ("user", "User"),
                    ("event", "Event"),
                    ("megamix", "Megamix"),
                ],
                default="series",
                help_text="Attribution/flavor (drives subject name and display label). All types share one earn engine.",
                max_length=12,
            ),
        ),
    ]
