# Generated by Django 5.2.7 on 2026-08-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0277_psn_concept_data_capture"),
        ("trophies", "0316_remove_badge_set_numbers"),
    ]

    operations = []
