# Generated by Django 5.2.7 on 2026-08-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0278_psn_title_observations"),
        ("trophies", "0317_merge_20260829_0838"),
    ]

    operations = []
