# Generated by Django 5.2.7 on 2026-08-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0318_merge_20260829_1527"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="game_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="version_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="franchise",
            name="game_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="franchise",
            name="version_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="genre",
            name="avg_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genre",
            name="game_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="genre",
            name="player_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="theme",
            name="avg_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="game_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="theme",
            name="player_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
