# Generated by Django 5.2.7 on 2026-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0319_browse_denorm_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="went_live_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='When this Contract FIRST went live, i.e. when the community could first see it. Distinct from created_at: the pipeline stages a contract (is_live=False) possibly weeks before staff publish it, so created_at answers "when was this drafted", not "what is new". Stamped once and never reset, so un-publishing and re-publishing does not re-announce a contract.',
                null=True,
            ),
        ),
    ]
