# Generated by Django 5.2.7 on 2026-09-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0320_contract_went_live_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="announced_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When `announce_contracts` posted this Contract to Discord. A COLUMN rather than a cursor/watermark on the side: a watermark that is lost (a Redis flush, a fresh environment) re-announces everything behind it, and one that is ahead silently swallows a wave. Per-row, the answer is exact and survives both.",
                null=True,
            ),
        ),
    ]
