# Generated by Django 5.2.7 on 2026-09-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0279_contract_candidate"),
        ("trophies", "0321_contract_announced_at"),
    ]

    operations = []
