# Generated by Django 5.2.7 on 2026-09-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0322_merge_20260902_0009"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeseries",
            name="artwork_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Borrow this OTHER series' artwork instead of holding your own -- the franchise/series sister case, where one subject deserves one piece of art. The funder credit travels with it, so the donor is credited on both. A series pointing here cannot be claimed for artwork commissioning; claim the SOURCE and both light up.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artwork_dependents",
                to="trophies.badgeseries",
            ),
        ),
    ]
