# Generated by Django 5.2.7 on 2026-09-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0323_badgeseries_artwork_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgeseries",
            name="artwork_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Borrow this OTHER series' artwork instead of holding your own -- the franchise/series sister case, where one subject deserves one piece of art. The funder credit travels with it, so the donor is credited on both. A series pointing here is refused by BOTH the fundraiser's picker and its claim endpoint; claim the SOURCE and both badges light up.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artwork_dependents",
                to="trophies.badgeseries",
            ),
        ),
        migrations.AddConstraint(
            model_name="badgeseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("artwork_source", models.F("id")), _negated=True),
                name="badgeseries_no_self_artwork_source",
            ),
        ),
    ]
