# Generated by Django 5.2.7 on 2026-09-04 14:49

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0324_badgeseries_artwork_source_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        help_text="The actor's name at the time, so the entry still reads after the account is gone.",
                        max_length=150,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("blurb_hidden", "Quick take hidden"),
                            ("blurb_restored", "Quick take restored"),
                            ("blurb_report_dismissed", "Quick take report dismissed"),
                            ("game_flag_approved", "Game flag approved"),
                            ("game_flag_dismissed", "Game flag dismissed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text='REQUIRED, and required by the service rather than by a form the next caller might not use. A log of timestamps with no reasons answers "what happened" and not "why", and only the second one is any use in an appeal.'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_id",
                    models.IntegerField(
                        blank=True,
                        help_text="PK of the object acted on (the rating, the game), captured at the time. The label alone is not identification: it is truncated at 255 and two long-titled games can produce the same one, and once the report is purged the label is all that is left. Mirrors ModerationLog.comment_id_snapshot, which learned this.",
                        null=True,
                    ),
                ),
                (
                    "target_label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable identification of what was acted on, captured at the time.",
                        max_length=255,
                    ),
                ),
                (
                    "changed",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="{field: [before, after]} for whatever the action actually WROTE -- read from the object, never assumed. This is what makes a reversal possible without guessing at the previous state, and `reverse_action` reads it rather than hardcoding. DjangoJSONEncoder so a date or Decimal field added to a flag action later cannot raise mid-transaction.",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="What the action was ABOUT but did not change -- the hidden blurb's text, most of all. Separate from `changed` because an appeal needs the words while a diff view must not render them as a field that was modified.",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The moderator who acted. SET_NULL so deleting a staff account never erases what they did -- `actor_label` keeps the name.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blurb_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to="trophies.blurbreport",
                    ),
                ),
                (
                    "game_flag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to="trophies.gameflag",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        help_text='Set when this entry UNDOES an earlier one. A reversal is logged as its own action rather than by editing or deleting the original -- an audit trail that can be rewritten is not one, and "who reversed this, and why" is exactly the question asked when a decision is disputed.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by_action",
                        to="trophies.moderationaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="modaction_recent_idx"),
                    models.Index(
                        fields=["actor", "-created_at"], name="modaction_actor_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="modaction_action_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reverses__isnull", False)),
                        fields=("reverses",),
                        name="modaction_one_reversal_per_action",
                    )
                ],
            },
        ),
    ]
