# Generated by Django 5.2.7 on 2026-09-05 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0325_moderation_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="moderationaction",
            name="modaction_recent_idx",
        ),
        migrations.RemoveIndex(
            model_name="moderationaction",
            name="modaction_actor_idx",
        ),
        migrations.RemoveIndex(
            model_name="moderationaction",
            name="modaction_action_idx",
        ),
        migrations.AlterField(
            model_name="moderationaction",
            name="actor",
            field=models.ForeignKey(
                db_index=False,
                help_text="The moderator who acted. SET_NULL so deleting a staff account never erases what they did -- `actor_label` keeps the name.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderation_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["-created_at", "-id"], name="modaction_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["actor", "-created_at", "-id"], name="modaction_actor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["action", "-created_at", "-id"], name="modaction_action_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="moderationaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason__regex", "\\S")),
                name="modaction_reason_is_not_blank",
            ),
        ),
    ]
