# Generated by Django 5.2.7 on 2026-09-05 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0326_moderation_log_hardening"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationaction",
            name="subject_label",
            field=models.CharField(
                blank=True,
                help_text="The subject's name at the time. Same reason as `actor_label`.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="subject_user",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                help_text="The hunter whose BEHAVIOUR this entry is evidence about -- which is not always the owner of the thing acted on. Hiding a take: its author. Dismissing a report: the REPORTER, because a dismissal is evidence about them. Approving or dismissing a flag: the reporter. Without one settled rule this column means two things.\n\nIt exists because the report FKs are SET_NULL: once a BlurbReport is purged, an entry could no longer be traced to a person at all -- losing exactly the old history an appeal is about.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderation_decisions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["subject_user", "-created_at", "-id"],
                name="modaction_subject_idx",
            ),
        ),
    ]
