# Generated by Django 5.2.7 on 2026-09-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0328_backfill_moderation_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("blurb_hidden", "Quick take hidden"),
                    ("blurb_restored", "Quick take restored"),
                    ("blurb_report_dismissed", "Quick take report dismissed"),
                    ("blurb_report_reopened", "Quick take report reopened"),
                    ("game_flag_approved", "Game flag approved"),
                    ("game_flag_dismissed", "Game flag dismissed"),
                    ("game_flag_reversed", "Game flag approval reversed"),
                    ("game_flag_reopened", "Game flag reopened"),
                ],
                max_length=32,
            ),
        ),
    ]
