# Generated by Django 5.2.7 on 2026-09-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0331_moderation_proactive_reversal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileTrophyStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clean_plats", models.PositiveIntegerField(default=0)),
                ("clean_trophies", models.PositiveIntegerField(default=0)),
                ("clean_bronzes", models.PositiveIntegerField(default=0)),
                ("clean_silvers", models.PositiveIntegerField(default=0)),
                ("clean_golds", models.PositiveIntegerField(default=0)),
                (
                    "country_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=5
                    ),
                ),
                ("is_linked", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clean_standing",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("clean_trophies__gt", 0), ("is_linked", True)
                        ),
                        fields=["-clean_plats", "-clean_trophies", "profile"],
                        name="pts_board_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("clean_trophies__gt", 0), ("is_linked", True)
                        ),
                        fields=[
                            "country_code",
                            "-clean_plats",
                            "-clean_trophies",
                            "profile",
                        ],
                        name="pts_country_board_idx",
                    ),
                ],
            },
        ),
    ]
