# Generated by Django 5.2.7 on 2026-09-08 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0334_profile_board_indexes_on_raw"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePPStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pp_score", models.PositiveIntegerField(default=0)),
                ("avg_earn_rate", models.FloatField(default=0.0)),
                ("scored_count", models.PositiveIntegerField(default=0)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("is_linked", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pp_standing",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("is_linked", True), ("scored_count__gte", 1000)
                        ),
                        fields=["-pp_score", "profile"],
                        name="pps_board_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("is_linked", True), ("scored_count__gte", 1000)
                        ),
                        fields=["country_code", "-pp_score", "profile"],
                        name="pps_country_board_idx",
                    ),
                ],
            },
        ),
    ]
