# Generated by Django 5.2.7 on 2026-09-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """NO BACKFILL, deliberately.

    Every row already carrying `announced_at` predates this column, so what actually happened to it
    -- posted, or recorded by `--baseline` -- is not recoverable from the data. Defaulting them all
    to False means an old row is treated as never posted, which is the safe direction: the cost is a
    contract missing from one Career modal, where the other direction announces a catalogue nobody
    was ever told about.

    On prod that is the whole point: `announce_contracts` has not been registered yet, so the
    ~1,000 launch contracts are exactly the rows this protects readers from.
    """


    dependencies = [
        ("trophies", "0335_profile_rarity_standing"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="announcement_posted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Whether the announcement was actually POSTED, as opposed to recorded. `announced_at` means "the announcer has settled this row" and is what makes it idempotent -- but `--baseline` settles a row by deciding NOT to post it, which is the opposite outcome wearing the same stamp. Only a confirmed 2xx sets this. The Career new-contracts modal reads it, so a backlog recorded as known (the ~1,000 launch contracts, which do carry `went_live_at` despite what the deploy notes long claimed) is never announced to a reader who was never told.',
            ),
        ),
    ]
