# Generated by Django 5.2.7 on 2026-09-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0336_contract_announcement_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgeseries",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"source_type": "collection"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_badge_series",
                to="trophies.franchise",
            ),
        ),
        migrations.AlterField(
            model_name="badgeseries",
            name="franchise",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"source_type": "franchise"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="badge_series",
                to="trophies.franchise",
            ),
        ),
    ]
