# Generated by Django 5.2.7 on 2026-09-20 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamelists", "0007_list_reports"),
        ("trophies", "0337_alter_badgeseries_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationaction",
            name="list_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderation_actions",
                to="gamelists.gamelistreport",
            ),
        ),
        migrations.AlterField(
            model_name="moderationaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("blurb_hidden", "Quick take hidden"),
                    ("blurb_hidden_proactive", "Quick take hidden (no report)"),
                    ("blurb_restored", "Quick take restored"),
                    (
                        "blurb_restored_proactive",
                        "Quick take restored (was hidden without a report)",
                    ),
                    ("blurb_report_dismissed", "Quick take report dismissed"),
                    ("blurb_report_reopened", "Quick take report reopened"),
                    ("list_text_hidden", "List name and description hidden"),
                    ("list_text_restored", "List name and description restored"),
                    ("list_report_dismissed", "List report dismissed"),
                    ("game_flag_approved", "Game flag approved"),
                    ("game_flag_dismissed", "Game flag dismissed"),
                    ("game_flag_reversed", "Game flag approval reversed"),
                    ("game_flag_reopened", "Game flag reopened"),
                ],
                max_length=32,
            ),
        ),
    ]
