# Generated by Django 5.2.7 on 2026-09-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0338_list_report_moderation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("blurb_hidden", "Quick take hidden"),
                    ("blurb_hidden_proactive", "Quick take hidden (no report)"),
                    ("blurb_restored", "Quick take restored"),
                    (
                        "blurb_restored_proactive",
                        "Quick take restored (was hidden without a report)",
                    ),
                    ("blurb_report_dismissed", "Quick take report dismissed"),
                    ("blurb_report_reopened", "Quick take report reopened"),
                    ("list_text_hidden", "List name and description hidden"),
                    ("list_text_restored", "List name and description restored"),
                    ("list_report_dismissed", "List report dismissed"),
                    ("list_report_reopened", "List report reopened"),
                    ("game_flag_approved", "Game flag approved"),
                    ("game_flag_dismissed", "Game flag dismissed"),
                    ("game_flag_reversed", "Game flag approval reversed"),
                    ("game_flag_reopened", "Game flag reopened"),
                ],
                max_length=32,
            ),
        ),
    ]
