# Generated by Django 5.2.7 on 2026-09-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0339_list_report_reopened"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="has_online_trophies",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="required_tiers",
        ),
    ]
