# Generated by Django 5.2.7 on 2026-09-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trophies", "0340_remove_stage_tier_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractxpgrant",
            name="source",
            field=models.CharField(
                choices=[
                    ("contract", "Contract"),
                    ("quest", "Quest"),
                    ("event", "Event"),
                    ("manual", "Manual"),
                    ("challenge", "Challenge"),
                ],
                db_index=True,
                default="contract",
                help_text="Where this XP came from.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usertitle",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("badge", "Badge"),
                    ("milestone", "Milestone"),
                    ("badge_series", "Badge Series"),
                    ("challenge", "Challenge"),
                ],
                help_text="Source of the title",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="contractxpgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "challenge")),
                fields=("profile", "job", "source", "source_id"),
                name="xpgrant_challenge_once_per_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractxpgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "challenge"), _negated=True),
                    ("source_id__isnull", False),
                    _connector="OR",
                ),
                name="xpgrant_challenge_needs_source_id",
            ),
        ),
    ]
