"""
Django settings for plat_pursuit project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
import stripe
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

AUTH_USER_MODEL = "users.CustomUser"
SITE_URL = 'https://platpursuit.com'

ADSENSE_PUB_ID = os.getenv('ADSENSE_PUB_ID')
ADSENSE_ENABLED = os.getenv('ADSENSE_ENABLED', 'False') == 'True'
ADSENSE_TEST_MODE = os.getenv('ADSENSE_TEST_MODE', 'False') == 'True'

STRIPE_MODE = os.getenv('STRIPE_MODE', 'test')

if STRIPE_MODE == 'live':
    STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_LIVE_PUBLISHABLE_KEY')
    STRIPE_SECRET_KEY = os.getenv('STRIPE_LIVE_SECRET_KEY')
else:
    STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_TEST_PUBLISHABLE_KEY')
    STRIPE_SECRET_KEY = os.getenv('STRIPE_TEST_SECRET_KEY')

DJSTRIPE_USE_NATIVE_JSONFIELD = True
DJSTRIPE_FOREIGN_KEY_TO_FIELD = 'id'
DJSTRIPE_WEBHOOK_SECRET = os.getenv(f"STRIPE_{STRIPE_MODE.upper()}_WEBHOOK_SECRET")
DJSTRIPE_WEBHOOK_VALIDATION = 'verify_signature'
DJSTRIPE_WEBHOOK_URL = r"^stripe/webhook/$"
stripe.api_key = STRIPE_SECRET_KEY

# PayPal Configuration
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox')  # 'sandbox' or 'live'

if PAYPAL_MODE == 'live':
    PAYPAL_CLIENT_ID = os.getenv('PAYPAL_LIVE_CLIENT_ID')
    PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_LIVE_CLIENT_SECRET')
else:
    PAYPAL_CLIENT_ID = os.getenv('PAYPAL_SANDBOX_CLIENT_ID')
    PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_SANDBOX_CLIENT_SECRET')

PAYPAL_WEBHOOK_ID = os.getenv(f"PAYPAL_{PAYPAL_MODE.upper()}_WEBHOOK_ID")
PAYPAL_API_BASE = 'https://api-m.paypal.com' if PAYPAL_MODE == 'live' else 'https://api-m.sandbox.paypal.com'

# IGDB (Twitch/Amazon) Game Database
IGDB_CLIENT_ID = os.getenv('IGDB_CLIENT_ID')
IGDB_CLIENT_SECRET = os.getenv('IGDB_CLIENT_SECRET')
IGDB_AUTO_ACCEPT_THRESHOLD = 0.85
IGDB_REVIEW_THRESHOLD = 0.50

# Discord Bot Integration
BOT_API_URL = os.getenv('BOT_API_URL', 'http://127.0.0.1:5000')
BOT_API_KEY = os.getenv('BOT_API_KEY')

DISCORD_PLATINUM_WEBHOOK_URL = os.getenv('DISCORD_PLATINUM_WEBHOOK_URL')
DISCORD_TEST_WEBHOOK_URL = os.getenv('DISCORD_TEST_WEBHOOK_URL')
PLATINUM_EMOJI_ID = os.getenv('PLATINUM_EMOJI_ID')
PLAT_PURSUIT_EMOJI_ID = os.getenv('PLAT_PURSUIT_EMOJI_ID')

DISCORD_PREMIUM_ROLE = os.getenv('DISCORD_PREMIUM_ROLE')
if DISCORD_PREMIUM_ROLE:
    try:
        DISCORD_PREMIUM_ROLE = int(DISCORD_PREMIUM_ROLE)
    except ValueError:
        DISCORD_PREMIUM_ROLE = 0
else:
    DISCORD_PREMIUM_ROLE = 0

DISCORD_PREMIUM_PLUS_ROLE = os.getenv('DISCORD_PREMIUM_PLUS_ROLE')
if DISCORD_PREMIUM_PLUS_ROLE:
    try:
        DISCORD_PREMIUM_PLUS_ROLE = int(DISCORD_PREMIUM_PLUS_ROLE)
    except ValueError:
        DISCORD_PREMIUM_PLUS_ROLE = 0
else:
    DISCORD_PREMIUM_PLUS_ROLE = 0

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS if origin.strip()]
CSRF_TRUSTED_ORIGINS = [
    f"https://{origin.removeprefix('http://').removeprefix('https://')}" if not origin.startswith('http') else origin
    for origin in CSRF_TRUSTED_ORIGINS
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True     # X-Content-Type-Options: nosniff
X_FRAME_OPTIONS = 'DENY'               # Prevent framing entirely
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True            # Safari ITP drops non-HttpOnly cookies more aggressively
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ─── Content Security Policy (django-csp) ────────────────────────────────────
# Pragmatic CSP: allows inline scripts/styles (needed for template <script>
# blocks and Tailwind) while restricting sources to known-good origins.
#
# Google AdSense requires broad access to Google domains for scripts, images,
# iframes, and styles. These are the minimum domains documented by Google.
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],
        "script-src": [
            "'self'",
            "'unsafe-inline'",                    # Template <script> blocks
            "https://cdn.jsdelivr.net",           # chart.js, marked, dompurify, confetti
            "https://pagead2.googlesyndication.com",  # AdSense loader
            "https://www.googletagservices.com",      # AdSense
            "https://adservice.google.com",           # AdSense
            "https://tpc.googlesyndication.com",      # AdSense
            "https://www.google.com",                 # AdSense
        ],
        "style-src": [
            "'self'",
            "'unsafe-inline'",                    # Tailwind + dynamic styles
            "https://fonts.googleapis.com",
        ],
        "font-src": [
            "'self'",
            "https://fonts.gstatic.com",
        ],
        "img-src": [
            "'self'",
            "data:",
            "https://image.api.playstation.com",      # PSN game/trophy icons
            "https://*.playstation.net",               # PSN avatars (legacy CDN)
            "http://*.playstation.net",                # PSN avatars (some stored as http)
            "https://*.s3.amazonaws.com",              # S3 media uploads
            "https://*.sonyentertainmentnetwork.com",  # PSN content rating images
            "https://pagead2.googlesyndication.com",   # AdSense ad images
            "https://tpc.googlesyndication.com",       # AdSense
            "https://www.google.com",                  # AdSense
            "https://www.gstatic.com",                 # AdSense
            "https://images.igdb.com",                 # IGDB company logos & game covers
        ],
        "frame-src": [
            "'self'",
            "https://googleads.g.doubleclick.net",     # AdSense iframes
            "https://tpc.googlesyndication.com",       # AdSense iframes
            "https://www.google.com",                  # AdSense iframes
            "https://www.youtube.com",                 # Roadmap video guides
            "https://www.youtube-nocookie.com",        # Roadmap video guides (privacy-enhanced)
            "https://youtube.com",                     # Roadmap video guides
        ],
        "connect-src": [
            "'self'",
            "https://pagead2.googlesyndication.com",   # AdSense reporting
        ],
        "worker-src": [
            "'self'",
            "blob:",                                 # canvas-confetti Web Worker
        ],
        "frame-ancestors": ["'none'"],
    },
}


DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    'django.contrib.sites',
    'django.contrib.sitemaps',
    "users",
    "core",
    "trophies.apps.TrophiesConfig",
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'api',
    'django_extensions',
    'storages',
    'allauth',
    'allauth.account',
    'djstripe',
    'notifications.apps.NotificationsConfig',
    'fundraiser.apps.FundraiserConfig',
    'django_htmx',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "csp.middleware.CSPMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.AnalyticsSessionMiddleware",  # Analytics session tracking (after auth)
    'allauth.account.middleware.AccountMiddleware',
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'plat_pursuit.middleware.TimezoneMiddleware',
]

# Allauth-specific
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'email2*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_PASSWORD_MIN_LENGTH = 8
ACCOUNT_RATE_LIMITS = {
    'reset_password': '5/m',
    'confirm_email': '5/m',
    'login_failed': '10/m/ip,5/300s/key',  # 10/min per IP + 5 per 5min per email
}
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_CONFIRMATION_AUTO_LOGIN = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Plat Pursuit] '
DEFAULT_FROM_EMAIL = 'Plat Pursuit <no-reply@platpursuit.com>'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login'
ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'
ACCOUNT_FORMS = {'signup': 'users.forms.CustomUserCreationForm'}

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
    SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
    SENDGRID_SANDBOX_MODE_IN_DEBUG = False
    EMAIL_HOST_USER = 'apikey'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'home'
SITE_ID = 1

ROOT_URLCONF = "plat_pursuit.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "plat_pursuit.context_processors.ads",
                "plat_pursuit.context_processors.moderation",
                "plat_pursuit.context_processors.premium_theme_background",
                "plat_pursuit.context_processors.high_sync_volume",
                "plat_pursuit.context_processors.psn_outage",
                "plat_pursuit.context_processors.active_fundraiser",
                "plat_pursuit.context_processors.hub_subnav",
            ],
        },
    },
]

WSGI_APPLICATION = "plat_pursuit.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

database_url = os.getenv('DATABASE_URL')
if database_url:
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600, conn_health_checks=True)
    }
    # Add timeout options for production
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].update({
        'connect_timeout': 10,
        'options': '-c statement_timeout=60000 -c lock_timeout=30000',  # 60s statement, 30s lock
    })
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "plat_pursuit_dev"),
            "USER": os.getenv("DB_USER", "plat_user"),
            "PASSWORD": os.getenv("DB_PASSWORD", "securepass"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5433"),
            "CONN_MAX_AGE": 600,
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {
                'connect_timeout': 10,
                'options': '-c statement_timeout=60000 -c lock_timeout=30000',  # 60s statement, 30s lock
            },
        }
    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.TokenAuthentication',],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated',],
    'DEFAULT_THROTTLE_CLASSES': ['rest_framework.throttling.UserRateThrottle',],
    'DEFAULT_THROTTLE_RATES': {'user': '60/min',},
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# CORS configuration for mobile app
# Token-auth API requests are CSRF-exempt, so CORS is the only cross-origin guard needed.
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if origin.strip()]
if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        'http://localhost:8081',   # Expo dev server (default)
        'http://localhost:19006',  # Expo web dev server
    ]
# Allow Authorization header so mobile clients can send the DRF token
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
# Only expose the API prefix to CORS — the rest of the site is same-origin only
CORS_URLS_REGEX = r'^/api/v1/.*$'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Caching
redis_url = os.getenv('REDIS_URL', 'redis://localhost:6379/1')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': redis_url,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'plat_pursuit'
    }
}

# Notification System Feature Flags
NOTIFICATION_CACHE_ENABLED = os.getenv('NOTIFICATION_CACHE_ENABLED', 'True') == 'True'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

PUBLIC_MEDIA_LOCATION = 'media'
if DEBUG:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
else:
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ACCESS_KEY_ID = os.getenv('AWS_S3_ACCESS_KEY_ID')
    AWS_S3_SECRET_ACCESS_KEY = os.getenv('AWS_S3_SECRET_ACCESS_KEY')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-west-2')
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
    AWS_DEFAULT_ACL = None

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage" if not DEBUG else "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            'location': PUBLIC_MEDIA_LOCATION,
        } if not DEBUG else {},
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "verbose",
            "stream": "ext://sys.stdout",
        },
    },
    "loggers": {
        "psn_api": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        'storages': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Notification settings
NOTIFICATION_RETENTION_DAYS = 90
NOTIFICATION_SSE_HEARTBEAT_INTERVAL = 30