# Generated by Django 5.2.7 on 2026-09-06 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trophies", "0331_moderation_proactive_reversal"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=1000),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Opt-IN. A list is private until its author decides otherwise.",
                    ),
                ),
                (
                    "selected_theme",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Gradient theme key from trophies.themes.GRADIENT_THEMES. Members only.",
                        max_length=50,
                    ),
                ),
                ("game_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The hunter who made it. Lists do not have co-owners.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GameListFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="gamelists.gamelist",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_game_lists",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_entries",
                        to="trophies.concept",
                    ),
                ),
                (
                    "game_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gamelists.gamelist",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="GameListLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="gamelists.gamelist",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_game_lists",
                        to="trophies.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="gamelist",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["owner", "-updated_at"],
                name="glst_owner_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gamelist",
            index=models.Index(
                condition=models.Q(("is_deleted", False), ("is_public", True)),
                fields=["-like_count", "-created_at"],
                name="glst_public_likes_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gamelist",
            index=models.Index(
                condition=models.Q(("is_deleted", False), ("is_public", True)),
                fields=["-created_at"],
                name="glst_public_new_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gamelist",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="gamelist_name_not_blank",
            ),
        ),
        migrations.AddIndex(
            model_name="gamelistfollow",
            index=models.Index(
                fields=["profile", "-created_at"], name="glstfollow_profile_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamelistfollow",
            constraint=models.UniqueConstraint(
                fields=("game_list", "profile"), name="gamelistfollow_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="gamelistitem",
            index=models.Index(
                fields=["game_list", "position"], name="glstitem_position_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamelistitem",
            constraint=models.UniqueConstraint(
                fields=("game_list", "concept"), name="gamelistitem_unique_concept"
            ),
        ),
        migrations.AddIndex(
            model_name="gamelistlike",
            index=models.Index(
                fields=["profile", "-created_at"], name="glstlike_profile_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamelistlike",
            constraint=models.UniqueConstraint(
                fields=("game_list", "profile"), name="gamelistlike_unique"
            ),
        ),
    ]
