# Generated by Django 5.2.7 on 2026-09-08 01:26

"""Drop `selected_theme`, which shipped with no reader.

A migrated column, a validator (`_check_theme`) and a branch in `update_list`, with no template, no
JS and no view ever setting it -- while its `help_text` and the validator's refusal message both
described a members-only perk that did not exist. Cut rather than wired: the gradient themes belong
to the share cards, and a list's theme is a decision for whenever sharing is actually built.

A SEPARATE migration rather than an edit to `0001_initial`, even though both are on the same
unmerged branch. Editing 0001 would be free only if nobody had run it; the branch has been exercised
in a browser, so at least one database already has the column and would be left holding a field the
migration state says was never created.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamelists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamelist",
            name="selected_theme",
        ),
    ]
