# Generated by Django 5.2.7 on 2026-09-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamelists", "0002_remove_gamelist_selected_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelist",
            name="list_type",
            field=models.CharField(
                choices=[("collection", "Collection"), ("ranked", "Ranked")],
                default="collection",
                help_text="How the list presents. Switching is lossless: the rows and their order are the same either way.",
                max_length=20,
            ),
        ),
    ]
