# Generated by Django 5.2.7 on 2026-09-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamelists", "0003_gamelist_list_type"),
        ("trophies", "0336_contract_announcement_posted"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="gamelist",
            constraint=models.CheckConstraint(
                condition=models.Q(("list_type__in", ["collection", "ranked"])),
                name="gamelist_list_type_valid",
            ),
        ),
    ]
