# Generated by Django 5.2.7 on 2026-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamelists", "0004_gamelist_gamelist_list_type_valid"),
        ("trophies", "0336_contract_announcement_posted"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gamelist",
            index=models.Index(
                condition=models.Q(("is_deleted", False), ("is_public", True)),
                fields=["-updated_at"],
                name="glst_public_upd_idx",
            ),
        ),
    ]
