# Generated by Django 5.2.7 on 2026-09-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamelists", "0005_gamelist_glst_public_upd_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelist",
            name="sections_restart_numbering",
            field=models.BooleanField(
                default=False,
                help_text="Sectioned ranked lists only: restart numbering at 1 in each section, rather than running 1..N through the whole list.",
            ),
        ),
        migrations.CreateModel(
            name="GameListSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="gamelists.gamelist",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="gamelistitem",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="gamelists.gamelistsection",
            ),
        ),
        migrations.AddIndex(
            model_name="gamelistsection",
            index=models.Index(
                fields=["game_list", "position"], name="glstsec_position_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gamelistsection",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="gamelistsection_name_not_blank",
            ),
        ),
    ]
