# Generated by Django 5.2.7 on 2026-09-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trophies", "0341_alter_contractxpgrant_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("az", "A-Z Challenge"),
                            ("jobs", "Job Coverage Challenge"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("total_slots", models.PositiveSmallIntegerField()),
                ("filled_count", models.PositiveSmallIntegerField(default=0)),
                ("completed_count", models.PositiveSmallIntegerField(default=0)),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="trophies.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "contract_slug",
                    models.SlugField(
                        blank=True, db_index=False, default="", max_length=255
                    ),
                ),
                (
                    "contract_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("live", "Completed during the run"),
                            ("import", "Imported from history"),
                            ("hatch", "Filled under the scarcity hatch"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("xp_redeemed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenge_slots",
                        to="trophies.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["profile", "-updated_at"],
                name="chal_profile_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                condition=models.Q(("is_complete", True), ("is_deleted", False)),
                fields=["-completed_at"],
                name="chal_completed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                condition=models.Q(("is_complete", True), ("is_deleted", False)),
                fields=["challenge_type", "-completed_at"],
                name="chal_type_completed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_complete", False), ("is_deleted", False)),
                fields=("profile", "challenge_type"),
                name="challenge_one_active_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("challenge_type__in", ["az", "jobs"])),
                name="challenge_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="challenge_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_slots__gt", 0)),
                name="challenge_total_slots_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("filled_count__lte", models.F("total_slots"))),
                name="challenge_filled_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("completed_count__lte", models.F("filled_count"))),
                name="challenge_completed_within_filled",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", False), ("is_complete", True)),
                    models.Q(("completed_at__isnull", True), ("is_complete", False)),
                    _connector="OR",
                ),
                name="challenge_completed_at_matches_flag",
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("deleted_at__isnull", False), ("is_deleted", True)),
                    models.Q(("deleted_at__isnull", True), ("is_deleted", False)),
                    _connector="OR",
                ),
                name="challenge_deleted_at_matches_flag",
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeslot",
            constraint=models.UniqueConstraint(
                fields=("challenge", "key"), name="challengeslot_unique_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeslot",
            constraint=models.UniqueConstraint(
                fields=("challenge", "position"), name="challengeslot_unique_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("contract_slug", ""), _negated=True),
                fields=("challenge", "contract_slug"),
                name="challengeslot_unique_contract",
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_completed", False),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("is_completed", True),
                        models.Q(("contract_slug", ""), _negated=True),
                        models.Q(("completed_via", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="challengeslot_completed_is_filled_dated_and_explained",
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_via", ""),
                    ("completed_via__in", ["hatch", "import", "live"]),
                    _connector="OR",
                ),
                name="challengeslot_completed_via_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("xp_redeemed_at__isnull", True),
                    ("is_completed", True),
                    _connector="OR",
                ),
                name="challengeslot_xp_needs_completion",
            ),
        ),
    ]
