"""One contract per run, keyed on the FK instead of the frozen slug.

The service's duplicate check reads `contract_id`; this constraint read `contract_slug`, so the database
and the only writer disagreed about what "the same game" means. The disagreement was reachable in the
direction that 500s: a staff rename frees a slug, a different contract takes it, and a placement the
service allows (different FK) raises `IntegrityError` on two identical frozen slugs in one run.

OVERLAPPING, NOT NARROWER, and the first version of this docstring said "strictly narrower" while naming
its own exception in the next clause. Per pair of squares in one run:

  - same contract, same frozen slug    -> refused before and after;
  - same contract, DIFFERENT slugs     -> newly REFUSED. A second hole, closed: while the key was the
    snapshot, a renamed contract could legally sit in two job squares;
  - different contracts, same slug     -> newly PERMITTED. This is the `IntegrityError` the change is for;
  - a square whose contract was DELETED -> no longer constrained at all, because a partial unique does not
    constrain NULLs. `assign` gained a dead-snapshot clause to cover it; see its comment.

COULD THE `AddConstraint` FAIL ON EXISTING DATA? Only on the second case above, and only where the
pre-fix service produced it -- the guard matched on the snapshot until a fix landed earlier in this same
branch. No environment has that data (`0001_initial` is dated 2026-09-27 and unmerged), which is why no
data migration is included: the table is new, NOT because "the service already refuses it", which was a
code argument for a data question. Any environment that has run `0001` should be checked first:

    SELECT challenge_id, contract_id, COUNT(*)
      FROM challenges_challengeslot
     WHERE contract_id IS NOT NULL
     GROUP BY challenge_id, contract_id HAVING COUNT(*) > 1;

LOCKING is a non-issue at this size. A conditional `UniqueConstraint` is a partial unique INDEX, so this
drops one and builds another non-concurrently (SHARE, blocking writes for the build) on a table holding
25-26 rows per run. Reusing the name inside one transaction is legal.

SAFE TO APPLY IN EITHER ORDER relative to a deploy, but for a narrower reason than "it is a constraint":
nothing calls `full_clean()`/`validate_constraints()` on `ChallengeSlot` (the admin is read-only with add
and delete off) and no code reads the constraint. Django 5.2 DOES validate conditional uniques in
`full_clean`, so that stops being true the moment a ModelForm touches this model.

A SIDE BENEFIT worth knowing: the new index is `(challenge_id, contract_id) WHERE contract_id IS NOT NULL`,
which is exactly what `eligibility._slot_pool`'s exclusion reads.
"""
# Generated by Django 5.2.7 on 2026-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
        ("trophies", "0341_alter_contractxpgrant_source_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="challengeslot",
            name="challengeslot_unique_contract",
        ),
        migrations.AddConstraint(
            model_name="challengeslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("contract__isnull", False)),
                fields=("challenge", "contract"),
                name="challengeslot_unique_contract",
            ),
        ),
    ]
