# Generated by Django 5.2.7 on 2026-09-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_slot_uniqueness_keys_on_the_contract_fk"),
        ("trophies", "0341_alter_contractxpgrant_source_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="challengeslot",
            index=models.Index(
                condition=models.Q(
                    ("is_completed", True), ("xp_redeemed_at__isnull", True)
                ),
                fields=["challenge"],
                name="chalslot_unclaimed_xp_idx",
            ),
        ),
    ]
