# Generated by Django 5.2.7 on 2026-10-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0003_the_unclaimed_xp_index"),
        ("trophies", "0341_alter_contractxpgrant_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(help_text="1-12.")),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        help_text="1-31, within that month."
                    ),
                ),
                ("in_all", models.BooleanField(default=False)),
                ("in_clean", models.BooleanField(default=False)),
                ("in_contracts", models.BooleanField(default=False)),
                ("earned_on", models.DateField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["month", "day"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="challenge",
            name="challenge_type_valid",
        ),
        migrations.AddField(
            model_name="challenge",
            name="completed_view",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All platinums"),
                    ("clean", "Shovelware free"),
                    ("contracts", "Contracts"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("az", "A-Z Challenge"),
                    ("jobs", "Job Coverage Challenge"),
                    ("calendar", "Plat Calendar"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("challenge_type__in", ["az", "jobs", "calendar"])),
                name="challenge_type_valid",
            ),
        ),
        migrations.AddField(
            model_name="calendarday",
            name="challenge",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_days",
                to="challenges.challenge",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarday",
            constraint=models.UniqueConstraint(
                fields=("challenge", "month", "day"), name="calendarday_unique_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarday",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                name="calendarday_month_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarday",
            constraint=models.CheckConstraint(
                condition=models.Q(("day__gte", 1), ("day__lte", 31)),
                name="calendarday_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("in_clean", False), ("in_all", True), _connector="OR"
                ),
                name="calendarday_clean_implies_all",
            ),
        ),
    ]
