# Generated by Django 5.2.7 on 2026-10-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0003_the_unclaimed_xp_index"),
        ("trophies", "0341_alter_contractxpgrant_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(help_text="1-12.")),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        help_text="1-31, within that month."
                    ),
                ),
                ("in_all", models.BooleanField(default=False)),
                ("in_clean", models.BooleanField(default=False)),
                ("in_contracts", models.BooleanField(default=False)),
                ("earned_on", models.DateTimeField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["month", "day"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="challenge",
            name="challenge_type_valid",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("az", "A-Z Challenge"),
                    ("jobs", "Job Coverage Challenge"),
                    ("calendar", "Plat Calendar"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("challenge_type__in", ["az", "jobs", "calendar"])),
                name="challenge_type_valid",
            ),
        ),
        migrations.AddField(
            model_name="calendarday",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_days",
                to="challenges.challenge",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarday",
            index=models.Index(
                condition=models.Q(("in_all", True)),
                fields=["challenge"],
                name="calday_all_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarday",
            index=models.Index(
                condition=models.Q(("in_clean", True)),
                fields=["challenge"],
                name="calday_clean_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarday",
            index=models.Index(
                condition=models.Q(("in_contracts", True)),
                fields=["challenge"],
                name="calday_contracts_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarday",
            constraint=models.UniqueConstraint(
                fields=("challenge", "month", "day"), name="calendarday_unique_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarday",
            constraint=models.CheckConstraint(
                condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                name="calendarday_month_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarday",
            constraint=models.CheckConstraint(
                condition=models.Q(("day__gte", 1), ("day__lte", 31)),
                name="calendarday_day_range",
            ),
        ),
    ]
