# Generated by Django 5.2.7 on 2026-10-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0004_calendarday_remove_challenge_challenge_type_valid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="calendar_contracts_seen",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="challenge",
            name="calendar_plats_seen",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
