# Generated by Django 5.2.7 on 2026-10-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0005_challenge_calendar_contracts_seen_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="calendarday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("day__lte", 28),
                    ("month__in", [1, 3, 5, 7, 8, 10, 12]),
                    models.Q(("month__in", [4, 6, 9, 11]), ("day__lte", 30)),
                    _connector="OR",
                ),
                name="calendarday_day_within_month",
            ),
        ),
    ]
