# Generated by Django 5.2.7 on 2026-10-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_calendarday_calendarday_day_within_month"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarday",
            name="in_contracts",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="calendar_contracts_seen",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="completed_view",
        ),
    ]
