# Generated by Django 5.2.7 on 2026-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0007_remove_calendarday_in_contracts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarday",
            name="plat_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
