# Generated by Django 5.2.7 on 2026-10-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0008_calendarday_plat_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="opening_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
