# Generated by Django 5.2.7 on 2026-01-29 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique template name", max_length=100, unique=True
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("platinum_earned", "Platinum Trophy Earned"),
                            ("badge_awarded", "Badge Awarded"),
                            ("milestone_achieved", "Milestone Achieved"),
                            ("subscription_created", "Subscription Created"),
                            ("subscription_updated", "Subscription Updated"),
                            ("discord_verified", "Discord Verified"),
                            ("admin_announcement", "Admin Announcement"),
                            ("system_alert", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Use {variable} for substitution, e.g. 'New {trophy_type} earned!'",
                        max_length=255,
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Use {variable} for substitution", max_length=1000
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🔔", help_text="Emoji or icon name", max_length=50
                    ),
                ),
                (
                    "action_url_template",
                    models.CharField(
                        blank=True,
                        help_text="URL template, e.g. '/game/{game_id}/'",
                        max_length=500,
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        help_text="Button text, e.g. 'View Game'",
                        max_length=100,
                    ),
                ),
                (
                    "auto_trigger_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically create notifications when event occurs",
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        blank=True,
                        help_text="Event name that triggers this template",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("platinum_earned", "Platinum Trophy Earned"),
                            ("badge_awarded", "Badge Awarded"),
                            ("milestone_achieved", "Milestone Achieved"),
                            ("subscription_created", "Subscription Created"),
                            ("subscription_updated", "Subscription Updated"),
                            ("discord_verified", "Discord Verified"),
                            ("admin_announcement", "Admin Announcement"),
                            ("system_alert", "System Alert"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(max_length=1000)),
                ("icon", models.CharField(blank=True, default="🔔", max_length=50)),
                ("action_url", models.URLField(blank=True, max_length=500, null=True)),
                ("action_text", models.CharField(blank=True, max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (trophy_id, badge_id, etc.)",
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who receives this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template used to create this notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notificatio_recipie_684eac_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="notificatio_notific_d8746a_idx",
                    ),
                ],
            },
        ),
    ]
