# Generated by Django 5.2.7 on 2026-01-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatinumShareImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("landscape", "Landscape (1200x630)"),
                            ("portrait", "Portrait (1080x1350)"),
                        ],
                        help_text="Image format/dimensions",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Generated share image stored in S3",
                        upload_to="platinum-share-images/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this image has been downloaded",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="The platinum notification this image was generated for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_images",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platinum Share Image",
                "verbose_name_plural": "Platinum Share Images",
                "indexes": [
                    models.Index(
                        fields=["notification", "format"],
                        name="notificatio_notific_aaa8f7_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_c99fa9_idx"
                    ),
                ],
                "unique_together": {("notification", "format")},
            },
        ),
    ]
