# Generated by Django 5.2.7 on 2026-02-03 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_platinumshareimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("platinum_earned", "Platinum Trophy Earned"),
                            ("badge_awarded", "Badge Awarded"),
                            ("milestone_achieved", "Milestone Achieved"),
                            ("subscription_created", "Subscription Created"),
                            ("subscription_updated", "Subscription Updated"),
                            ("discord_verified", "Discord Verified"),
                            ("admin_announcement", "Admin Announcement"),
                            ("system_alert", "System Alert"),
                        ],
                        default="admin_announcement",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(max_length=1000)),
                ("icon", models.CharField(default="📢", max_length=50)),
                ("action_url", models.URLField(blank=True, max_length=500, null=True)),
                ("action_text", models.CharField(blank=True, max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all", "All Active Users"),
                            ("premium_monthly", "Premium Monthly"),
                            ("premium_yearly", "Premium Yearly"),
                            ("premium_supporter", "Premium Supporter"),
                            ("premium_all", "All Premium"),
                            ("discord_verified", "Discord Verified"),
                            ("individual", "Individual Users"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Criteria like {"user_ids": [1,2,3]} for individual targeting',
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated or actual recipient count"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Notification",
                "verbose_name_plural": "Scheduled Notifications",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(max_length=1000)),
                ("target_type", models.CharField(max_length=50)),
                ("target_criteria", models.JSONField(default=dict)),
                ("recipient_count", models.PositiveIntegerField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("was_scheduled", models.BooleanField(default=False)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduled_notification",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to scheduled notification if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notifications.schedulednotification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="schedulednotification",
            index=models.Index(
                fields=["status", "scheduled_at"], name="notificatio_status_831c89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedulednotification",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="notificatio_created_8d5687_idx",
            ),
        ),
    ]
