# Generated by Django 5.2.7 on 2026-02-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_schedulednotification_notificationlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Banner image displayed at top of notification detail view",
                null=True,
                upload_to="notification-banners/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="detail",
            field=models.TextField(
                blank=True,
                help_text="Rich text detail content (supports markdown)",
                max_length=2500,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="detail",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Banner image for scheduled notification",
                null=True,
                upload_to="notification-banners/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="detail",
            field=models.TextField(
                blank=True,
                help_text="Rich text detail content (supports markdown)",
                max_length=2500,
            ),
        ),
    ]
