# Generated by Django 5.2.7 on 2026-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0004_notification_banner_image_notification_detail_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured sections as JSON array. Each section has: id, header, icon, content, order",
            ),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured sections as JSON array. Each section has: id, header, icon, content, order",
            ),
        ),
    ]
