# Generated by Django 5.2.7 on 2026-02-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("platinum_earned", "Platinum Trophy Earned"),
                    ("badge_awarded", "Badge Awarded"),
                    ("milestone_achieved", "Milestone Achieved"),
                    ("monthly_recap", "Monthly Recap Available"),
                    ("subscription_created", "Subscription Created"),
                    ("subscription_updated", "Subscription Updated"),
                    ("discord_verified", "Discord Verified"),
                    ("challenge_completed", "Challenge Completed"),
                    ("review_reply", "Review Reply"),
                    ("review_milestone", "Review Milestone"),
                    ("admin_announcement", "Admin Announcement"),
                    ("system_alert", "System Alert"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_action_required", "Payment Action Required"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("platinum_earned", "Platinum Trophy Earned"),
                    ("badge_awarded", "Badge Awarded"),
                    ("milestone_achieved", "Milestone Achieved"),
                    ("monthly_recap", "Monthly Recap Available"),
                    ("subscription_created", "Subscription Created"),
                    ("subscription_updated", "Subscription Updated"),
                    ("discord_verified", "Discord Verified"),
                    ("challenge_completed", "Challenge Completed"),
                    ("review_reply", "Review Reply"),
                    ("review_milestone", "Review Milestone"),
                    ("admin_announcement", "Admin Announcement"),
                    ("system_alert", "System Alert"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_action_required", "Payment Action Required"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="schedulednotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("platinum_earned", "Platinum Trophy Earned"),
                    ("badge_awarded", "Badge Awarded"),
                    ("milestone_achieved", "Milestone Achieved"),
                    ("monthly_recap", "Monthly Recap Available"),
                    ("subscription_created", "Subscription Created"),
                    ("subscription_updated", "Subscription Updated"),
                    ("discord_verified", "Discord Verified"),
                    ("challenge_completed", "Challenge Completed"),
                    ("review_reply", "Review Reply"),
                    ("review_milestone", "Review Milestone"),
                    ("admin_announcement", "Admin Announcement"),
                    ("system_alert", "System Alert"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_action_required", "Payment Action Required"),
                ],
                default="admin_announcement",
                max_length=50,
            ),
        ),
    ]
