# Generated by Django 5.2.7 on 2026-03-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_devicetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="emails_sent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="emails_suppressed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="email_body_markdown",
            field=models.TextField(
                blank=True,
                help_text="Markdown content for email body (rendered as HTML)",
            ),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="email_cta_text",
            field=models.CharField(
                blank=True,
                help_text="Email CTA button text (defaults to action_text if blank)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="email_cta_url",
            field=models.URLField(
                blank=True,
                help_text="Email CTA button URL (defaults to action_url if blank)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="email_subject",
            field=models.CharField(
                blank=True,
                help_text="Email subject line (defaults to notification title if blank)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="send_email",
            field=models.BooleanField(
                default=False,
                help_text="Also send an email alongside the in-app notification",
            ),
        ),
    ]
