# Generated by Django 5.2.7 on 2026-05-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0015_roadmap_note_mention_per_ctg_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlatinumShareImage",
        ),
    ]
