# Generated by Django 5.2.7 on 2026-08-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0016_drop_platinum_share_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceToken",
        ),
    ]
